<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headScript() ?>
	<?php echo isset($this->google_analytics)?$this->google_analytics:"" ?>
	<?php $baseUrl = Application_Common_OsPath::getBaseDir(); ?>
</head>
<body>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-55N6NH"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-55N6NH');</script>
<!-- End Google Tag Manager -->

<?php echo $this->partial('partialviews/trialBox.phtml', array("is_trial"=>$this->isTrial(), "trial_remain"=> $this->trialRemaining())) ?>

    <div id="Panel" class="sticky">
    <?php if($this->suspended) : ?>
        <?php echo $this->partial('partialviews/suspended.phtml'); ?>
    <?php else : ?>

    <?php echo $this->versionNotify();
            $sss = $this->SourceSwitchStatus();
            $scs = $this->SourceConnectionStatus();
    ?>
    <?php echo $this->partial('partialviews/header.phtml', array("live_dj_switch"=>$sss['live_dj'], "live_dj_connection"=>$scs['live_dj'], "master_dj_switch"=>$sss['master_dj'], "master_dj_connection"=>$scs['master_dj'],
                "scheduled_play_switch"=>$sss['scheduled_play'])) ?>
<?php 	$partial = array('menu.phtml', 'default');
    $this->navigation()->menu()->setPartial($partial); ?>


    <script type="text/javascript">
        var schedulePreLoaded = <?php
        //Awful hack to speed up loading - Embed the schedule in the response so that the dashboard
        //doesn't have to make a separate AJAX request to get this data.
    require_once("ScheduleController.php");
    ScheduleController::printCurrentPlaylistForEmbedding();
 ?>;
        //The DOM elements that these calls depend on exist by this point:
        parseItems(schedulePreLoaded.entries);
        parseSourceStatus(schedulePreLoaded.source_status);
        parseSwitchStatus(schedulePreLoaded.switch_status);

    </script>

    <?php endif; //suspended ?>
</div>

<div id="media_type_nav"> <!-- class="content-pane" -->
    <div class="btn-group">
        <button id="new_media_selector" class="btn btn-small dropdown-toggle dashboard-btn" data-toggle="dropdown">
            New <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li id="new-playlist">
                <a href="#"><?php echo _("Playlist") ?></a>
            </li>
            <li id="new-smart-block">
                <a href="#"><?php echo _("Smart Block") ?></a>
            </li>
            <li id="new-webstream">
                <a href="#"><?php echo _("Webstream") ?></a>
            </li>
        </ul>
        <a href="/Plupload">
            <button id="add_media_btn" class="btn btn-small dashboard-btn">Upload</button>
        </a>
    </div>
    <div class="media_type_selector top-link" data-selection-id="1">
        <a href="/showbuilder#"><i class='icon-home icon-white'></i><?php echo _("Dashboard") ?></a></div>
    <div class="media_type_selector dashboard_sub_nav" data-selection-id="1">
        <a href="/showbuilder#tracks"><i class='icon-music icon-white'></i><?php echo _("Tracks") ?></a></div>
    <div class="media_type_selector dashboard_sub_nav" data-selection-id="2">
        <a href="/showbuilder#playlists"><i class='icon-list icon-white'></i><?php echo _("Playlists") ?></a></div>
    <div class="media_type_selector dashboard_sub_nav" data-selection-id="3">
        <a href="/showbuilder#smart-blocks"><i class='icon-time icon-white'></i><?php echo _("Smart Blocks") ?></a></div>
    <div class="media_type_selector dashboard_sub_nav" data-selection-id="4">
        <a href="/showbuilder#webstreams"><i class='icon-random icon-white'></i><?php echo _("Webstreams") ?></a></div>
    <hr style="margin-left: 5px; margin-right: 5px">
    <div id="nav">
        <?php echo $this->navigation()->menu(); ?>
    </div>

    <?php
    $partitions = Application_Model_Systemstatus::GetDiskInfo();
    $status = new StdClass;
    $partitions = $partitions;
    $disk = $partitions[0];
    $used = $disk->totalSpace-$disk->totalFreeSpace;
    $total = $disk->totalSpace;
    ?>
    <div id="disk_usage" style="height: 13px; position:fixed; bottom: 5px; left: 10px;">
        <!--<div style="padding-bottom: 2px;">Disk Usage</div>-->
        <div class="disk_usage_progress_bar"></div>
        <div class="disk_usage_percent_in_use"><?php echo sprintf("%01.1fGB of %01.1fGB", $used/pow(2, 30), $total/pow(2, 30)); ?></div>
        <div class="disk_usage_used" style="width:<?php echo sprintf("%01.1f%%", $used/$total*100) ?>;"></div>

        <!--<div style="margin-top: 15px; font-size: 12px;">
            <?php //echo sprintf("%01.1fGB of %01.1fGB", $used/pow(2, 30), $total/pow(2, 30)); ?>
        </div>-->

    </div>

</div>

<?php $hint = Application_Common_UsabilityHints::getUsabilityHint(); ?>
<div class="usability_hint <?php if ($hint == "") { echo "hidden"; } ?>"><?php echo $hint; ?></div>

<div class="wrapper <?php if (isset($this->layout()->parent_page)) echo "wrapper_panel";?>" id="content">
    <?php echo $this->layout()->content ?>
</div>
<?php if (isset($this->layout()->parent_page)) { ?>
    <div id="sub-menu">
        <h3><?php //parent_page is passed in from controller
            echo $this->layout()->parent_page; ?></h3>
        <hr>
        <?php
        $page = $this->navigation()->findOneBy('title', $this->layout()->parent_page);
        echo $this->navigation()->menu()->renderMenu($page);
        ?>
    </div>
<?php } ?>

<script id="tmpl-pl-cues" type="text/template">
<div class="waveform-cues">
  <div class="playlist-time-scale"></div>
  <div class="playlist-tracks"></div>
  <div class="playlist-controls">
	<a class="btn btn-small btn_play"><i class="icon-play icon-white"></i><?php echo _("Play"); ?></a>
    <a class="btn btn-small btn_stop"><i class="icon-stop icon-white"></i><?php echo _("Stop"); ?></a>
	<label class="audio audio_pos">00:00:00.0</label>
  </div>
  <div class="set-cue">
	<label for="editor-cue-in"><?php echo _("Cue In"); ?></label>
    <input type="text" class="audio_start">
    <input type="button" class="btn btn-small set-cue-in" value="<?php echo _("Set Cue In"); ?>">
    <label class="audio editor-cue-in">00:00:00.0</label>
    <span style="display:none" class="cue-in-error"></span>
  </div>
  <div class="set-cue">
    <label for="editor-cue-out"><?php echo _("Cue Out"); ?></label>
    <input type="text" class="audio_end">
    <input type="button" class="btn btn-small set-cue-out" value="<?php echo _("Set Cue Out"); ?>">
    <label class="audio editor-cue-out">00:00:00.0</label>
    <span style="display:none" class="cue-out-error"></span>
  </div>
</div>
</script>

<script id="tmpl-pl-fades" type="text/template">
<div class="waveform-fades">
  <div class="playlist-time-scale"></div>
  <div class="playlist-tracks"></div>
  <div class="playlist-controls left-floated">
    <a class="btn btn-small btn_play"><i class="icon-play icon-white"></i><?php echo _("Play"); ?></a>
    <a class="btn btn-small btn_stop"><i class="icon-stop icon-white"></i><?php echo _("Stop"); ?></a>
	<label class="audio audio_pos">00:00:00.0</label>
  </div>
  <div class="set-fade left-floated">
     <a type="button" class="btn btn-small btn_cursor" data-state="cursor"><?php echo _("Cursor"); ?></a>
     <a type="button" class="btn btn-small btn_fadein" data-state="fadein"><?php echo _("Fade In"); ?></a>
     <a type="button" class="btn btn-small btn_fadeout" data-state="fadeout"><?php echo _("Fade Out"); ?></a>
  </div>
</div>
</script>
</body>
</html>

