<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle() ?>
	<?php echo $this->headScript() ?>
	<?php echo $this->headLink() ?>
	<?php echo isset($this->google_analytics)?$this->google_analytics:"" ?>
</head>
<body>

<div id="Panel">
    <div class="logo"></div>
    <?php echo $this->versionNotify();
            $sss = $this->SourceSwitchStatus();
            $scs = $this->SourceConnectionStatus(); ?>
    <?php echo $this->partial('partialviews/header.phtml', array("user" => $this->loggedInAs(), "is_trial"=>$this->isTrial(), "trial_remain"=> $this->trialRemaining(),
                    "live_dj_switch"=>$sss['live_dj'], "live_dj_connection"=>$scs['live_dj'], "master_dj_switch"=>$sss['master_dj'], "master_dj_connection"=>$scs['master_dj'],
                    "scheduled_play_switch"=>$sss['scheduled_play'])) ?>

<?php 	$partial = array('menu.phtml', 'default');
		$this->navigation()->menu()->setPartial($partial); ?>

<?php echo $this->navigation()->menu() ?>
</div>

<div class="wrapper">
    <!--Set to z-index 254 to make it lower than the top-panel and the ZFDebug info bar, but higher than the side-playlist-->
	<div id="library_content" class="ui-widget ui-widget-content block-shadow alpha-block padded" style="z-index:254"><?php echo $this->layout()->library ?></div>
	<div id="side_playlist" class="ui-widget ui-widget-content block-shadow omega-block padded"><?php echo $this->layout()->spl ?></div>
</div>
</body>
</html>
