<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headScript() ?>
	<?php echo isset($this->google_analytics)?$this->google_analytics:"" ?>
</head>
<body>

    <div id="login-page">
        <?php echo $this->layout()->content ?>
    </div>
    <div class="footer">
      <?php echo sprintf(_("Airtime copyright &copy; Sourcefabric z.ú. All rights reserved.%s"
      ."Maintained and distributed under the GNU GPL v.3 by %sSourcefabric z.ú.%s"),
      "<br>", "<a href='http://www.sourcefabric.org'>" ,"</a>");?> 
    </div>
 
</body>
</html>
