#!/bin/bash

### BEGIN INIT INFO
# Provides:          airtime-playout
# Required-Start:    $local_fs $remote_fs $network $syslog apache2
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage airtime-playout daemon
### END INIT INFO

USERID=pypo
GROUPID=pypo
NAME=Airtime

DAEMON0=/usr/bin/airtime-playout
PIDFILE0=/var/run/airtime-playout.pid

DAEMON1=/usr/bin/airtime-liquidsoap
PIDFILE1=/var/run/airtime-liquidsoap.pid

start () {    
        start-stop-daemon --start --background --quiet --chuid $USERID:$GROUPID --make-pidfile --pidfile $PIDFILE0 --startas $DAEMON0
        start-stop-daemon --start --background --quiet --chuid $USERID:$GROUPID --make-pidfile --pidfile $PIDFILE1 --startas $DAEMON1
}

stop () {
        # Send TERM after 5 seconds, wait at most 30 seconds.
        start-stop-daemon --stop --oknodo --retry TERM/5/0/30 --quiet --pidfile $PIDFILE0
        start-stop-daemon --stop --oknodo --retry TERM/5/0/30 --quiet --pidfile $PIDFILE1
        rm -f $PIDFILE0
        rm -f $PIDFILE1
}


case "${1:-''}" in
  'start')
            # start commands here
            echo -n "Starting $NAME: "
            start
            echo "Done."
        ;;
  'stop')
            # stop commands here
            echo -n "Stopping $NAME: "
            stop
            echo "Done."
        ;;
  'restart')
           # restart commands here
           echo -n "Restarting $NAME: "
           stop
           start
           echo "Done."
        ;;
  'status')
           # status commands here
           /usr/bin/airtime-check-system
        ;;
  *)      # no parameter specified
        echo "Usage: $SELF start|stop|restart|status"
        exit 1
        ;;
esac
