<div id="master-panel">
  <div class="now-playing-block">
    <div class="text-row"><strong>Previous:</strong> <span id='previous'></span> <span id='prev-length'></span></div>
    <div class="now-playing-info song">
      <div class="time-flow"><span class="time-elapsed" id="time-elapsed"></span><span class="time-remaining" id="time-remaining"></span></div>
      <span id='current'></span> <span class="length" id="song-length"></span> </div>
    <div class="progressbar">
      <div class="progress-song" id="progress-bar" style="width:0%;"></div>
    </div>
    <div class="text-row next-song"><strong>Next:</strong> <span id='next'></span> <span id='next-length'></span></div>
  </div>
    <div class="show-block">
      <div class="text-row">&nbsp;</div>
      <div class="now-playing-info show">
        <div class="recording-show" style="display: none;"></div>
        <span id="playlist"></span>
        <span id="show-length" class="show-length"></span>
      </div>
      <div class="progressbar">
        <div class="progress-show" id='progress-show' style="width:0%;"></div>
      </div>
    </div>
  <div class="on-air-block">
    <div class="on-air-info off" id="on-air-info">ON AIR</div>
  </div>
  <div class="time-info-block">
    <ul>
      <li>Station time</li>
      <li class="time" id="time"></li>
      <li class="time-zone"><span id="time-zone"></span></li>
    </ul>
  </div>
  <div class="personal-block">
    <ul>
      <li><a id="about-link" href="#">About</a></li> 
      <li>&nbsp;</li> 
      <li>Signed in:</li>
      <li class="name"><?php echo $this->user ?></li>
      <li><a href="/Login/logout">Logout</a></li>
    </ul>
  </div>
</div>
<div id="jquery_jplayer_1" class="jp-jplayer" style="width:0px; height:0px;"></div>

<div id="about-txt" style="display: none;">
<a href="http://airtime.sourcefabric.org">Airtime</a> <?php echo AIRTIME_VERSION ?>, the open radio software for scheduling and remote station management.<br>
© 2011 <a href="http://www.sourcefabric.org">Sourcefabric</a> o.p.s 2011. Airtime is distributed under the <a href="http://www.gnu.org/licenses/gpl-3.0-standalone.html">GNU GPL v.3</a>
</div>
