<div id='col0' style='float:left; width: 10%; height: 100%;'>
	<div><a href="Schedule" onClick="return popup(this)">Listen</a></div>
</div>
	
<div id='col1' style='float:left; width: 25%; height: 100%;'>
	<div>Show: <span id='show'></span></div>
	<div>Playlist: <span id='playlist'></span></div>
	<div>Host: <span id='host'></span></div>
</div>
	
<div id='col2' style='float:left; width: 30%; height: 100%;'>
	<div>Previous: <span id='previous'></span></div>
	<div>Current: <span id='current'></span></div>
	<div>Upcoming: <span id='next'></span></div>
</div>

<div id='list0' style='float:left; width: 35%; height: 100%;'>
	<div>Start: <span id='start'></span></div>
	<div>End: <span id='end'></span></div>
	<div><span id='progressbar'></span> <span id='songposition'></span> | <span id='songlength'></span></div>
	<div><span id='showprogressbar'></span> <span id='showposition'></span> | <span id='showlength'></span></div>
</div>

<script type="text/javascript">
function popup(mylink){
	if (!window.focus)
		return true;
	var href;
	if (typeof(mylink) == 'string')
	   href=mylink;
	else
	   href=mylink.href;
	window.open(href, "player", 'width=400,height=200,scrollbars=yes');
	return false;
}
</script>

<script type="text/javascript">
$(document).ready(function() {
	//initialize the playlist bar in the included playlist.js
	init("nowplayingbar");
});
</script>
