<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN";
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php echo _("An error has occurred.") ?></title>
  <?php echo $this->headLink(); ?>
</head>
<body>
    <div class="error-content">
        <h2><?php echo $this->escape($this->message)?></h2>
        <p><?php echo _("Looks like the page you were looking for doesn't exist!")?></p>
        <div class="button-bar">
            <a class="toggle-button" href="<?php echo $this->baseUrl('dashboard/help'); ?>"><?php echo _("Help") ?></a>
        </div>
    </div>
</body>
</html>
