<div class="login_box">
    <div class="logobox">&nbsp;</div>
        <h2><?php echo _("Login") ?></h2>
    <div id="login" class="login-content clearfix">
        <?php if(isset($this->demo) && $this->demo == 1){?>
            <p style="font-weight:bold">
            <?php echo sprintf(_("Welcome to the %s demo! You can log in using the username 'admin' and the password 'admin'."), PRODUCT_NAME)?>
            </p>
        <?php }?>
        <p class="light" style='<?php echo $this->error?"color:#902d2d;font-size:11px;padding:2px 4px;background:#c6b4b4;margin-bottom:2px;border:1px solid #c83f3f;":""?>'><?php echo $this->message; ?></p>
        <?php echo $this->form; ?>
    </div>
</div>
