<div class="login_box">
  <div class="logobox">&nbsp;</div>
  <h2><?php echo _("Email Sent!") ?></h2>

  <div id="login" class="login-content clearfix">
    <p class="light"><?php echo _("A password reset link has been sent to your email address. Please check your email and follow the instructions inside to reset your password. If you don't see the email, please check your spam folder!") ?></p>
    <br>
    <dl class="zend-form">
      <dd id="cancel-element">
        <a href="<?php echo($this->baseUrl('login')); ?>">
          <button name="cancel" type="button" class="ui-button ui-widget ui-state-default ui-button-text-only center"><?php echo(_("Back")); ?></button>
        </a>
      </dd>
    </dl>
  </div>
</div>
