#!/bin/bash

virtualenv_bin="/usr/lib/airtime/airtime_virtualenv/bin/"
. ${virtualenv_bin}activate

invokePwd=$PWD

#airtime_silan_path="/usr/lib/airtime/utils/airtime-silan/"
airtime_silan_path="/home/james/src/airtime/utils/airtime-silan/"
airtime_silan_script="airtime-silan.py"

api_client_path="/usr/lib/airtime/"
cd ${airtime_silan_path}

exec 2>&1

export PYTHONPATH=${api_client_path}

# Note the -u when calling python! we need it to get unbuffered binary stdout and stderr
exec python -u ${airtime_silan_path}${airtime_silan_script} --dir "$invokePwd" "$@"

# EOF
