<?php
if (isset($this->obj)) {
    $contents = $this->obj->getContents();
    $count = count($contents);
}
?>

<?php if (isset($this->obj)) : ?>
    <div class="inner_editor_wrapper">
        <input class="obj_id" type="hidden" value="<?php echo $this->obj->getId(); ?>"/>
        <input class="obj_lastMod" type="hidden" value="<?php echo $this->obj->getLastModified('U'); ?>"/>
        <input class='obj_type' type='hidden' value='playlist'/>
        <div class="playlist_title">
            <h3 class="obj_name">
                <a class="playlist_name_display" contenteditable="true"><?php echo $this->escape($this->obj->getName()); ?></a>
            </h3>
            <h4 class="obj_length"><?php echo $this->length; ?></h4>
        </div>
        <div id='sp-success' class='success' style='display:none'></div>

        <dl class="zend_form">
            <dt id="description-label"><label for="description"><?php echo _("Description") ?></label></dt>
            <dd id="description-element">
                <textarea cols="80" rows="24" id="description" name="description"><?php echo $this->escape($this->obj->getDescription()); ?></textarea>
            </dd>
        </dl>

        <div class="btn-toolbar spl-no-margin clearfix left-floated">
            <div class='btn-group pull-right'>
                <button class="btn btn-danger" title='<?php echo _("Empty playlist content") ?>' type="button" id="pl-bl-clear-content"><?php echo _("Clear") ?></button>
            </div>
            <div class='btn-group pull-right'>
                <button class="btn" title='<?php echo _("Shuffle playlist") ?>' type="button" id="playlist_shuffle_button"><?php echo _("Shuffle") ?></button>
            </div>
            <div class='btn-group pull-right'>
                <a href="#" id="spl_crossfade" class="btn crossfade-main-button" style="display:<?php echo $count > 0 ?"block;":"none;"?>">
                    <i class='crossfade-main-icon'></i><span class="ui-button-text"><?php echo _("Playlist crossfade") ?></span>
                </a>
            </div>
        </div>

        <?php //echo $this->form; ?>

        <div id="crossfade_main" class="crossfade-main clearfix" style="display:none;">
            <span class="ui-icon ui-icon-closethick sp-closethick-center"></span>
            <dl id="spl_editor-main" class="inline-list">
                <dt><?php echo _("Fade in: "); ?><span class='spl_cue_hint'>(ss.t)</span></dt>
                <dd><span contenteditable="true" class="spl_text_input spl_main_fade_in">00</span></dd>
                <dd class="edit-error"></dd>
                <dt><?php echo _("Fade out: "); ?><span class='spl_cue_hint'>(ss.t)</span></dt>
                <dd><span contenteditable="true" class="spl_text_input spl_main_fade_out">00</span></dd>
                <dd class="edit-error"></dd>
            </dl>
        </div>
    </div>
    <ul class="spl_sortable">
        <?php  $this->contents = $contents;
            echo $this->render('playlist/update.phtml') ?>
    </ul>
    <div class="btn-toolbar spl-no-margin clearfix">
        <div class='btn-group pull-right'>
            <button class="btn btn-inverse" title='<?php echo _("Save playlist") ?>' type="button" id="save_button"><?php echo _("Save") ?></button>
        </div>
    </div>

<?php else : ?>
    <div><?php echo _("No open playlist") ?></div>
<?php endif; ?>