<?php
if (isset($this->obj)) {
    $contents = $this->obj->getContents();
    $count = count($contents);
}
?>

<?php if (isset($this->obj)) : ?>
    <div class="inner_editor_wrapper">
        <input class="obj_id" type="hidden" value="<?php echo $this->obj->getId(); ?>"/>
        <input class="obj_lastMod" type="hidden" value="<?php echo $this->obj->getLastModified('U'); ?>"/>
        <input class='obj_type' type='hidden' value='block'/>
        <div class="playlist_title">
            <h3 class="obj_name">
                <a class="playlist_name_display" contenteditable="true">
                <?php
                    if (isset($this->unsavedName)) echo $this->unsavedName;
                    else echo $this->escape($this->obj->getName());
                ?>
                </a>
            </h3>
            <h4 class="obj_length"><?php echo $this->length; ?></h4>
        </div>
        <div id='sp-success-saved' class='success' style='display:none'></div>

        <dl class="zend_form">
            <dt id="description-label"><label for="description"><?php echo _("Description") ?></label></dt>
            <dd id="description-element">
                <textarea cols="80" rows="24" id="description" name="description"><?php if (isset($this->unsavedDesc)) echo $this->unsavedDesc; else echo $this->obj->getDescription();?></textarea>
            </dd>
        </dl>

        <?php echo $this->form; ?>
        <div class="btn-toolbar spl-no-margin clearfix left-floated">
            <div class='btn-group pull-right'>
                <button class="btn btn-danger" title='<?php echo _("Empty smart block content") ?>' type="button" id="pl-bl-clear-content"><?php echo _("Clear") ?></button>
            </div>
            <div class='btn-group pull-right'>
                <a href="#" id="spl_crossfade" class="btn crossfade-main-button" style="display:<?php echo ($this->obj->isStatic() && $count > 0) ?"block;":"none;"?>">
                    <i class='crossfade-main-icon'></i><span class="ui-button-text"><?php echo _("Playlist crossfade") ?></span>
                </a>
            </div>
        </div>

        <div id="crossfade_main" class="crossfade-main clearfix" style="display:none;">
            <span class="ui-icon ui-icon-closethick"></span>
            <dl id="spl_editor-main" class="inline-list">
                <dt><?php echo _("Fade in: "); ?><span class='spl_cue_hint'><?php echo _("(ss.t)")?></span></dt>
                <dd><span contenteditable="true" class="spl_text_input spl_main_fade_in">00</span></dd>
                <dd class="edit-error"></dd>
                <dt><?php echo _("Fade out: "); ?><span class='spl_cue_hint'><?php echo _("(ss.t)")?></span></dt>
                <dd><span contenteditable="true" class="spl_text_input spl_main_fade_out">00</span></dd>
                <dd class="edit-error"></dd>
            </dl>
        </div>
    </div>
    <ul class="spl_sortable">
        <?php $this->contents = $contents;
            echo $this->render('playlist/update.phtml') ?>
    </ul>
    <div class="btn-toolbar spl-no-margin clearfix">
        <div class='btn-group pull-right'>
            <button class="btn btn-inverse" title='Save smart block&#39s title, description, and criteria' type="button" id="save_button"><?php echo _("Save") ?></button>
        </div>
    </div>

<?php else : ?>
    <div><?php echo _("No open smart block") ?></div>
<?php endif; ?>
