<button id="spl_new" class="ui-button" role="button" aria-disabled="false">New</button>
<?php if (isset($this->pl)) : ?>
<button id="spl_delete" class="ui-button" role="button" aria-disabled="false">Delete</button>
<a href="#" id="spl_crossfade" class="ui-button ui-button-icon-only ui-widget ui-state-default crossfade-main-button">
    <span class="ui-icon crossfade-main-icon"></span><span class="ui-button-text">Playlist crossfade</span>
</a>
<button id="spl_close" class="ui-button right-floated" role="button" aria-disabled="false">Done Editing</button>
<?php endif; ?>

<?php if (isset($this->pl)) : ?>
<h3 id="spl_name"><?php echo $this->pl->getName(); ?></h3>
<h4 id="spl_length"><?php echo $this->pl->getLength(); ?></h4>

<div id="crossfade_main" class="crossfade-main clearfix" style="display:none;">
  	<span class="ui-icon ui-icon-closethick"></span>
	<dl id="spl_editor-main" class="inline-list">
        <dt>Fade in:</dt>
        <dd id="spl_fade_in_main"><span contenteditable="true" class="spl_text_input">00:00:00</span></dd>
        <dd class="edit-error"></dd>
        <dt>Fade out:</dt>
        <dd id="spl_fade_out_main"><span contenteditable="true" class="spl_text_input">00:00:00</span></dd>
        <dd class="edit-error"></dd>
    </dl>
</div>

<div class="clear"></div>
<div class="" style="clear:both; float:none; width:100%;">
	<ul id="spl_sortable">	
        <?php echo $this->render('playlist/update.phtml') ?>
	</ul>
</div>

<?php else : ?>
<div>No open playlist</div>
<?php endif; ?>
