<?php
    $contents = $this->obj->getMediaContents();
    $count = count($contents);
?>
<a href="#" class="close-round" id="lib_pl_close"></a>
<div class="btn-toolbar spl-no-top-margin clearfix">
    <div class='btn-group pull-right'>
        <button class="btn btn-inverse" title='<?php echo _("Empty playlist content") ?>' type="button" id="pl-bl-clear-content"><?php echo _("Clear") ?></button>
    </div>
    <div class='btn-group pull-right'>
        <button class="btn btn-inverse" title='<?php echo _("Shuffle playlist") ?>' type="button" id="playlist_shuffle_button"><?php echo _("Shuffle") ?></button>
    </div>
</div>

<input id="playlist_id" type="hidden" value="<?php echo $this->obj->getId(); ?>"></input>
<input id="playlist_lastmod" type="hidden" value="<?php echo $this->obj->getUpdatedAt('U'); ?>"></input>
<div class="playlist_title">
    <h3 id="playlist_name">
        <a id="playlist_name_display" contenteditable="true"><?php echo $this->escape($this->obj->getName()); ?></a>
    </h3>
    <h4 id="playlist_length"><?php echo $this->length; ?></h4>
</div>
<div id='sp-success' class='success' style='display:none'></div>

<fieldset class="toggle closed" id="fieldset-metadate_change">
    <legend style="cursor: pointer;">
        <span class="ui-icon ui-icon-triangle-2-n-s"></span>
        <?php echo _("View / edit description"); ?>
    </legend>
    <dl class="zend_form">
        <dt>
            <label for="description">
                <?php echo _("Description"); ?>
            </label>
        </dt>
        <dd>
            <textarea cols="80" rows="24" id="playlist_description" name="description">
                <?php echo $this->escape($this->obj->getDescription()); ?>
            </textarea>
        </dd>
    </dl>
</fieldset>

<div style="clear:both; float:none; width:100%;">
	<ul id="spl_sortable">
	<?php  $this->contents = $contents; 
		echo $this->render('playlist/update.phtml'); 
	?>
	</ul>
</div>
    
<div class="btn-toolbar spl-no-top-margin clearfix">
    <div class='btn-group pull-right'>
        <button class="btn btn-inverse" title='<?php echo _("Save playlist") ?>' type="button" id="save_button"><?php echo _("Save") ?></button>
    </div>
    <div class='btn-group pull-right'>
        <button id="spl_delete" class="btn" role="button" aria-disabled="false"><?php echo _("Delete") ?></button>
    </div>
</div>
