<?php
if (isset($this->obj)) {
    $contents = $this->obj->getContents();
    $count = count($contents);
}
?>
<a href="#" class="close-round" id="lib_pl_close"></a>
<div class="btn-toolbar spl-no-top-margin clearfix">
    <div class="btn-group pull-left">
        <button id="spl_new" class="btn dropdown-toggle" data-toggle="dropdown" aria-disabled="false">
            <?php echo _("New")?> <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li id='lib-new-pl'><a href="#"><?php echo _("New Playlist") ?></a></li>
            <li id='lib-new-bl'><a href="#"><?php echo _("New Smart Block") ?></a></li>
            <li id='lib-new-ws'><a href="#"><?php echo _("New Webstream") ?></a></li>
        </ul>
    </div>
<?php if (isset($this->obj)) : ?>
    <div class='btn-group pull-right'>
        <button class="btn btn-inverse" title='<?php echo _("Empty playlist content") ?>' type="button" id="pl-bl-clear-content"><?php echo _("Clear") ?></button>
    </div>
    <div class='btn-group pull-right'>
        <button class="btn btn-inverse" title='<?php echo _("Shuffle playlist") ?>' type="button" id="playlist_shuffle_button"><?php echo _("Shuffle") ?></button>
    </div>
    <div class='btn-group pull-right'>
        <button class="btn btn-inverse" title='<?php echo _("Save playlist") ?>' type="button" id="save_button"><?php echo _("Save") ?></button>
    </div>
    <div class='btn-group pull-right'>
        <button id="spl_delete" class="btn" role="button" aria-disabled="false"><?php echo _("Delete") ?></button>
    </div>
    <div class='btn-group pull-right'>
        <a href="#" id="spl_crossfade" class="btn crossfade-main-button" style="display:<?php echo $count > 0 ?"block;":"none;"?>">
            <i class='crossfade-main-icon'></i><span class="ui-button-text"><?php echo _("Playlist crossfade") ?></span>
        </a>
    </div>
<?php endif; ?>
</div>

<?php if (isset($this->obj)) : ?>
    <input id="obj_id" type="hidden" value="<?php echo $this->obj->getId(); ?>"></input>
    <input id="obj_lastMod" type="hidden" value="<?php echo $this->obj->getLastModified('U'); ?>"></input>
    <input id='obj_type' type='hidden' value='playlist'></input>
    <div class="playlist_title">
        <h3 id="obj_name">
            <a id="playlist_name_display" contenteditable="true"><?php echo $this->escape($this->obj->getName()); ?></a>
        </h3>
        <h4 id="obj_length"><?php echo $this->length; ?></h4>
    </div>
    <div id='sp-success' class='success' style='display:none'></div>

    <fieldset class="toggle closed" id="fieldset-metadate_change">
        <legend style="cursor: pointer;"><span class="ui-icon ui-icon-triangle-2-n-s"></span><?php echo _("View / edit description"); ?></legend>
        <dl class="zend_form">
            <dt id="description-label"><label for="description"><?php echo _("Description") ?></label></dt>
            <dd id="description-element">
                <textarea cols="80" rows="24" id="description" name="description"><?php echo $this->escape($this->obj->getDescription()); ?></textarea>
            </dd>
        </dl>
    </fieldset>
    
    <?php //echo $this->form; ?>

    <div id="crossfade_main" class="crossfade-main clearfix" style="display:none;">
      	<span class="ui-icon ui-icon-closethick sp-closethick-center"></span>
	    <dl id="spl_editor-main" class="inline-list">
            <dt><?php echo _("Fade in: "); ?><span class='spl_cue_hint'>(ss.t)</span></dt>
            <dd><span contenteditable="true" class="spl_text_input spl_main_fade_in">00</span></dd>
            <dd class="edit-error"></dd>
            <dt><?php echo _("Fade out: "); ?><span class='spl_cue_hint'>(ss.t)</span></dt>
            <dd><span contenteditable="true" class="spl_text_input spl_main_fade_out">00</span></dd>
            <dd class="edit-error"></dd>
        </dl>
    </div>

    <div class="clear"></div>
    <div class="" style="clear:both; float:none; width:100%;">
	    <ul id="spl_sortable">
            <?php  $this->contents = $contents;
                echo $this->render('playlist/update.phtml') ?>
	    </ul>
    </div>

<?php else : ?>
    <div><?php echo _("No open playlist") ?></div>
<?php endif; ?>
