<?php
$items = $this->obj->getContents();
if (count($items)) : ?>
<?php $i = 0; ?>
<?php foreach($items as $item) : ?>
    <li class="ui-state-default" id="spl_<?php echo $item["id"] ?>" unqid="<?php echo $item["gunid"]."_".$item["id"]; ?>">
        <div class="list-item-container"> 
        
            <?php if ($item['exists']):?>
            <div class="big_play" audioFile="<?php echo $item["gunid"].".".pathinfo($item['path'], PATHINFO_EXTENSION); ?>">
                <span class="ui-icon ui-icon-play"></span>
            </div>
            <?php else: ?>
            <div class="big_play ui-state-hover">
                <span class="ui-icon ui-icon-alert"></span>
            </div>   
            <?php endif; ?>   
            
            <div class="text-row top">
                <span class="spl_playlength"><?php echo $item["cliplength"] ?></span>
                <span class="spl_cue ui-state-default"></span>
                <span class="spl_title"><?php echo $item['track_title'] ?></span>
            </div>
            <div class="text-row">
                <span class="spl_artist"><?php echo $item['creator'] ?></span>     
                <span class="spl_offset"><?php echo $item["offset"]?></span>
            </div>
            <?php //create the crossfade icon.
                if ($i < count($items) -1):
            ?>
            <div id="fade_<?php echo $i ?>" class="spl_fade_control ui-state-default"></div>
            <?php endif; ?>
            <span id="remove_<?php echo $item["id"] ?>" class="ui-icon ui-icon-closethick"></span>
        </div>

        <div id="cues_<?php echo $i ?>" class="cue-edit clearfix" style="display: none">
            <?php echo $this->partial('playlist/set-cue.phtml', array(
                'id' => $item["id"],
                'cueIn' => $item['cuein'],
                'cueOut' => $item['cueout'],
                'origLength' => $item['length'])); ?>
        </div>


        <?php //create a fade editor box
              //(fadeout of current position + fade in of next position)
            if($i < count($items) -1):
        ?>
        <div id="crossfade_<?php echo $i ?>-<?php echo $i+1 ?>" class="crossfade clearfix" style="display: none">
            <?php echo $this->partial('playlist/set-fade.phtml', array(
                'item1' => $items[$i]['id'],
                'item2' => $items[$i+1]['id'],
                'fadeOut' => $items[$i]['fadeout'],
                'fadeIn' => $items[$i+1]['fadein'])); ?>
        </div>
        <?php endif; ?>

    </li>
    <?php $i = $i+1; ?>
<?php endforeach; ?>

<?php else : ?>
<li class="spl_empty">Empty playlist</li>
<?php endif; ?>
