<fieldset>
    <dl>
        <dt id="add_show_has_autoplaylist_label">
            <label for="add_show_has_autoplaylist_label">
                <?php echo $this->element->getElement('add_show_has_autoplaylist')->getLabel()?>
            </label>
        </dt>
        <dd>
            <?php echo $this->element->getElement('add_show_has_autoplaylist') ?>
        </dd>

	<div id="add_show_playlist_dropdown">
        <dt id="add_show_autoplaylist_id">
            <label for="add_show_autoplaylist_id" class="required">
                <?php echo $this->element->getElement('add_show_autoplaylist_id')->getLabel()?>
            </label>
        </dt>
        <dd>
            <?php echo $this->element->getElement('add_show_autoplaylist_id') ?>
        </div>
        <div  id="add_show_autoplaylist_repeat">
            <dt id="add_show_autoplaylist_repeat_label">
            <label for="add_show_autoplaylist_repeat_label">
                <?php echo $this->element->getElement('add_show_autoplaylist_repeat')->getLabel()?>
            </label>
            </dt>
            <dd>
            <?php echo $this->element->getElement('add_show_autoplaylist_repeat') ?>
            </dd>
        </div>

    
    </dl>
</fieldset>
