<fieldset>
    <dl>
        <dt id="allow_live_stream_override-label">
            <label class="optional" for="allow_live_stream_override">
            <?php echo $this->element->getElement('allow_live_stream_override')->getLabel() ?>
            </label>
        </dt>
        <dd id="allow_live_stream_override-element">
            <?php echo $this->element->getElement('allow_live_stream_override') ?>
        </dd>
        <dt id="cb_airtime_auth_override-label">
            <label class="optional" for="cb_airtime_auth">
            <?php echo $this->element->getElement('cb_airtime_auth')->getLabel() ?>
            <span class='info-tooltip'>
                        <span>
                            <?php echo $this->element->getElement('cb_airtime_auth')->getDescription() ?>
                        </span>
                    </span>
            </label>
        </dt>
        <dd id="cb_airtime_auth_override-element">
            <?php echo $this->element->getElement('cb_airtime_auth') ?>
        </dd>
        <dt id="cb_custom_auth_override-label">
            <label class="optional" for="cb_custom_auth">
            <?php echo $this->element->getElement('cb_custom_auth')->getLabel() ?>
            <span class='info-tooltip'>
                        <span>
                            <?php echo $this->element->getElement('cb_custom_auth')->getDescription() ?>
                        </span>
                    </span>
            </label>
        </dt>
        <dd id="cb_custom_auth_override-element">
            <?php echo $this->element->getElement('cb_custom_auth') ?>
        </dd>
        
    
        <dt id="custom_username-label" class="block-display">
            <label class="optional" for="custom_username"><?php echo $this->element->getElement('custom_username')->getLabel() ?> :
            </label>
        </dt>
        <dd id="custom_username-element" class="block-display">
            <?php echo $this->element->getElement('custom_username') ?>
            <?php if($this->element->getElement('custom_username')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('custom_username')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="custom_password-label" class="block-display">
            <label class="optional" for="custom_password"><?php echo $this->element->getElement('custom_password')->getLabel() ?> :
            </label>
        </dt>
        <dd id="custom_password-element" class="block-display">
            <?php echo $this->element->getElement('custom_password') ?>
            <?php if($this->element->getElement('custom_password')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('custom_password')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="Connection_URL-label">
            <label for="outputStreamURL">Connection URL: </label>
        </dt>
        <dd id="Connection_URL-element">
            <span id="stream_url"><?php echo $this->connection_url; ?></span>
        </dd>
     </dl>
</fieldset>

