<div class="his-timerange">
    <?php echo $this->element->getElement('his_date_start') ?>
    <?php echo $this->element->getElement('his_time_start') ?>
    <?php echo $this->element->getElement('his_date_end') ?>
    <?php echo $this->element->getElement('his_time_end') ?>
    <div id="his_submit" class="ui-button ui-state-default" title="<?php echo _("Filter History")?>">
        <span class="ui-icon ui-icon-search"></span>
    </div>
</div>