<div id="current-user-container">
<form id="current-user-form" class="edit-user-global" enctype="application/x-www-form-urlencoded">
    <dl class="zend_form">
        <?php echo $this->element->getElement('cu_user_id') ?>
        <dt id="cu-username-label">
            <label><?php echo $this->element->getElement('cu_login')->getLabel() ?>
            </label>
        </dt>
        <dd id="cu-username-element">
            <?php echo $this->element->getElement('cu_login') ?>
            <?php if($this->element->getElement('cu_login')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('cu_login')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="cu-password-label">
            <label><?php echo $this->element->getElement('cu_password')->getLabel() ?>
            </label>
        </dt>
        <dd id="cu-password-element">
            <?php echo $this->element->getElement('cu_password') ?>
            <?php if($this->element->getElement('cu_password')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('cu_password')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="cu-firstname-label">
            <label><?php echo $this->element->getElement('cu_first_name')->getLabel() ?>
            </label>
        </dt>
        <dd id="cu-firstname-element">
            <?php echo $this->element->getElement('cu_first_name') ?>
            <?php if($this->element->getElement('cu_first_name')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('cu_first_name')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="cu-lastname-label">
            <label><?php echo $this->element->getElement('cu_last_name')->getLabel() ?>
            </label>
        </dt>
        <dd id="cu-lastname-element">
            <?php echo $this->element->getElement('cu_last_name') ?>
            <?php if($this->element->getElement('cu_last_name')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('cu_last_name')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="cu-email-label">
            <label><?php echo $this->element->getElement('cu_email')->getLabel() ?>
            </label>
        </dt>
        <dd id="cu-email-element">
            <?php echo $this->element->getElement('cu_email') ?>
            <?php if($this->element->getElement('cu_email')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('cu_email')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="cu-cell_phone-label">
            <label><?php echo $this->element->getElement('cu_cell_phone')->getLabel() ?>
            </label>
        </dt>
        <dd id="cu-cell_phone-element">
            <?php echo $this->element->getElement('cu_cell_phone') ?>
            <?php if($this->element->getElement('cu_cell_phone')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('cu_cell_phone')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="cu-skype-label">
            <label><?php echo $this->element->getElement('cu_skype')->getLabel() ?>
            </label>
        </dt>
        <dd id="cu-skype-element">
            <?php echo $this->element->getElement('cu_skype') ?>
            <?php if($this->element->getElement('cu_skype')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('cu_skype')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="cu-jabber-label">
            <label><?php echo $this->element->getElement('cu_jabber')->getLabel() ?>
            </label>
        </dt>
        <dd id="cu-jabber-element">
            <?php echo $this->element->getElement('cu_jabber') ?>
            <?php if($this->element->getElement('cu_jabber')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('cu_jabber')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <button id="cu_save_user" type="button" class="btn btn-small right-floated">Save</button>
    </dl>
</form>
</div>