<fieldset class="padded">
    <dl class="zend_form">

        <?php echo $this->element->getElement('player_embed_src'); ?>

        <?php echo $this->element->getElement('player_stream_mode'); ?>

        <?php echo $this->element->getElement('player_stream_url'); ?>

        <?php //echo $this->element->getElement('player_display_track_metadata'); ?>

        <?php echo $this->element->getElement('player_preview_label')->renderLabel(); ?>

        <div style="clear:both"></div>
        <?php echo $this->element->getElement('player_embed_src')->getValue(); ?>

    </dl>
</fieldset>