<fieldset class="padded">
    <dl class="zend_form">

        <?php echo $this->element->getElement('player_embed_src'); ?>

        <?php echo $this->element->getElement('player_display_track_metadata'); ?>

        <?php echo $this->element->getElement('player_stream_url'); ?>

        <div style="clear:both"></div>
        <iframe frameborder="0" src="http://localhost/embeddableplayer/embed-code"></iframe>
    </dl>
</fieldset>