<form enctype="application/x-www-form-urlencoded" method="post" action="">
  <dl class="zend_form">
    <dt id="new-password-label">
      <label for="new-password" class="required">
          <?php echo $this->element->getElement('password')->getLabel() ?>
      </label>
    </dt>
    <dd id="new-password-element">
      <?php echo $this->element->getElement('password') ?>
    </dd>
    <dt id="confirm-password-label">
      <label for="confirm-password" class="required">
          <?php echo $this->element->getElement('password_confirm')->getLabel() ?>
      </label>
    </dt>
    <dd id="confirm-password-element">
      <?php echo $this->element->getElement('password_confirm') ?>
    </dd>
  
    <dt id="submit-label">&nbsp;</dt>
    <dd id="submit-element">
      <?php echo $this->element->getElement('submit') ?>
    </dd>
  </dl>
</form>