<form enctype="application/x-www-form-urlencoded" method="post" action="">
  <dl class="zend_form">
    <dt id="username-label">
      <label for="username" class="required">
         <?php echo $this->element->getElement('email')->getLabel() ?>
      </label>
    </dt>
    <dd id="username-element">
      <?php echo $this->element->getElement('email') ?>
    </dd>

 
    <dt id="submit-label">&nbsp;</dt>
    <dd id="submit-element">
      <?php echo $this->element->getElement('submit') ?>
    </dd>
    </dl>
</form>