<dl class='zend_form search-criteria'>
    <dd id='rule_repeat_tracks'>
		<span class='sp_text_font'><?php echo $this->element->getElement('pl_repeat_tracks')->getLabel() ?></span>
        <span class='repeat_tracks_help_icon'></span>
        <?php echo $this->element->getElement('pl_repeat_tracks')?>
    </dd>
    
    <dd id='rule_my_tracks'>
		<span class='sp_text_font'><?php echo $this->element->getElement('pl_my_tracks')->getLabel() ?></span>
        <span class='repeat_tracks_help_icon'></span>
        <?php echo $this->element->getElement('pl_my_tracks')?>
    </dd>
        
	<dd id='rule_limit'>
    	<span class='sp_text_font'><?php echo $this->element->getElement('pl_limit_value')->getLabel() ?></span>
        <?php echo $this->element->getElement('pl_limit_value')?>
        <?php echo $this->element->getElement('pl_limit_options') ?>
        <?php if($this->element->getElement("pl_limit_value")->hasErrors()) : ?>
            <?php foreach($this->element->getElement("pl_limit_value")->getMessages() as $error): ?>
            <span class='errors sp-errors'>
                <?php echo $error; ?>
            </span>
            <?php endforeach; ?>
        <?php endif; ?>
    </dd>
</dl>