<dl class='zend_form search-criteria'>
    <dd id='rule_repeat_tracks'>
		<span class='sp_text_font'><?php echo $this->element->getElement('pl_repeat_tracks')->getLabel() ?></span>
        <span class='repeat_tracks_help_icon'></span>
        <?php echo $this->element->getElement('pl_repeat_tracks')?>
    </dd>
    
    <dd id='rule_my_tracks'>
		<span class='sp_text_font'><?php echo $this->element->getElement('pl_my_tracks')->getLabel() ?></span>
        <span class='repeat_tracks_help_icon'></span>
        <?php echo $this->element->getElement('pl_my_tracks')?>
    </dd>
    
    <dd id='rule_criteria'>
    	<div>
        	<?php echo $this->element->getElement("sp_criteria_field_") ?>
            <a class='btn btn-small pl-same-criteria'>
                <i class='icon-white icon-plus'></i>
            </a>
            <?php echo $this->element->getElement("sp_criteria_modifier_") ?>
            <?php echo $this->element->getElement("sp_criteria_value_") ?>  
            <span class='sp_text_font' id="extra_criteria"><?php echo _(" to "); ?>
            	<?php echo $this->element->getElement('sp_criteria_extra_') ?>
            </span>
            <a class='btn btn-small btn-danger'>
                <i class='icon-white icon-remove'></i>
            </a>
            <a class='btn btn-small pl-diff-criteria'>
                <i class='icon-white icon-plus'></i>
            </a>  
    	</div>
    </dd>
        
	<dd id='rule_limit' class="criteria-element">
    	<span class='sp_text_font'><?php echo $this->element->getElement('pl_limit_value')->getLabel() ?></span>
        <?php echo $this->element->getElement('pl_limit_value')?>
        <?php echo $this->element->getElement('pl_limit_options') ?>
        <?php if($this->element->getElement("pl_limit_value")->hasErrors()) : ?>
            <?php foreach($this->element->getElement("pl_limit_value")->getMessages() as $error): ?>
            <span class='errors sp-errors'>
                <?php echo $error; ?>
            </span>
            <?php endforeach; ?>
        <?php endif; ?>
    </dd>
</dl>