<style type="text/css">

.player-title {
	width: 70px;
	border-style: none
	float: left;
	}

.preview-label {
	line-height: 60px;
	border-style: none
	float: left;
	font-size: 20px;
	color: #fff
	}

</style>
<fieldset class="padded">
    <dl class="zend_form">

        <?php echo $this->element->getElement('player_preview_label')->renderLabel(); ?>

        <div style="clear:both"></div>
        <div class="player-preview">
            <?php echo $this->element->getElement('player_embed_src')->getValue(); ?>
        </div>

        <div id="player_instructions">
            <?php echo _("Customize the player by configuring the options below. When you are done,
            copy the embeddable code below and paste it into your website's HTML.") ?>
        </div>

        <?php echo $this->element->getElement('player_title')->render(); ?>

        <?php echo $this->element->getElement('player_stream_mode')->render(); ?>

        <?php echo $this->element->getElement('player_stream_url'); ?>

        <?php echo $this->element->getElement('player_embed_src')->render(); ?>

        <?php //echo $this->element->getElement('player_display_track_metadata'); ?>
    </dl>
</fieldset>
