<fieldset class="padded">
    <dl class="zend_form">
        <!-- Enable System Email option -->
            
            <dd id="enableSystemEmail-element" class="block-display">
                <label class="required" for="timezone">
                    <?php echo $this->element->getElement('enableSystemEmail') ?>
                    <strong><?php echo $this->element->getElement('enableSystemEmail')->getLabel() ?></strong>
                </label>
                <?php if($this->element->getElement('enableSystemEmail')->hasErrors()) : ?>
                    <ul class='errors'>
                        <?php foreach($this->element->getElement('enableSystemEmail')->getMessages() as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </dd>
            
            <!-- System Email option -->
            <dt id="systemEmail-label" class="block-display">
                <label class="required" for="timezone"><?php echo $this->element->getElement('systemEmail')->getLabel() ?>:
                </label>
            </dt>
            <dd id="systemEmail-element" class="block-display">
                <?php echo $this->element->getElement('systemEmail') ?>
                <?php if($this->element->getElement('systemEmail')->hasErrors()) : ?>
                    <ul class='errors'>
                        <?php foreach($this->element->getElement('systemEmail')->getMessages() as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </dd>
            <br />
            <dd id="configureMailServer-element" class="block-display">
                <label class="required" for="configureMailServer">
                    <?php echo $this->element->getElement('configureMailServer') ?>
                    <strong><?php echo $this->element->getElement('configureMailServer')->getLabel() ?></strong>
                </label>
            </dd>
            
            <dt id="mailServer-label" class="block-display">
                <label class="required" for="mailServer"><?php echo $this->element->getElement('mailServer')->getLabel() ?>
                <span class="info-text-small"><?php echo _("(Required)") ?></span>:
                </label>
                
                <label class="required" for="msRequiresAuth">
                    <?php echo $this->element->getElement('msRequiresAuth') ?>
                    <?php echo $this->element->getElement('msRequiresAuth')->getLabel() ?>
                </label>
            </dt>
            
            <dd id="mailServer-element" class="block-display">
                <?php echo $this->element->getElement('mailServer') ?>
                <?php if($this->element->getElement('mailServer')->hasErrors()) : ?>
                    <ul class='errors'>
                        <?php foreach($this->element->getElement('mailServer')->getMessages() as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?> 
            </dd>
            
            <dt id="port-label" class="block-display">
                <label class="required" for="port"><?php echo $this->element->getElement('port')->getLabel() ?>:
                </label>
            </dt>
            <dd id="port-element" class="block-display">
                <?php echo $this->element->getElement('port') ?>
            </dd>
            
            <dt id="email-label" class="block-display">
                <label class="required" for="email"><?php echo $this->element->getElement('email')->getLabel() ?>
                <span class="info-text-small"><?php echo _("(Required)") ?></span>:
                </label>
            </dt>
            <dd id="email-element" class="block-display">
                <?php echo $this->element->getElement('email') ?>
                <?php if($this->element->getElement('email')->hasErrors()) : ?>
                    <ul class='errors'>
                        <?php foreach($this->element->getElement('email')->getMessages() as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?> 
            </dd>
            
            <dt id="password-label" class="block-display">
                <label class="required" for="password"><?php echo $this->element->getElement('ms_password')->getLabel() ?>
                <span class="info-text-small"><?php echo _("(Required)") ?></span>:
                </label>
            </dt>
            <dd id="password-element" class="block-display">
                <?php echo $this->element->getElement('ms_password') ?>
                <?php if($this->element->getElement('ms_password')->hasErrors()) : ?>
                    <ul class='errors'>
                        <?php foreach($this->element->getElement('ms_password')->getMessages() as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </dd>
            
            
    </dl>
</fieldset>
