<fieldset class="padded stream-setting-global" style="margin-top: 15px">
    <legend><?php echo _("Input Stream Settings") ?></legend>
    <dl class="zend_form">
        <dt id="auto_transition-label">
            <label class="optional" for="auto_transition"><?php echo $this->element->getElement('auto_transition')->getLabel() ?> :
                <span class="icecast_metadata_help_icon" id="auto_transition_help">
                </span>
            </label>
        </dt>
        <dd id="auto_transition-element">
            <?php echo $this->element->getElement('auto_transition') ?>
            <?php if($this->element->getElement('auto_transition')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('auto_transition')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="auto_switch-label">
            <label class="optional" for="auto_transition"><?php echo $this->element->getElement('auto_switch')->getLabel() ?> :
                <span class="icecast_metadata_help_icon" id="auto_switch_help">
                </span>
            </label>
        </dt>
        <dd id="auto_switch-element">
            <?php echo $this->element->getElement('auto_switch') ?>
            <?php if($this->element->getElement('auto_switch')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('auto_switch')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="transition_fade-label">
            <label class="optional" for="transition_fade"><?php echo $this->element->getElement('transition_fade')->getLabel() ?> :
            </label>
        </dt>
        <dd id="transition_fade-element">
            <?php echo $this->element->getElement('transition_fade') ?>
            <?php if($this->element->getElement('transition_fade')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('transition_fade')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="master_username-label">
            <label class="optional" for="master_username"><?php echo $this->element->getElement('master_username')->getLabel() ?> :
            <span class='master_username_help_icon'></span>
            </label>
        </dt>
        <dd id="master_username-element">
            <?php echo $this->element->getElement('master_username') ?>
            <?php if($this->element->getElement('master_username')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('master_username')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="master_password-label">
            <label class="optional" for="master_password"><?php echo $this->element->getElement('master_password')->getLabel() ?> :
            </label>
        </dt>
        <dd id="master_password-element">
            <?php echo $this->element->getElement('master_password') ?>
            <?php if($this->element->getElement('master_password')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('master_password')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
            <dt id="master_harbor_input_port-label">
                <label class="optional" for="master_harbor_input_port"><?php echo $this->element->getElement('master_harbor_input_port')->getLabel() ?> :
                </label>
            </dt>
            <dd id="master_harbor_input_port-element">
                <?php echo $this->element->getElement('master_harbor_input_port') ?>
                <?php if($this->element->getElement('master_harbor_input_port')->hasErrors()) : ?>
                    <ul class='errors'>
                        <?php foreach($this->element->getElement('master_harbor_input_port')->getMessages() as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?> 
            </dd>
            <dt id="master_harbor_input_mount_point-label">
                <label class="optional" for="master_harbor_input_mount_point"><?php echo $this->element->getElement('master_harbor_input_mount_point')->getLabel() ?> :
                </label>
            </dt>
            <dd id="master_harbor_input_mount_point-element">
                <?php echo $this->element->getElement('master_harbor_input_mount_point') ?>
                <?php if($this->element->getElement('master_harbor_input_mount_point')->hasErrors()) : ?>
                    <ul class='errors'>
                        <?php foreach($this->element->getElement('master_harbor_input_mount_point')->getMessages() as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?> 
            </dd>
        <dt id="master_dj_connection_url-label">
            <label class="optional" for="master_dj_connection_url" style="white-space: nowrap">
                <?php echo _("Master Source Connection URL:")?>
            </label>
        </dt>
        <dd id="master_dj_connection_url-element">
            <span id="stream_url"><?php echo $this->element->getElement('master_dj_connection_url')->setValue($this->master_dj_connection_url) ?></span>
            <?php if(!$this->isDemo){?>
                <a href=# id="connection_url_override" style="font-size: 12px;"><?php echo _("Override") ?></a>&nbsp;&nbsp;
                <span class="override_help_icon">
                </span><br>
            <?php } ?>
            <div id="master_dj_connection_url_actions" style="display:none">
                <a href=# id="ok" style="font-size: 12px;"><?php echo _("OK") ?></a> <a href=# id="reset" style="font-size: 12px;"><?php echo _("RESET"); ?></a>
            </div>
        </dd>
            <dt id="dj_harbor_input_port-label">
                <label class="optional" for="dj_harbor_input_port"><?php echo $this->element->getElement('dj_harbor_input_port')->getLabel() ?> :
                </label>
            </dt>
            <dd id="dj_harbor_input_port-element">
                <?php echo $this->element->getElement('dj_harbor_input_port') ?>
                <?php if($this->element->getElement('dj_harbor_input_port')->hasErrors()) : ?>
                    <ul class='errors'>
                        <?php foreach($this->element->getElement('dj_harbor_input_port')->getMessages() as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?> 
            </dd>
            <dt id="dj_harbor_input_mount_point-label">
                <label class="optional" for="dj_harbor_input_mount_point"><?php echo $this->element->getElement('dj_harbor_input_mount_point')->getLabel() ?> :
                </label>
            </dt>
            <dd id="dj_harbor_input_mount_point-element">
                <?php echo $this->element->getElement('dj_harbor_input_mount_point') ?>
                <?php if($this->element->getElement('dj_harbor_input_mount_point')->hasErrors()) : ?>
                    <ul class='errors'>
                        <?php foreach($this->element->getElement('dj_harbor_input_mount_point')->getMessages() as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?> 
            </dd>
        <dt id="live_dj_connection_url-label">
            <label class="optional" for="live_dj_connection_url" style="white-space: nowrap">
                <?php echo _("Show Source Connection URL:")?>
            </label>
        </dt>
        <dd id="live_dj_connection_url-element">
            <span id="stream_url"><?php echo $this->element->getElement('live_dj_connection_url')->setValue($this->live_dj_connection_url) ?></span>
            <?php if( !$this->isDemo ){?>   
                <a href=# id="connection_url_override" style="font-size: 12px;"><?php echo _("Override") ?></a>&nbsp;&nbsp;
                <span class="override_help_icon">
                </span><br>
            <?php } ?>
            <div id="live_dj_connection_url_actions" style="display:none">
                <a href=# id="ok" style="font-size: 12px;"><?php echo _("OK") ?></a> <a href=# id="reset" style="font-size: 12px;"><?php echo _("RESET"); ?></a>
            </div>
        </dd>
    </dl>
</fieldset>
