<fieldset class="padded">
    <dl class="zend_form">

        <?php echo $this->element->getElement('stationName')->render() ?>

        <?php echo $this->element->getElement('stationDescription')->render() ?>

        <?php echo $this->element->getElement('stationLogo')->render() ?>

        <div id="Logo-img-container"><img id="logo-img" onload='resizeImg(this, 450, 450);' src="data:image/png;base64,<?php echo $this->element->getView()->logoImg ?>" /></div>

        <?php echo $this->element->getElement('locale')->render() ?>

        <?php echo $this->element->getElement('timezone')->render() ?>

        <?php echo $this->element->getElement('weekStartDay')->render() ?>

        <?php echo $this->element->getElement('stationDefaultFadeIn')->render() ?>

        <?php echo $this->element->getElement('stationDefaultFadeOut')->render() ?>

        <?php echo $this->element->getElement('stationDefaultCrossfadeDuration')->render() ?>

        <?php echo $this->element->getElement('thirdPartyApi')->render() ?>

    </dl>
</fieldset>
