<form method="<?php echo $this->element->getMethod() ?>" enctype="multipart/form-data">

    <?php echo $this->element->getSubform('preferences_general') ?>
    
    <?php if (!$this->isSaas) { ?>
        <h3 class="collapsible-header" id="email-server-heading"><span class="arrow-icon"></span>Email / Mail Server Settings</h3>
        <div class="collapsible-content" id="email-server-settings" style="display: none;">
            <?php echo $this->element->getSubform('preferences_email_server') ?>
        </div>
    <?php } ?>

    <h3 class="collapsible-header" id="soundcloud-heading"><span class="arrow-icon"></span>SoundCloud Settings</h3>

    <div class="collapsible-content" id="soundcloud-settings" style="display: none;">
        <?php echo $this->element->getSubform('preferences_soundcloud') ?>
    </div>

    <?php echo $this->element->getElement('pref_save') ?>

</form>
