<fieldset class="padded">
    <dl class="zend_form">
        <?php
            $soundcloudService = new SoundcloudService();
            if ($soundcloudService->hasAccessToken()) {
                echo $this->element->getElement('SoundCloudDisconnect')->render();
            } else {
                echo $this->element->getElement('SoundCloudConnect')->render();
            }
        ?>

        <?php echo $this->element->getElement('SoundCloudLicense')->render() ?>

        <?php echo $this->element->getElement('SoundCloudSharing')->render() ?>
    </dl>
</fieldset>
