<fieldset class="padded">
    <dl class="zend_form">
    	<?php if($this->element->getView()->supportFeedback === '0'){?>
    	<div class="info-text"><p>Be more awesome by selecting "Support feedback" below. You will be helping Airtim improve!</p></div>
    	<?php }?>
    	<dd id="SupportFeedback-element">
            <label class="optional" for="SupportFeedback">
                <?php echo $this->element->getElement('SupportFeedback') ?>
                <strong><?php echo $this->element->getElement('SupportFeedback')->getLabel() ?></strong>
            </label>
            <?php if($this->element->getElement('SupportFeedback')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('SupportFeedback')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
            <div class="info-text">By checking this box, I agree to Sourcefabric's privacy policy.</div>
        </dd>
		<dd id="publicize-element">
			<label class="optional" for="Publicise">
                <?php echo $this->element->getElement('Publicise') ?>
                <strong><?php echo $this->element->getElement('Publicise')->getLabel() ?></strong>
            </label>
            <?php if($this->element->getElement('Publicise')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Publicise')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
		</dd>
		<div class="info-text" style="clear: both;padding: 4px 0 4px 15px;"><p> Note: In order to publicise your station, "Send support feedback" must be enabled</p></div>
        <dt id="Phone-label" class="block-display">
            <label class="optional" for="Phone"><?php echo $this->element->getElement('Phone')->getLabel() ?></label>
        </dt>
        <dd id="Phone-element" class="block-display">
            <?php echo $this->element->getElement('Phone') ?>
            <?php if($this->element->getElement('Phone')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Phone')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="Email-label" class="block-display">
            <label class="optional" for="Email"><?php echo $this->element->getElement('Email')->getLabel() ?></label>
        </dt>
        <dd id="Email-element" class="block-display">
            <?php echo $this->element->getElement('Email') ?>
            <?php if($this->element->getElement('Email')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Email')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="StationWebSite-label" class="block-display">
            <label class="optional" for="StationWebSite"><?php echo $this->element->getElement('StationWebSite')->getLabel() ?></label>
        </dt>
        <dd id="StationWebSite-element" class="block-display clearfix">
            <?php echo $this->element->getElement('StationWebSite') ?>
            <?php if($this->element->getElement('StationWebSite')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('StationWebSite')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Country-label" class="block-display">
            <label class="optional" for="Country"><?php echo $this->element->getElement('Country')->getLabel() ?></label>
        </dt>
        <dd id="Country-element" class="block-display clearfix">
            <?php echo $this->element->getElement('Country') ?>
            <?php if($this->element->getElement('Country')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Country')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="City-label" class="block-display">
            <label class="optional" for="City"><?php echo $this->element->getElement('City')->getLabel() ?></label>
        </dt>
        <dd id="City-element" class="block-display clearfix">
            <?php echo $this->element->getElement('City') ?>
            <?php if($this->element->getElement('City')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('City')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Description-label" class="block-display">
            <label class="optional" for="Description"><?php echo $this->element->getElement('Description')->getLabel() ?></label>
        </dt>
        <dd id="Description-element" class="block-display clearfix">
            <?php echo $this->element->getElement('Description') ?>
            <?php if($this->element->getElement('Description')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Description')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Logo-label" class="block-display">
            <label class="optional" for="Description"><?php echo $this->element->getElement('Logo')->getLabel() ?></label>
        </dt>
        <?php if($this->element->getView()->logoImg){?>
        <div id="Logo-img-container"><img id="logo-img" onload='resizeImg(this);' src="data:image/png;base64,<?php echo $this->element->getView()->logoImg ?>" /></div>
        <?php }?>
        <dd id="Logo-element" class="block-display clearfix">
            <?php echo $this->element->getElement('Logo') ?>
            <div class="info-text"><p>Min. size: 200x200 Max. size: 600x600</p></div>
            <?php if($this->element->getElement('Logo')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Logo')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        
    </dl>
    <h3 class="collapsible-header">
		<span class="arrow-icon"></span>Show me what I am sending
	</h3>

	<div class="collapsible-content" id="show_what_sending" style="display: none;">
		<fieldset class="display_field">
			<dl>
				<?php echo $this->element->getElement('SendInfo') ?>
			</dl>
		</fieldset>
	</div>
</fieldset>
