<fieldset class="padded">
    <dl class="zend_form">
        <dt id="stationName-label" class="block-display">
            <label class="required" for="stationName"><?php echo $this->element->getElement('stationName')->getLabel() ?>:
            </label>
        </dt>
        <dd id="stationName-element" class="block-display">
            <?php echo $this->element->getElement('stationName') ?>
            <?php if($this->element->getElement('stationName')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('stationName')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="stationDefaultFade-label" class="block-display">
            <label class="optional" for="stationDefaultFade"><?php echo $this->element->getElement('stationDefaultFade')->getLabel() ?></label>
        </dt>
        <dd id="stationDefaultFade-element" class="block-display">
            <?php echo $this->element->getElement('stationDefaultFade') ?>
            <?php if($this->element->getElement('stationDefaultFade')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('stationDefaultFade')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="thirdPartyApi-label" class="block-display">
            <label class="optional"><?php echo $this->element->getElement('thirdPartyApi')->getLabel() ?></label>
        </dt>
        <dd id="thirdPartyApi-element" class="block-display  radio-inline-list">
            <?php $i=0;
                  $value = $this->element->getElement('thirdPartyApi')->getValue();
            ?>
            <?php foreach ($this->element->getElement('thirdPartyApi')->getMultiOptions() as $radio) : ?>
                <label for="thirdPartyApi-<?php echo $i ?>">
                    <input type="radio" value="<?php echo $i ?>" id="thirdPartyApi-<?php echo $i ?>" name="thirdPartyApi" <?php if($i == $value){echo 'checked="checked"';}?>>
                        <?php echo $radio ?>
                    </input>
                </label>
            <?php $i = $i + 1; ?>
            <?php endforeach; ?>
            <?php if($this->element->getElement('thirdPartyApi')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('thirdPartyApi')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="timezone-label" class="block-display">
            <label class="required" for="timezone"><?php echo $this->element->getElement('timezone')->getLabel() ?>
                <span class="info-text-small">(Required)</span> :
            </label>
        </dt>
        <dd id="timezone-element" class="block-display">
            <?php echo $this->element->getElement('timezone') ?>
            <?php if($this->element->getElement('timezone')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('timezone')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>

        <!-- Week Start Day option -->
        <dt id="weekStartDay-label" class="block-display">
            <label class="required" for="timezone"><?php echo $this->element->getElement('weekStartDay')->getLabel() ?>:
            </label>
        </dt>
        <dd id="weekStartDay-element" class="block-display">
        	<?php $i=0;
                  $value = $this->element->getElement('weekStartDay')->getValue();
            ?>
            <select id="weekStartDay" name="weekStartDay">
            <?php foreach ($this->element->getElement('weekStartDay')->getMultiOptions() as $option) : ?>
                <option value="<?php echo $i ?>" <?php if($i == $value){echo 'selected="selected"';}?> >
                        <?php echo $option ?>
                </option>
                <?php $i = $i + 1; ?>
            <?php endforeach; ?>
            </select>

            <?php if($this->element->getElement('weekStartDay')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('weekStartDay')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
    </dl>
</fieldset>
