<form method="<?php echo $this->element->getMethod() ?>" action="<?php echo $this->element->getAction() ?>" enctype="application/x-www-form-urlencoded">

    <?php echo $this->element->getSubform('preferences_general') ?>

    <h3 class="collapsible-header"><span class="arrow-icon"></span>SoundCloud Settings</h3>
    <div class="collapsible-content" id="soundcloud-settings" style="display: none;">
        <?php echo $this->element->getSubform('preferences_soundcloud') ?>
    </div>
    
    <h3 class="collapsible-header"><span class="arrow-icon"></span>Support Settings</h3>
    <div class="collapsible-content" id="support-settings" style="display: none;">
        <?php echo $this->element->getSubform('preferences_support') ?>
    </div>

    <div class="button-bar bottom" id="submit-element">
        <?php echo $this->element->getElement('submit') ?>
    </div>

</form>
