<fieldset class="padded">
    <dl class="zend_form">

        <div class="warning" style="margin-bottom: 10px;">
            <p class="warning-label">
                <?php echo _("<strong>Warning:</strong> These functions will have <strong>permanent and lasting effects</strong> on your Airtime station. Think carefully before using them!") ?>
            </p>
        </div>

        <?php echo $this->element->getElement('clear_library')->render() ?>

    </dl>
</fieldset>
