<form method="<?php echo $this->element->getMethod() ?>" action="<?php echo $this->element->getAction() ?>" enctype="multipart/form-data">

    <?php echo $this->element->getSubform('preferences_general') ?>


    <h3 class="collapsible-header" id="soundcloud-heading"><span class="arrow-icon"></span>SoundCloud Settings</h3>

    <div class="collapsible-content" id="soundcloud-settings" style="display: none;">
        <?php echo $this->element->getSubform('preferences_soundcloud') ?>
    </div>

    <div class="button-bar bottom" id="submit-element">
        <?php echo $this->element->getElement('submit') ?>
    </div>

</form>
