<fieldset class="padded">
    <dl class="zend_form">
        <dd id="auto_enable_live_stream-element" class="block-display" style=" margin:6px 0 10px 0">
            <label class="optional" for="auto_enable_live_stream">
                <?php echo $this->element->getElement('auto_enable_live_stream') ?>
                <strong><?php echo $this->element->getElement('auto_enable_live_stream')->getLabel() ?></strong>
            </label>
            <?php if($this->element->getElement('auto_enable_live_stream')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('auto_enable_live_stream')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="master_username-label" class="block-display">
            <label class="optional" for="master_username"><?php echo $this->element->getElement('master_username')->getLabel() ?>
                <span class="info-text-small">(Required)</span> :
            </label>
        </dt>
        <dd id="master_username-element" class="block-display">
            <?php echo $this->element->getElement('master_username') ?>
            <?php if($this->element->getElement('master_username')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('master_username')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dt id="master_password-label" class="block-display">
            <label class="optional" for="master_password"><?php echo $this->element->getElement('master_password')->getLabel() ?>
                <span class="info-text-small">(Required)</span> :
            </label>
        </dt>
        <dd id="master_password-element" class="block-display">
            <?php echo $this->element->getElement('master_password') ?>
            <?php if($this->element->getElement('master_password')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('master_password')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
    </dl>
</fieldset>
