<div class="dialogPopup register-dialog" title="Register Airtime">
	<div class="info-text">
		<p>Help Airtime improve by letting us know you are using it. This info
			will be collected once per month and is anonymous unless you chose to
			advertise your station on sourcefabric.org</p>

	</div>
<form method="<?php echo $this->element->getMethod() ?>" action="<?php echo $this->element->getAction() ?>" enctype="application/x-www-form-urlencoded">

		<dl class="zend_form">
			<dd id="publicize-element">
				<label class="optional" for="Publicise">
	                <?php echo $this->element->getElement('Publicise') ?>
	                <strong><?php echo $this->element->getElement('Publicise')->getLabel() ?></strong>
	            </label>
	            <?php if($this->element->getElement('Publicise')->hasErrors()) : ?>
	                <ul class='errors'>
	                    <?php foreach($this->element->getElement('Publicise')->getMessages() as $error): ?>
	                        <li><?php echo $error; ?></li>
	                    <?php endforeach; ?>
	                </ul>
	            <?php endif; ?> 
			</dd>
		</dl>

		<fieldset>
			<dl class="zend_form">
				<dt id="StationName-label" class="block-display">
		            <label class="required" for="StationName"><?php echo $this->element->getElement('StationName')->getLabel() ?></label>
		        </dt>
		    	<dd id="StationName-element" class="block-display clearfix">
		            <?php echo $this->element->getElement('StationName') ?>
		            <?php if($this->element->getElement('StationName')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('StationName')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?>
		        </dd>
		        <dt id="StationWebSite-label" class="block-display">
		            <label class="required" for="StationWebSite"><?php echo $this->element->getElement('StationWebSite')->getLabel() ?></label>
		        </dt>
		        <dd id="StationWebSite-element" class="block-display clearfix">
		            <?php echo $this->element->getElement('StationWebSite') ?>
		            <?php if($this->element->getElement('StationWebSite')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('StationWebSite')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?>
		        </dd>
		        <dt id="Phone-label" class="block-display">
		            <label class="required" for="Phone"><?php echo $this->element->getElement('Phone')->getLabel() ?></label>
		        </dt>
		        <dd id="Phone-element" class="block-display">
		            <?php echo $this->element->getElement('Phone') ?>
		            <?php if($this->element->getElement('Phone')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('Phone')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?> 
		        </dd>
		        <dt id="Email-label" class="block-display">
		            <label class="required" for="Email"><?php echo $this->element->getElement('Email')->getLabel() ?></label>
		        </dt>
		        <dd id="Email-element" class="block-display">
		            <?php echo $this->element->getElement('Email') ?>
		            <?php if($this->element->getElement('Email')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('Email')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?> 
		        </dd>
			</dl>
		</fieldset>
	</form>

	<h3 class="collapsible-header">
		<span class="arrow-icon"></span>Show me what I am sending
	</h3>

	<div class="collapsible-content" id="show_what_sending" style="display: block;">
		<fieldset class="display_field">
			<dl>
				<?php echo $this->element->getElement('SendInfo') ?>
				<dt>Airtime version:</dt>
				<dd>1.9.0</dd>

				<dt>Unique ID:</dt>
				<dd>AT19236520FR00673</dd>

				<dt>Station name:</dt>
				<dd>BBC Radio 1</dd>
			</dl>
		</fieldset>
	</div>
</div>