<div class="dialogPopup register-dialog" title="Register Airtime">
	<form id="register-form" method="<?php echo $this->element->getMethod() ?>" action="<?php echo $this->element->getAction() ?>" enctype="multipart/form-data">
    		<fieldset>
		    <dl class="zend_form">
		    	<dt class="block-display info-text">
            		Help Airtime improve by letting us know you are using it. This info
            			will be collected regularly in order to improve your user experience.
                </dt>
		    	<dd id="SupportFeedback-element" class="block-display">
		            <label class="optional" for="SupportFeedback">
		                <?php echo $this->element->getElement('SupportFeedback') ?>
		                <strong><?php echo $this->element->getElement('SupportFeedback')->getLabel() ?></strong>
		            </label>
		            <?php if($this->element->getElement('SupportFeedback')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('SupportFeedback')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?>
		        </dd>
                <dt class="block-display info-text">
            		Click the box below to advertise your station on <a id="link_to_whos_using" href="">Sourcefabric.org</a>. In order to promote your station, "Send support feedback" must be enabled. This data will be collected in addition to the support feedback.
                </dt>
				<dd id="publicize-element" class="block-display">
					<label class="optional" for="Publicise">
		                <?php echo $this->element->getElement('Publicise') ?>
		                <strong><?php echo $this->element->getElement('Publicise')->getLabel() ?></strong>
		            </label>
		            <?php if($this->element->getElement('Publicise')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('Publicise')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?> 
				</dd>
			</dl>
			<dl id="public-info" style="display:none;">
				<dt id="stnName-label">
		            <label class="optional" for="stnName"><?php echo $this->element->getElement('stnName')->getLabel() ?></label>
		        </dt>
		        <dd id="stnName-element">
		            <?php echo $this->element->getElement('stnName') ?>
		            <?php if($this->element->getElement('stnName')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('stnName')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?> 
		        </dd>
		        <dt id="Phone-label">
		            <label class="optional" for="Phone"><?php echo $this->element->getElement('Phone')->getLabel() ?></label>
		        </dt>
		        <dd id="Phone-element">
		            <?php echo $this->element->getElement('Phone') ?>
		            <?php if($this->element->getElement('Phone')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('Phone')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?> 
		        </dd>
		        <dt id="Email-label">
		            <label class="optional" for="Email"><?php echo $this->element->getElement('Email')->getLabel() ?></label>
		        </dt>
		        <dd id="Email-element">
		            <?php echo $this->element->getElement('Email') ?>
		            <?php if($this->element->getElement('Email')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('Email')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?> 
		        </dd>
		        <dt id="StationWebSite-label">
		            <label class="optional" for="StationWebSite"><?php echo $this->element->getElement('StationWebSite')->getLabel() ?></label>
		        </dt>
		        <dd id="StationWebSite-element">
		            <?php echo $this->element->getElement('StationWebSite') ?>
		            <?php if($this->element->getElement('StationWebSite')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('StationWebSite')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?>
		        </dd>
		        <dt id="Country-label">
		            <label class="optional" for="Country"><?php echo $this->element->getElement('Country')->getLabel() ?></label>
		        </dt>
		        <dd id="Country-element">
		            <?php echo $this->element->getElement('Country') ?>
		            <?php if($this->element->getElement('Country')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('Country')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?>
		        </dd>
		        <dt id="City-label">
		            <label class="optional" for="City"><?php echo $this->element->getElement('City')->getLabel() ?></label>
		        </dt>
		        <dd id="City-element">
		            <?php echo $this->element->getElement('City') ?>
		            <?php if($this->element->getElement('City')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('City')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?>
		        </dd>
		        <dt id="Description-label">
		            <label class="optional" for="Description"><?php echo $this->element->getElement('Description')->getLabel() ?></label>
		        </dt>
		        <dd id="Description-element">
		            <?php echo $this->element->getElement('Description') ?>
		            <?php if($this->element->getElement('Description')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('Description')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?>
		        </dd>
		        <dt id="Logo-label" class="block-display">
		            <label class="optional" for="Description"><?php echo $this->element->getElement('Logo')->getLabel() ?></label>
		        </dt>

		        <dd id="Logo-element">
                	<?php if($this->element->getView()->logoImg){?>
		        	<div id="Logo-img-container"><img id="logo-img" onload='resizeImg(this);' src="data:image/png;base64,<?php echo $this->element->getView()->logoImg ?>" /></div>
		        	<?php }?>
                    
		            <?php echo $this->element->getElement('Logo') ?>
		            <p class="info-text">Min. size: 200x200 Max. size: 600x600</p>
		            <?php if($this->element->getElement('Logo')->hasErrors()) : ?>
		                <ul class='errors'>
		                    <?php foreach($this->element->getElement('Logo')->getMessages() as $error): ?>
		                        <li><?php echo $error; ?></li>
		                    <?php endforeach; ?>
		                </ul>
		            <?php endif; ?>
		        </dd>
		    </dl>
            </fieldset>
		
			<div id="show_what_sending" style="display: block;">
				<fieldset class="display_field toggle closed">
				<legend style="cursor: pointer;"><span class="ui-icon ui-icon-triangle-2-n-s"></span>Show me what I am sending </legend>
					<dl>
						<?php echo $this->element->getElement('SendInfo') ?>
					</dl>
				</fieldset>
			</div>
			<div>
			    <br>
				<label class="optional" for="Privacy">
	                <?php echo $this->element->getElement('Privacy') ?>
	                <?php echo $this->element->getElement('Privacy')->getLabel() ?>
	            </label>
			</div>
	</form>
</div>