<div id="lang-timezone-popup" class="dialogPopup register-dialog" title="<?php echo _("Setup Station Language and Timezone") ?>" style="display: none;">
    <form id="lang-timezone-form" method="post" action="/setup/setup-language-timezone">
        <fieldset>
            <dl class="zend_form">
                <?php echo $this->element->getElement('csrf') ?>

                <?php echo $this->element->getElement('setup_language')->render(); ?>

                <?php echo $this->element->getElement('setup_timezone')->render(); ?>

                <br>
                You can set these settings later under Preferences and your user settings.
            </dl>
        </fieldset>
    </form>
</div>
