<?php echo $this->element->getElement('sb_date_start'); ?>
<?php echo $this->element->getElement('sb_time_start'); ?>
<?php echo $this->element->getElement('sb_date_end'); ?>
<?php echo $this->element->getElement('sb_time_end'); ?>

<a id="sb_submit" class="btn btn-small" href="#" title="Display shows in the specified date and time range">
    <i class="icon-white icon-search"></i><?php echo " "._("Find Shows") ?>
</a>
