<form id="smart-playlist-form" method="post" action="">
<fieldset class='toggle closed' id='smart_playlist_options' style='overflow-x:auto; width:781px'>
<legend style='cursor: pointer;'><span class='ui-icon ui-icon-triangle-2-n-s'></span>Smart Playlist Options</legend>
    <dl class='zend_form'>
        <dd id='sp_type-element' class='radio-inline-list'>
        <label for='sp_type'>            
            <?php echo $this->element->getElement('sp_type')->getLabel() ?>
            <?php $i=0;
                  $value = $this->element->getElement('sp_type')->getValue();
                  foreach ($this->element->getElement('sp_type')->getMultiOptions() as $radio) : ?>
                      <input type="radio" value="<?php echo $i ?>" id="sp_type-<?php echo $i ?>" name="sp_type" <?php if($i == $value){echo 'checked="checked"';}?> >
                          <?php echo $radio ?>
                      </input>
            <?php $i = $i + 1; ?>
            <?php endforeach; ?>
        </label>
        </dd>
        
        <dd id='sp_criteria-element'>
        <?php for ($i = 0; $i < $this->criteriasLength; $i++) {?>
            <div <?php if (($i > 0) && ($this->element->getElement('sp_criteria_field_'.$i)->getAttrib('disabled') == 'disabled')) {
                           echo 'style=display:none';
                       } ?>>
        
                <?php echo $this->element->getElement('sp_criteria_field_'.$i) ?>
                <?php echo $this->element->getElement('sp_criteria_modifier_'.$i) ?>
                <?php echo $this->element->getElement('sp_criteria_value_'.$i) ?><span id="extra_criteria" <?php echo $this->element->getElement('sp_criteria_extra_'.$i)->getAttrib("disabled") == "disabled"?'style="display:none;"':""?>> to <?php echo $this->element->getElement('sp_criteria_extra_'.$i) ?></span> 
                <?php if ($i != 0) { ?>
                    <a href='#' id='criteria_remove_<?php echo $i ?>'>Remove&nbsp;</a>
                <?php } ?>
                <br />
            </div>
            
        <?php } ?>
        
        </dd>
        
        <dd id='sp_limit-element'>
            <label>
                <?php echo $this->element->getElement('sp_limit_value')->getLabel() ?>
                <?php echo $this->element->getElement('sp_limit_value')?>
                <?php echo $this->element->getElement('sp_limit_options') ?>
                <br />
            </label>
        </dd>
        
        <dd id='sp_save'>
            <?php echo $this->element->getElement('save_button') ?>
        </dd>
        
</dl>
</fieldset>
</form>