<form id="smart-playlist-form" method="post" action="">
<fieldset class='toggle closed' id='smart_playlist_options'>
<legend style='cursor: pointer;'><span class='ui-icon ui-icon-triangle-2-n-s'></span>Smart Playlist Options</legend>
    <dl class='zend_form'>
        <dd id='sp_type-element' class='radio-inline-list'>
        <label for='sp_type'>            
            <?php echo $this->element->getElement('sp_type')->getLabel() ?>
            <?php $i=0;
                  $value = $this->element->getElement('sp_type')->getValue();
                  foreach ($this->element->getElement('sp_type')->getMultiOptions() as $radio) : ?>
                      <input type="radio" value="<?php echo $i ?>" id="sp_type-<?php echo $i ?>" name="sp_type" <?php if($i == $value){echo 'checked="checked"';}?> >
                          <?php echo $radio ?>
                      </input>
            <?php $i = $i + 1; ?>
            <?php endforeach; ?>
        </label>
        </dd>
        
        <dd id='sp_criteria-element'>
        <?php for($i = 1; $i <= $this->criteriasLength; $i++) {?>
            <div <?php if(($i > 1) && ($this->element->getElement('sp_criteria_'.$i)->getValue() == "0" &&
                           $this->element->getElement('sp_criteria_modifier_'.$i)->getValue() == "0")) {
                           echo 'style=display:none';
                       } ?>>
        
                <?php echo $this->element->getElement('sp_criteria_'.$i) ?>
                <?php echo $this->element->getElement('sp_criteria_modifier_'.$i) ?>
                <?php echo $this->element->getElement('sp_criteria_value_'.$i) ?>
                <a href='#' id='criteria_remove_<?php echo $i ?>'>Remove</a>
            </div>
        <?php } ?>
        <a href='#' id='criteria_add'>Add</a>
        </dd>
        
        <dd id='sp_limit-element'>
            <label>
                <?php echo $this->element->getElement('sp_limit_check') ?>
                <?php echo $this->element->getElement('sp_limit_check')->getLabel() ?>
                <?php echo $this->element->getElement('sp_limit_value')?>
                <?php echo $this->element->getElement('sp_limit_options') ?>
            </label>
        </dd>
        
        <dd id='sp_save'>
            <?php echo $this->element->getElement('save_button') ?>
        </dd>
        
</dl>
</fieldset>
</form>