<h2 class="collapsible-header close"><span class="arrow-icon"></span>Set <?php echo $this->setNumber?></h2>
<fieldset class='toggle <?php echo $this->openOption ? "" : "closed"?>' id='sp_set_<?php echo $this->setNumber?>'>
    <dl class='zend_form'>
        
        <dd id='sp_criteria-element'>
        <?php for ($i = 0; $i < $this->criteriasLength; $i++) {?>
            <div <?php if (($i > 0) && ($this->element->getElement("sp_criteria_field_".$this->setNumber."_".$i)->getAttrib('disabled') == 'disabled')) {
                           echo 'style=display:none';
                       } ?>>
        
                <?php echo $this->element->getElement("sp_criteria_field_".$this->setNumber."_".$i) ?>
                <?php echo $this->element->getElement("sp_criteria_modifier_".$this->setNumber."_".$i) ?>
                <?php echo $this->element->getElement("sp_criteria_value_".$this->setNumber."_".$i) ?>
                <span class='sp_text_font' id="extra_criteria" <?php echo $this->element->getElement("sp_criteria_extra_".$this->setNumber."_".$i)->getAttrib("disabled") == "disabled"?'style="display:none;"':""?>> to <?php echo $this->element->getElement('sp_criteria_extra_'.$this->setNumber.'_'.$i) ?></span> 
                <a class='ui-button sp-ui-button-icon-only' id='criteria_remove_<?php echo $this->setNumber ?>_<?php echo $i ?>'>
                    <span class='ui-icon ui-icon-closethick'></span>
                </a>
                <br />
            </div>
            
        <?php } ?>
        <br />
        </dd>
        
        <dd id='sp_limit-element'>
            <span class='sp_text_font'><?php echo $this->element->getElement('sp_limit_value_'.$this->setNumber)->getLabel() ?></span>
            <?php echo $this->element->getElement('sp_limit_value_'.$this->setNumber)?>
            <?php echo $this->element->getElement('sp_limit_options_'.$this->setNumber) ?>
        <br /><br />
        </dd>
        <div class='sp_text_font sp_text_font_bold'>
            <span id='sp_pool_count' class='sp_text_font sp_text_font_bold'>
            <?php
            if ($this->poolCount > 1) {
                echo $this->poolCount;
            ?>
                files meet the criteria
                </span>
                <span class='checked-icon sp-checked-icon' id='sp_pool_count_icon'></span>
            <?php 
            } else if ($this->poolCount == 1) {
                echo $this->poolCount;
            ?>
                file meets the criteria
                </span>
                <span class='checked-icon sp-checked-icon' id='sp_pool_count_icon'></span>
            <?php 
            } else {
            ?> 
                0 files meet the criteria
                </span>
                <span class='sp-warning-icon' id='sp_pool_count_icon'></span>
            <?php 
            }
            ?>
        </div>
        
    </dl>
</fieldset>