<fieldset class="padded">
    <dl id="public-info" style="display:<?php echo "block"?>;">
        <dt id="stationName-label" class="block-display">
            <label class="required" for="stationName"><?php echo $this->element->getElement('stationName')->getLabel() ?>
                <span class="info-text-small"><?php echo _("(Required)")?></span>:
            </label>
        </dt>
        <dd id="stationName-element" class="block-display">
            <?php echo $this->element->getElement('stationName') ?>
            <?php if($this->element->getElement('stationName')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('stationName')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Phone-label" class="block-display">
            <label class="optional" for="Phone"><?php echo $this->element->getElement('Phone')->getLabel() ?></label>
            <span class="info-text-small"><?php echo _("(for verification purposes only, will not be published)")?></span>
        </dt>
        <dd id="Phone-element" class="block-display">
            <?php echo $this->element->getElement('Phone') ?>
            <?php if($this->element->getElement('Phone')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Phone')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Email-label" class="block-display">
            <label class="optional" for="Email"><?php echo $this->element->getElement('Email')->getLabel() ?></label>
            <span class="info-text-small">
                <?php echo _("(for verification purposes only, will not be published)")?>
            </span>
        </dt>
        <dd id="Email-element" class="block-display">
            <?php echo $this->element->getElement('Email') ?>
            <?php if($this->element->getElement('Email')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Email')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="StationWebSite-label" class="block-display">
            <label class="optional" for="StationWebSite"><?php echo $this->element->getElement('StationWebSite')->getLabel() ?></label>
        </dt>
        <dd id="StationWebSite-element" class="block-display clearfix">
            <?php echo $this->element->getElement('StationWebSite') ?>
            <?php if($this->element->getElement('StationWebSite')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('StationWebSite')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Country-label" class="block-display">
            <label class="optional" for="Country"><?php echo $this->element->getElement('Country')->getLabel() ?></label>
        </dt>
        <dd id="Country-element" class="block-display clearfix">
            <?php echo $this->element->getElement('Country') ?>
            <?php if($this->element->getElement('Country')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Country')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="City-label" class="block-display">
            <label class="optional" for="City"><?php echo $this->element->getElement('City')->getLabel() ?></label>
        </dt>
        <dd id="City-element" class="block-display clearfix">
            <?php echo $this->element->getElement('City') ?>
            <?php if($this->element->getElement('City')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('City')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Description-label" class="block-display">
            <label class="optional" for="Description"><?php echo $this->element->getElement('Description')->getLabel() ?></label>
        </dt>
        <dd id="Description-element" class="block-display clearfix">
            <?php echo $this->element->getElement('Description') ?>
            <?php if($this->element->getElement('Description')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Description')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Logo-label" class="block-display">
            <label class="optional" for="Description"><?php echo $this->element->getElement('Logo')->getLabel() ?></label>
        </dt>
        <dd id="Logo-element" class="block-display clearfix">
            <?php if($this->element->getView()->logoImg){?>
            <div id="Logo-img-container"><img id="logo-img" onload='resizeImg(this, 450, 450);' src="data:image/png;base64,<?php echo $this->element->getView()->logoImg ?>" /></div>
            <?php }?>

            <?php echo $this->element->getElement('Logo') ?>
            <div class="info-text">
                <p><?php echo _("Note: Anything larger than 600x600 will be resized.")?></p>
            </div>
            <?php if($this->element->getElement('Logo')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Logo')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
    </dl>
</fieldset>
