<fieldset class="padded">
    <dl class="zend_form">
        <dd id="SupportFeedback-element" style="width:90%;">
            <div class="info-text">
               <?php echo sprintf(_("Help improve %s by letting us know how you're using it. This information"
                ." will be collected regularly in order to enhance your user experience.<br />"
                ."Click the box below and we'll make sure the features you use are constantly improving."), 
                       PRODUCT_NAME)?>
            </div>
            <label class="optional" for="SupportFeedback">
                <?php echo $this->element->getElement('SupportFeedback') ?>
                <strong><?php echo $this->element->getElement('SupportFeedback')->getLabel() ?></strong>
            </label>
            <?php if($this->element->getElement('SupportFeedback')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('SupportFeedback')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
        <dd id="publicize-element" style="width:90%;">
            <div class="info-text">
                <?php 
                
                $whosUsingAnchor = "<a id='link_to_whos_using' href='" . WHOS_USING_URL . "' onclick='window.open(this.href); return false'>"
                                    . COMPANY_SITE
                                . "</a>";
                echo sprintf(_("Click the box below to promote your station on %s."), $whosUsingAnchor)
                ?>
            </div>
            <label class="optional" for="Publicise">
                <?php echo $this->element->getElement('Publicise') ?>
                <strong><?php echo $this->element->getElement('Publicise')->getLabel() ?></strong>
            </label>
            <?php if($this->element->getElement('Publicise')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Publicise')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?> 
        </dd>
    </dl>
    <div class="info-text" style="clear: both;padding: 4px 0 4px 15px;">
        <?php echo _("(In order to promote your station, 'Send support feedback' must be enabled).")?><br /><br />
    </div>
    <dl id="public-info" style="display:<?php echo "none"?>;">
        <dt id="stationName-label" class="block-display">
            <label class="required" for="stationName"><?php echo $this->element->getElement('stationName')->getLabel() ?>
                <span class="info-text-small"><?php echo _("(Required)")?></span>:
            </label>
        </dt>
        <dd id="stationName-element" class="block-display">
            <?php echo $this->element->getElement('stationName') ?>
            <?php if($this->element->getElement('stationName')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('stationName')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Phone-label" class="block-display">
            <label class="optional" for="Phone"><?php echo $this->element->getElement('Phone')->getLabel() ?></label>
            <span class="info-text-small"><?php echo _("(for verification purposes only, will not be published)")?></span>
        </dt>
        <dd id="Phone-element" class="block-display">
            <?php echo $this->element->getElement('Phone') ?>
            <?php if($this->element->getElement('Phone')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Phone')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Email-label" class="block-display">
            <label class="optional" for="Email"><?php echo $this->element->getElement('Email')->getLabel() ?></label>
            <span class="info-text-small">
                <?php echo _("(for verification purposes only, will not be published)")?>
            </span>
        </dt>
        <dd id="Email-element" class="block-display">
            <?php echo $this->element->getElement('Email') ?>
            <?php if($this->element->getElement('Email')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Email')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="StationWebSite-label" class="block-display">
            <label class="optional" for="StationWebSite"><?php echo $this->element->getElement('StationWebSite')->getLabel() ?></label>
        </dt>
        <dd id="StationWebSite-element" class="block-display clearfix">
            <?php echo $this->element->getElement('StationWebSite') ?>
            <?php if($this->element->getElement('StationWebSite')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('StationWebSite')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Country-label" class="block-display">
            <label class="optional" for="Country"><?php echo $this->element->getElement('Country')->getLabel() ?></label>
        </dt>
        <dd id="Country-element" class="block-display clearfix">
            <?php echo $this->element->getElement('Country') ?>
            <?php if($this->element->getElement('Country')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Country')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="City-label" class="block-display">
            <label class="optional" for="City"><?php echo $this->element->getElement('City')->getLabel() ?></label>
        </dt>
        <dd id="City-element" class="block-display clearfix">
            <?php echo $this->element->getElement('City') ?>
            <?php if($this->element->getElement('City')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('City')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <dt id="Description-label" class="block-display">
            <label class="optional" for="Description"><?php echo $this->element->getElement('Description')->getLabel() ?></label>
        </dt>
        <dd id="Description-element" class="block-display clearfix">
            <?php echo $this->element->getElement('Description') ?>
            <?php if($this->element->getElement('Description')->hasErrors()) : ?>
                <ul class='errors'>
                    <?php foreach($this->element->getElement('Description')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
    </dl>
</fieldset>
