<div class="text-content">
    <h2><?php echo _("About") ?></h2>
<p>
<?php 
echo sprintf(_("%sAirtime%s %s, the open radio software for scheduling and remote station management. %s"),
    "<a href='http://airtime.sourcefabric.org' target='_blank'>",
    "</a>",
     $this->airtime_version,
    "<br />")
?>
<br>© 2013 
<?php 
echo sprintf(_("%sSourcefabric%s o.p.s. Airtime is distributed under the %sGNU GPL v.3%s"),
    "<a href='http://www.sourcefabric.org' target='_blank'>",
    "</a>",
    "<a href='http://www.gnu.org/licenses/gpl-3.0-standalone.html' target='_blank'>",
    "</a>")
?>
</p>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
