<div class="text-content">
    <h2>About</h2>
<p>
<a href="http://airtime.sourcefabric.org" target="_blank">Airtime</a> <?php echo $this->airtime_version ?>, the open radio software for scheduling and remote station management.<br>
© 2012 <a href="http://www.sourcefabric.org" target="_blank">Sourcefabric</a> o.p.s. Airtime is distributed under the <a href="http://www.gnu.org/licenses/gpl-3.0-standalone.html" target="_blank">GNU GPL v.3</a>
</p>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
