<img src="/css/images/big_gray_logo.png" width="287" height="109" alt="Airtime" class="gray-logo" />
<div class="text-content">
  <h2>Welcome to Airtime!</h2>
<p>Here's how you can get started using Airtime to automate your broadcasts: </p>

<ol>
    <li>Add your files to the library using the "Add Media" button. You can drag and drop your files to this window too.</li>
    <li>Create a show by going to "Calendar" in the menu bar, and then clicking the "+ Show" icon. This can be either a one-time or repeating show. Only admins and program managers can add shows.</li>
    <li>Add media to the show by going to your show in the Schedule calendar, left-clicking on it and selecting "Add / Remove Content".</li>
    <li>Select your media from the left pane and drag them to your show in the right pane.</li>
</ol>
<p><strong>Then you're good to go!</strong><br />
For more detailed help, read the <a href="http://www.sourcefabric.org/en/airtime/manuals/" target="_blank">user manual</a>.</p>
</div>

