<div class="gray-logo"></div>
<div class="text-content">
  <h2><?php echo _("Welcome to Airtime!") ?></h2>
<p><?php echo _("Here's how you can get started using Airtime to automate your broadcasts: ")?></p>

<ol>
    <li><?php echo _("Begin by adding your files to the library using the 'Add Media' menu button. You can drag and drop your files to this window too.")?></li>
    <li><?php echo _("Create a show by going to 'Calendar' in the menu bar, and then clicking the '+ Show' icon. This can be either a one-time or repeating show. Only admins and program managers can add shows.")?></li>
    <li><?php echo _("Add media to the show by going to your show in the Schedule calendar, left-clicking on it and selecting 'Add / Remove Content'")?>.</li>
    <li><?php echo _("Select your media from the left pane and drag them to your show in the right pane."); ?></li>
</ol>
<p><strong><?php echo _("Then you're good to go!")?></strong><br />
<?php echo sprintf(_("For more detailed help, read the %suser manual%s."),
    "<a href='http://www.sourcefabric.org/en/airtime/manuals/' target='_blank'>",
    "</a>") ?></p>
</div>

