<div id="content" class="jp-container">
<script>
$(document).ready(function(){

    $("#jquery_jplayer_1").jPlayer({
        ready: function () {
            $(this).jPlayer("setMedia", {
                oga: "http://localhost:8000/airtime_128"
            }).jPlayer("play");
        },
        ended: function (event) {
            $(this).jPlayer("play");
        },
        swfPath: "js",
        supplied: "oga",
        wmode: "window"
    });
});
</script>
  <div class="jp-logo"></div>
        <div class="jp-stream">
            <div class="jp-stream-text">Select stream:</div>
              <form id="form1" method="post" action="">
                  <label>
                    <input type="radio" name="select-stream" value="radio" id="select-stream_0" checked="checked" />
                    48 Kbit/s</label>
                  <label>
                    <input type="radio" name="select-stream" value="radio" id="select-stream_1" />
                    96 Kbit/s</label>
                  <label>
                    <input type="radio" name="select-stream" value="radio" id="select-stream_2" />
                    192 Kbit/s</label>
              </form>
        </div>
        <div id="jquery_jplayer_1" class="jp-jplayer"></div>

  <div id="jp_container_1" class="jp-audio">
            <div class="jp-type-single">
                <div id="jp_interface_1" class="jp-gui jp-interface">
                    <ul class="jp-controls">
                        <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                        <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                        <li><a href="javascript:;" class="jp-mute" tabindex="1">mute</a></li>
                        <li><a href="javascript:;" class="jp-unmute" tabindex="1">unmute</a></li>
                    </ul>
                </div>
                <div id="jp_playlist_1" class="jp-playlist">
                </div>

            </div>
        </div>
</div>
