#!/bin/bash
#
# Auto install script for airtime on Debian


#Current dir
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=`readlink -f $0`
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`

cd $SCRIPTPATH/../ubuntu
./airtime-full-install

