<?php
$get_artwork = FileDataHelper::getArtworkData($this->artwork, 256);
$baseUrl = Application_Common_OsPath::getBaseDir();

$get_replay_gain = Application_Model_Preference::getReplayGainModifier();
if (!Application_Model_Preference::GetEnableReplayGain() ) {
    $get_replay_gain = 0;
}
$analogMeter = true;
?>
<div class="ui-widget ui-widget-content block-shadow simple-formblock clearfix padded-strong edit-md-dialog" file-id="<?php echo $this->id; ?>">

    <div class="track-edit-header">
        <div class="track-edit-right-wrapper">
            <div class="track-edit-right">
                <div class="inner_track_editor_title">
                    <div class="track_editor_title"><span class="title_obj_name"><?php echo($this->title); ?></span></div>
                    <div class="track_editor_creator"><span class=""><?php echo($this->artist_name); ?></span></div>
                </div>
            </div>
        </div>
        <div class="track-edit-left">
            <div class="artwork-upload" data-id="<?php echo($this->id); ?>">
                <div class="artwork-edit">
                    <input type='file' class="artworkUpload artwork-uploaded-<?php echo($this->id); ?>" id="artworkUpload" data-id="<?php echo($this->id); ?>" accept=".png, .jpg, .jpeg" />
                    <label for="artworkUpload"></label>
                </div>
                <div class="artwork-preview">
                    <div class="artwork-preview-<?php echo($this->id); ?>" style="background-image: url(<?php echo $get_artwork; ?>);">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="track-window">
        <div class="editor-tabs">
       		<ul id="tracks-inner-tab-<?php echo $this->id; ?>" class="navtt nav-tabs">
         				<li class="active"><a href="#tracktab-details-<?php echo $this->id; ?>"><?php echo _("Details") ?></a></li>
                <?php if (!$this->permissionDenied) { ?>
             				<li><a href="#tracktab-editor-<?php echo $this->id; ?>"><?php echo _("Editor") ?></a></li>
             				<li><a href="#tracktab-artwork-<?php echo $this->id; ?>"><?php echo _("Artwork") ?></a></li>
                <?php } ?>
                <li><a href="#tracktab-file-<?php echo $this->id; ?>"><?php echo _("File") ?></a></li>
       		</ul>
 		    </div>
   		  <section id="tracktab-details-<?php echo $this->id; ?>" class="navtt-content active">
            <div style="text-align: left;">
                <?php if ($this->permissionDenied) { ?>
                <div class="alert alert-warning permission-text" role="alert">
                    <?php echo _("You do not have permission to edit this track.") ?>
                </div>
               <?php } ?>
                <?php echo $this->form; ?>
            </div>
   		 </section>
   		  <section id="tracktab-editor-<?php echo $this->id; ?>" class="navtt-content hide">
            <div style="width:500px">
                 <div class="controls">
                      <div class="row">
                          <div class="col-sm-7">
                              <div class="btn-toolbar track-toolbar">
                                    <div class="btn-group" title="Play Controls">
                                      <button class="btn btn-control-player btn-new control-play-btn" id="track-play-<?php echo $this->id; ?>" onClick="wavesurfer['t<?php echo $this->id; ?>'].playPause();" style="background-color:#555555; border-top-left-radius: 5px; border-bottom-left-radius: 5px;">
                                        <i class="icon-white icon-play"></i>
                                      </button>
                                      <button class="btn btn-control-player btn-new control-playedit-btn" id="track-playedit-<?php echo $this->id; ?>"
                                        onClick="" style="background-color:#555555; border-top-right-radius: 5px; border-bottom-right-radius: 5px">
                                        <i class="icon-white icon-step-backward"></i>
                                      </button>
                                    </div>
                                    <div class="btn-group" title="Playhead"> <!-- TODO: support for typing it in -->
                                      <div class="btn track-timer" style="border-radius: 5px">
                                        <input class="track-timer-input" id="tracktimerinput-<?php echo $this->id; ?>" val="0.000" style="font-size:15px; font-weight:500;"/>
                                      </div>
                                    </div>

                                    <!-- TODO: these buttons are temporary, need better ones for setting cue in and out -->
                                    <div class="btn-group" title="Cue Controls">
                                      <button class="btn  btn-new control-play-btn" id="cue-set-<?php echo $this->id; ?>" style="background-color:#555555; border-top-left-radius: 5px; border-bottom-left-radius: 5px;">
                                        <span style="font-size:22px; font-weight:800; color:rgb(0, 230, 64);">›</span>
                                      </button>
                                      <button class="btn  btn-new control-playedit-btn" id="cue-set-<?php echo $this->id; ?>"
                                        onClick="" style="background-color:#555555; border-top-right-radius: 5px; border-bottom-right-radius: 5px">
                                        <span style="font-size:22px; font-weight:800; color:rgb(242, 38, 19);">‹</span>
                                      </button>
                                    </div>

                                    <div class="btn-group pull-right zoom-container" title="Zoom">
                                        <input id="zoom-slider-<?php echo $this->id; ?>" class="input-slider" data-height="26" data-width="120" data-action="zoom-<?php echo $this->id; ?>" type="range"  min="20" max="290" data-sprites="50" data-src="<?php echo $baseUrl.'css/images/slider.png'; ?>" value="0" />
                                    </div>
                                    <br><br>
                              </div>
                          </div>
                      </div>
                      <div class="row">
                            <div id="track-waveform-<?php echo $this->id; ?>"></div>
                            <div id="timeline-<?php echo $this->id; ?>"></div>
                      </div>
                      <div class="row gain-row">
                           <div class="gain-inner-section">
                                  <div class="gain-col-knob">
                                          <div title="Gain">
                                            <div class="knob-controls">
                                              <div style="margin-left:13px; font-size:11px;"><span>GAIN</span></div>
                                              <input id="replay_gain_knob_<?php echo $this->id; ?>" type="range"
                                              class="input-knob"
                                              data-src="<?php echo $baseUrl.'css/images/knob_2x.png'; ?>"
                                              data-sprites="100"
                                              style="width: 52px; height: 52px; background-image: url(<?php echo $baseUrl.'css/images/knob_2x.png'; ?>); background-size: 100% 10100%; background-position: 0px 0px;"
                                              value="0">
                                             <div class="knob-labels" style="margin-left:13px"><span id="gain-val-<?php echo $this->id; ?>"><?php echo $this->replay_gain; ?></span></div>
                                             <input type="hidden" id="volume-<?php echo $this->id; ?>" type="range" min="0" max="1" value="1" step="0.1">
                                            </div>
                                          </div>
                                  </div>
                                  <div class="gain-col-meter">
                                          <?php if($analogMeter == true){ ?>
                                              <div style="position: relative; left: 0; top: 0;" >
                                                <img src="<?php echo $baseUrl.'css/images/meterbg.png'; ?>" class="meterbg" style="width:200px" />
                                                <div class="meterwrappercont">
                                                    <div id="meterwrapper-<?php echo $this->id; ?>" style="height:220px;width:220px;">
                                                        <img id="meter_needle-<?php echo $this->id; ?>" class="meter_needle" src="<?php echo $baseUrl.'css/images/meterneedle.svg'; ?>">
                                                    </div>
                                                </div>
                                                <input class="testgain" id="testgain-<?php echo $this->id; ?>" val=""/>
                                                <div class="db-letters">dB</div>

                                              </div>
                                        <?php } ?>
                                  </div>
                                  <div class="gain-col-meter2">
                                        <button id="gain-clipping-<?php echo $this->id; ?>" class="btn btn-small btn-new" style="background-color:rgb(101,	0,	0)">
                                           <span></span>
                                        </button>
                                        <br><span style="font-size:8px">Todo: adjust clipping to default gain in LT.</span>
                                  </div>
                                  <div class="clear"></div>
                           </div>
                     </div>
                </div>

     			  </div>
   		  </section>
        <section id="tracktab-artwork-<?php echo $this->id; ?>" class="navtt-content hide">
     			<div>
            <div class="artwork-upload" data-id="<?php echo($this->id); ?>" style="width:300px; height: 300px;">
                <div class="artwork-edit" style="width:300px; height: 300px;">
                    <input type='file' class="artworkUpload artwork-uploaded-<?php echo($this->id); ?>" id="artworkUpload" data-id="<?php echo($this->id); ?>" accept=".png, .jpg, .jpeg" />
                    <label for="artworkUpload" style="width:300px; height: 300px;"></label>
                </div>
                <div class="artwork-preview" style="width:300px; height: 300px;">
                    <div class="artwork-preview-<?php echo($this->id); ?>" style="background-image: url(<?php echo $get_artwork; ?>);">
                    </div>
                </div>
            </div>

            <br>
            <div>
              <div href="#" class="delete-artwork knob-labels" data-id="<?php echo($this->id); ?>" style="font-size: 11px; width: 80px; padding:3px; cursor:pointer;"><span>Remove</span></div>
            </div>
     			</div>
   		 </section>
        <section id="tracktab-file-<?php echo $this->id; ?>" class="navtt-content hide">
     			 <div class="track-file-details">
               <?php echo _("ID:") ?>: <?php echo $this->id; ?></br>
               <?php echo _("Bit Rate:") ?> <?php echo $this->bit_rate; ?></br>
               <?php echo _("Sample Rate:") ?> <?php echo $this->sample_rate; ?></br>
               <?php echo _("Format:") ?>: <?php echo $this->format; ?> </br>
               <?php echo _("Encoded By:") ?> <?php echo $this->encoded_by; ?></br>
               <?php echo _("File Size:") ?> <?php echo $this->filesize; ?></br>
     			</div>
   		  </section>
    </div>

    <script>
        //waveform
        var track_id      = <?php echo $this->id; ?>;
        var selector_id   = "#track-waveform-"+<?php echo $this->id; ?>;
        var url           = baseUrl + 'api/get-media/file/<?php echo $this->id; ?>';
        var cuein         = '<?php echo $this->cuein; ?>';
        var cueout        = '<?php echo $this->cueout; ?>';
        var gain_level    = deciSteps(<?php echo $this->replay_gain; ?>);
        var default_gain  = <?php echo $get_replay_gain; ?>;
        renderWaveform(track_id, selector_id, url, cuein, cueout, gain_level, default_gain);

        $(document).ready(function() {

            //Inner Track Tabs
            $('#tracks-inner-tab-<?php echo $this->id; ?> > li > a').click(function(event){
                event.preventDefault();
                var active_tab_selector = $('#tracks-inner-tab-<?php echo $this->id; ?> > li.active > a').attr('href');
                var actived_nav = $('#tracks-inner-tab-<?php echo $this->id; ?> > li.active');
                actived_nav.removeClass('active');
                $(this).parents('li').addClass('active');
                $(active_tab_selector).removeClass('active');
                $(active_tab_selector).addClass('hide');
                var target_tab_selector = $(this).attr('href');
                $(target_tab_selector).removeClass('hide');
                $(target_tab_selector).addClass('active');
            });

            //Gain Knob
            $("#replay_gain_knob_<?php echo $this->id; ?>").val(deciNum(<?php echo $this->replay_gain; ?>));
            $("#volume-<?php echo $this->id; ?>").val(deciSteps(<?php echo $this->replay_gain; ?>));

            $(document).on('mouseleave', '#replay_gain_knob_<?php echo $this->id; ?>', 'input', function() {
                var val = $(this).val();
                $("#gain-val-<?php echo $this->id; ?>").text(gainNum(val));
            });

            $(document).on('change', '.replay_gain_<?php echo $this->id; ?>', 'input', function(event) {
                event.preventDefault();
                event.stopPropagation();
                var val = $(this).val();
                $("input#replay_gain_knob_<?php echo $this->id; ?>").val(deciNum(val));
            }).on('keyup', '.replay_gain_<?php echo $this->id; ?>', 'input', function(event) {
                event.preventDefault();
                event.stopPropagation();
                var val = $(this).val();
                $("input#replay_gain_knob_<?php echo $this->id; ?>").val(deciNum(val));
            });
            /*
            $(document).on('change', '.cuein_<?php echo $this->id; ?>', 'input', function(event) {
                event.preventDefault();
                event.stopPropagation();
                var val = $(this).val();
                TODO: *
            }).on('keyup', '.cuein_<?php echo $this->id; ?>', 'input', function(event) {
                event.preventDefault();
                event.stopPropagation();
                var val = $(this).val();
                TODO: *
            });*/

        });
    </script>

  </div>
