<div id="configure_item_template" class="ui-widget ui-widget-content block-shadow alpha-block padded">

  <div>
    <select id="template_list">
      <option value="">New</option>
      <?php foreach ($this->template_list as $id=>$name): ?>
      <option value="<?php echo $id; ?>"><?php echo $name; ?></option>
      <?php endforeach; ?>
    </select>
  </div>
  
  <?php echo $this->render('playouthistory/item-template.phtml'); ?>

</div>