<div id="history_content" class="ui-widget ui-widget-content block-shadow alpha-block padded">
  <?php echo $this->date_form; ?>

  <div id="his-tabs">
    <ul>
      <li><a href="#his-tabs-1"><?php echo _("Log Sheet"); ?></a></li>
      <li><a href="#his-tabs-2"><?php echo _("File Summary"); ?></a></li>
    </ul>
    <div id="his-tabs-1">
      <table id="history_table_list" cellpadding="0" cellspacing="0" class="datatable"></table>
    </div>
    <div id="his-tabs-2">
      <table id="history_table_aggregate" cellpadding="0" cellspacing="0" class="datatable"></table>
    </div>
  </div>

</div>