<dt id="<?php echo $this->element->getName() ?>-label" class="block-display">
    <?php echo $this->formLabel($this->element->getName(),
                         $this->element->getLabel()) ?>
</dt>
<dd id="<?php echo $this->element->getName() ?>-element" class="block-display clearfix">
<?php $i=0 ?>
<?php foreach ($this->element->getMultiOptions() as $opt) : ?> 
    <label class="wrapp-label" for="<?php echo $this->element->getName() ?>-<?php echo $i ?>">
        <input id="<?php echo $this->element->getName() ?>-<?php echo $i ?>" value="<?php echo $i ?>" type="checkbox" name="add_show_day_check[]"><?php echo $opt ?></input>
    </label>
    <?php $i=$i+1 ?>
<?php endforeach; ?>
    <?php if($this->element->hasErrors()) { echo $this->formErrors($this->element->getMessages());} ?>
</dd>
