<fieldset class="padded">
    <dl class="zend_form">
        <dd id="UseSoundCloud-element" class="block-display" style=" margin:6px 0 10px 0">
            <label class="optional" for="UseSoundCloud">
                <?php echo $this->element->getElement('UseSoundCloud') ?>
                <strong><?php echo $this->element->getElement('UseSoundCloud')->getLabel() ?></strong>
            </label>
        </dd>
        <dt id="SoundCloudUser-label" class="block-display">
            <label class="optional" for="SoundCloudUser"><?php echo $this->element->getElement('SoundCloudUser')->getLabel() ?></label>
        </dt>
        <dd id="SoundCloudUser-element" class="block-display">
            <?php echo $this->element->getElement('SoundCloudUser') ?>
        </dd>
        <dt id="SoundCloudPassword-label" class="block-display">
            <label class="optional" for="SoundCloudPassword"><?php echo $this->element->getElement('SoundCloudPassword')->getLabel() ?></label>
        </dt>
        <dd id="SoundCloudPassword-element" class="block-display">
            <?php echo $this->element->getElement('SoundCloudPassword') ?>
        </dd>
        <dt id="SoundCloudTags-label" class="block-display">
            <label class="optional" for="SoundCloudTags"><?php echo $this->element->getElement('SoundCloudTags')->getLabel() ?></label>
        </dt>
        <dd id="SoundCloudTags-element" class="block-display clearfix">
            <?php echo $this->element->getElement('SoundCloudTags') ?>
        </dd>
        <dt id="SoundCloudGenre-label" class="block-display">
            <label class="optional" for="SoundCloudGenre"><?php echo $this->element->getElement('SoundCloudGenre')->getLabel() ?></label>
        </dt>
        <dd id="SoundCloudGenre-element" class="block-display">
            <?php echo $this->element->getElement('SoundCloudGenre') ?>
        </dd>
        <dt id="SoundCloudTrackType-label" class="block-display">
             <label class="optional" for="SoundCloudTrackType"><?php echo $this->element->getElement('SoundCloudTrackType')->getLabel() ?></label>
        </dt>
        <dd id="SoundCloudTrackType-element" class="block-display">
            <?php echo $this->element->getElement('SoundCloudTrackType') ?>
        </dd>
        <dt id="SoundCloudLicense-label" class="block-display">
            <label class="optional" for="SoundCloudLicense"><?php echo $this->element->getElement('SoundCloudLicense')->getLabel() ?></label>
        </dt>
        <dd id="SoundCloudLicense-element" class="block-display">
            <?php echo $this->element->getElement('SoundCloudLicense') ?>
        </dd>
    </dl>
</fieldset>
