<form name="SPL">
	<div>
		<span id="spl_new">
		<a href="<?php echo $this->url(
			array(
				'controller' => 'Playlist',
				'action'     => 'new'
			),
			'default',
			true) ?>">New</a>
		</span>
		<?php if (isset($this->pl)) { echo '<span id="spl_delete">Delete</span>';} ?>
		<?php if (isset($this->pl)) { echo '<span id="spl_close">Close</span>';} ?>
	<div>
	<div id="spl_name"><?php if (isset($this->pl)) { echo $this->pl->getName(); } ?></div>
	<div id="spl_length"><?php if (isset($this->pl)) { echo $this->pl->getLength(); } ?></div>
	<div class="spl_main">
		<?php 
			if (isset($this->pl)) {

				echo '<div class="spl_head">';
				echo '<span class="spl_input"><input type="checkbox" name="all"></span>';
				echo '<span class="spl_title">Title</span>';
				echo '<span class="spl_artist">Creator</span>';
				echo '<span class="spl_playlength">Playlength</span>';      
				echo '</div>';

				echo '<ul id="spl_sortable">';

				if (count($this->pl->getContents())) {
					echo $this->partialLoop('sideplaylist/sidebarcontent.phtml', $this->pl->getContents());
				}
				else {
					echo '<li class="spl_empty">Empty playlist</li>'; 
				}

				echo '</ul></div>';
			}
			else {
				echo '<div>No open playlist</div>';
			}
		?>
</form>
<div class="spl_footer">
	<?php if (isset($this->pl)) { echo '<span id="spl_remove_selected">Remove</span>';} ?>
</div>
