<li class="spl_row" id="spl_<?php echo $this->partialCounter-1 ?>">
    <span class="spl_input">
    	<input type="checkbox" class="checkbox" name="<?php echo $this->partialCounter-1 ?>"/>
    </span>
    <span class="spl_title">
    	<?php echo $this->CcFiles['track_title'] ?>
    </span>
    <span class="spl_artist">
    	<?php echo $this->CcFiles['artist_name'] ?>
    </span>
    <span class="spl_playlength">
        <?php echo $this->cliplength ?>
    </span>
</li>
