<div id='demo'></div>
<script>
function getDateText(obj){
	var str = obj.aData[ obj.iDataColumn ];
	if (str.indexOf(" ") != -1){
		return changeTimePrecision(str.substring(0, str.indexOf(" ")));
	}
	return str;
}

function getTimeText(obj){
	var str = obj.aData[ obj.iDataColumn ];
	if (str.indexOf(" ") != -1){
		return changeTimePrecision(str.substring(str.indexOf(" ")+1));
	}
	return str;
}

function changeTimePrecisionInit(obj){
	var str = obj.aData[ obj.iDataColumn ];
	return changeTimePrecision(str);
}

function changeTimePrecision(str){
	if (str.indexOf(".") != -1){
		if (str.length - str.indexOf(".") > 2)
			var extraLength = str.length - str.indexOf(".") -3;
			return str.substring(0, str.length - extraLength);
	}
	return str;
}

function createDataGrid(obj){
	
	obj.columnHeaders[0]["fnRender"] = getDateText;
	obj.columnHeaders[1]["fnRender"] = getTimeText;
	obj.columnHeaders[2]["fnRender"] = getTimeText;
	obj.columnHeaders[3]["fnRender"] = changeTimePrecisionInit;
	
	$('#demo').html( '<table cellpadding="0" cellspacing="0" border="0" class="display" id="example"></table>' );
	$('#example').dataTable( {
		"bSort" : false,
		"bJQueryUI": true,
		"bFilter": true,
		"bInfo": false,
		"bLengthChange": false,
		"aaData": obj.rows,
		"aoColumns": obj.columnHeaders
	} );	
}

function init2(){
	  $.ajax({ url: "/Nowplaying/get-data-grid-data/format/json", dataType:"json", success:function(data){
		createDataGrid(data.entries);
	  }});
	  //setTimeout(init2, 5000);
}

$(document).ready(function() {
	init2();
});
</script>
