<div id='demo'></div>
<script>
function getDateText(obj){
	//var str = "";
	//for (s in obj.oSettings)
	//	str += s + ", ";
	//alert(str);
	var str = obj.aData[ obj.iDataColumn ];
	if (str.indexOf(" ") != -1){
		return changeTimePrecision(str.substring(0, str.indexOf(" ")));
	}
	return str;
}

function getTimeText(obj){
	var str = obj.aData[ obj.iDataColumn ];
	if (str.indexOf(" ") != -1){
		return changeTimePrecision(str.substring(str.indexOf(" ")+1));
	}
	return str;
}

function changeTimePrecisionInit(obj){
	var str = obj.aData[ obj.iDataColumn ];
	return changeTimePrecision(str);
}

function changeTimePrecision(str){
	if (str.indexOf(".") != -1){
		if (str.length - str.indexOf(".") > 2)
			var extraLength = str.length - str.indexOf(".") -3;
			return str.substring(0, str.length - extraLength);
	}
	return str;
}

function notifySongEnd(){
	for (row in datagridData.rows){
		if (row[0] == "c")
			row[0] = "p";
		if (row[0] == "n"){
			row[0] = "c";
			break;
		}
	}
	
	createDataGrid();
}

function createDataGrid(){
	
	datagridData.columnHeaders[1]["fnRender"] = getDateText;
	datagridData.columnHeaders[2]["fnRender"] = getTimeText;
	datagridData.columnHeaders[3]["fnRender"] = getTimeText;
	datagridData.columnHeaders[4]["fnRender"] = changeTimePrecisionInit;
		
	$('#demo').html( '<table cellpadding="0" cellspacing="0" border="0" class="display" width="100%" id="nowplayingtable"></table>' );
	$('#nowplayingtable').dataTable( {
		"bSort" : false,
		"bJQueryUI": true,
		"bFilter": false,
		"bInfo": false,
		"bLengthChange": false,
		"aaData": datagridData.rows,
		"aoColumns": datagridData.columnHeaders,
		"fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
			if (aData[0] == "p"){
				//$(nRow).attr("style", "background-color:blue;");
			} else if (aData[0] == "c"){
				$(nRow).attr("style", "background-color:#61B329;");
			} else if (aData[0] == "n"){
			}
			return nRow;
		}
	} );	
}

var registered = false

function init2(){
	  $.ajax({ url: "/Nowplaying/get-data-grid-data/format/json", dataType:"json", success:function(data){
		datagridData = data.entries;
		createDataGrid();
	  }});
	  
	  if (typeof registerSongEndListener == 'function' && !registered){
		  registered = true;
		  registerSongEndListener(notifySongEnd);
	  }
	  
	  setTimeout(init2, 5000);
}

$(document).ready(function() {
	init2();
});
</script>
