#!/bin/bash

virtualenv_bin="/usr/lib/airtime/airtime_virtualenv/bin/"
. ${virtualenv_bin}activate

recorder_user="pypo"


# Location of pypo_cli.py Python script
recorder_path="/usr/lib/airtime/show-recorder/"
recorder_script="recorder.py"

api_client_path="/usr/lib/airtime/"
cd ${recorder_path}

exec 2>&1

export HOME="/var/tmp/airtime/show-recorder/"
export TERM=xterm
export PYTHONPATH=${api_client_path}

#this line works: su ${recorder_user} -c "python -u ${recorder_path}${recorder_script}"
# Note the -u when calling python! we need it to get unbuffered binary stdout and stderr
exec python -u ${recorder_path}${recorder_script}  > /var/log/airtime/show-recorder/py-interpreter.log 2>&1

# EOF
