#!/bin/bash -e
#-e Causes bash script to exit if any of the installers
#return with a non-zero return value.

if [ `whoami` != 'root' ]; then
    echo "Please run as root user."
    exit 1
fi

set +e
DEB=$(dpkg -s airtime 2> /dev/null | grep Status)
set -e
if [[ "$DEB" = "Status: install ok installed" ]]; then
    echo -e "\nDebian package of Airtime detected. Please use the debian package to upgrade.\n"
    exit 1
fi

#Check whether version of virtualenv is <= 1.4.8. If so exit install. 
BAD_VERSION="1.4.8"
VERSION=$(virtualenv --version)
NEWEST_VERSION=$(echo -e "$BAD_VERSION\n$VERSION\n'" | sort -t '.' -g | tail -n 1)
echo -n "Ensuring python-virtualenv version > $BAD_VERSION..."
if [[ "$NEWEST_VERSION" = "$BAD_VERSION" ]]; then
    URL="http://apt.sourcefabric.org/pool/main/p/python-virtualenv/python-virtualenv_1.4.9-3_all.deb"
    echo "Failed!"
    echo "You have version $BAD_VERSION or older installed. Please install package at $URL first and then try installing Airtime again."
    exit 1
else
    echo "Success!"
fi


echo -e "\n******************************** Install Begin *********************************"

#copy files to 
## /etc/airtime
#+ /etc/apache2/sites-available/airtime
#+ /etc/apache2/sites-enabled/airtime
## /etc/cron.d/
## /etc/init.d/
## /etc/monit/conf.d/
# /usr/lib/airtime/airtime_virtualenv
# /usr/lib/airtime/api_clients
# /usr/lib/airtime/media-monitor
# /srv/airtime
# /usr/lib/airtime/pypo
# /usr/lib/airtime/show-recorder
## /usr/lib/airtime/utils
## /usr/bin/airtime-*
## /usr/share/airtime
## /var/log/airtime
## /var/tmp/airtime

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=`readlink -f $0`
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`

mkdir -p /etc/airtime
cp $SCRIPTPATH/../airtime_mvc/build/airtime.conf /etc/airtime
cp $SCRIPTPATH/../python_apps/api_clients/api_client.cfg /etc/airtime
cp $SCRIPTPATH/../python_apps/show-recorder/recorder.cfg /etc/airtime
cp $SCRIPTPATH/../python_apps/media-monitor/media-monitor.cfg /etc/airtime
cp $SCRIPTPATH/../python_apps/pypo/pypo.cfg /etc/airtime
cp $SCRIPTPATH/../python_apps/pypo/liquidsoap_scripts/liquidsoap.cfg /etc/airtime

HOUR=$(($RANDOM%24))
MIN=$(($RANDOM%60))
echo "$MIN $HOUR * * * root /usr/lib/airtime/utils/phone_home_stat" > /etc/cron.d/airtime-crons

cp $SCRIPTPATH/../python_apps/show-recorder/airtime-show-recorder-init-d /etc/init.d/airtime-show-recorder
cp $SCRIPTPATH/../python_apps/media-monitor/airtime-media-monitor-init-d /etc/init.d/airtime-media-monitor
cp $SCRIPTPATH/../python_apps/pypo/airtime-playout-init-d /etc/init.d/airtime-playout

cp $SCRIPTPATH/../python_apps/monit/monit-airtime-generic.cfg /etc/monit/conf.d/
#cp $SCRIPTPATH/../python_apps/monit/monit-airtime-rabbitmq-server.cfg /etc/monit/conf.d/
cp $SCRIPTPATH/../python_apps/media-monitor/monit-airtime-media-monitor.cfg /etc/monit/conf.d/
cp $SCRIPTPATH/../python_apps/show-recorder/monit-airtime-show-recorder.cfg /etc/monit/conf.d/
cp $SCRIPTPATH/../python_apps/pypo/monit-airtime-liquidsoap.cfg /etc/monit/conf.d/
cp $SCRIPTPATH/../python_apps/pypo/monit-airtime-playout.cfg /etc/monit/conf.d/

cp -R $SCRIPTPATH/../utils /usr/lib/airtime

ln -s /usr/lib/airtime/utils/airtime-import/airtime-import /usr/bin/airtime-import
ln -s /usr/lib/airtime/utils/airtime-update-db-settings /usr/bin/airtime-update-db-settings
ln -s /usr/lib/airtime/utils/airtime-check-system /usr/bin/airtime-check-system
ln -s /usr/lib/airtime/utils/airtime-log /usr/bin/airtime-log

cp -R $SCRIPTPATH/../airtime_mvc/* /usr/share/airtime/

mkdir -p /var/log/airtime
mkdir -p /var/tmp/airtime
