#!/bin/bash -e

#Check if root user
if [ `whoami` != 'root' ]; then
    echo "Please run as root user."
    exit 1
fi

echo -e "\n******************************* Uninstall Begin ********************************"

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=`readlink -f $0`
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`

#Uninitialize Airtime
$SCRIPTPATH/include/airtime-uninitialize.sh

#Remove Airtime files
$SCRIPTPATH/include/airtime-remove-files.sh

#Remove pypo user
python $SCRIPTPATH/../python_apps/remove-pypo-user.py

echo -e "\n****************************** Uninstall Complete *******************************"
