<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jp_container_1" class="jp-audio">
<?php if (isset($this->playlistID)): ?>
    <span class='playlistID'><?php echo "$this->playlistID" ?></span>
    <span class='playlistIndex'><?php echo "$this->playlistIndex" ?></span>
<?php elseif (isset($this->audioFileID)): ?>
    <span class='audioFileID'><?php echo "$this->audioFileID" ?></span>
    <span class='audioFileTitle'><?php echo "$this->audioFileTitle" ?></span>
    <span class='audioFileArtist'><?php echo "$this->audioFileArtist" ?></span>
<?php elseif (isset($this->showID)): ?>
    <span class='showID'><?php echo "$this->showID" ?></span>
    <span class='showIndex'><?php echo "$this->showIndex" ?></span>
<?php endif;?>
    <div class="jp-type-playlist">
        <div class="jp-gui jp-interface">
            <ul class="jp-controls">
                <li class="ui-state-default ui-corner-all jp-previous">
                    <span class="ui-icon ui-icon-seek-prev" tabindex="1">previous</span>
                </li>
                <li class="ui-state-default ui-corner-all jp-play">
                    <span class="ui-icon ui-icon-play" tabindex="1">play</span>
                </li>
                <li class="ui-state-default ui-corner-all jp-pause">
                    <span class="ui-icon ui-icon-pause" tabindex="1">pause</span>
                </li>
                <li class="ui-state-default ui-corner-all jp-next">
                    <span class="ui-icon ui-icon-seek-next" tabindex="1">next</span>
                </li>
                <li class="ui-state-default ui-corner-all jp-stop">
                    <span class="ui-icon ui-icon-stop" tabindex="1">stop</span>
                </li>
            </ul>
            <div class="jp-time-block">
                <div class="jp-progress">
                    <div class="jp-seek-bar">
                        <div class="jp-play-bar"></div>
                    </div>
                </div>
                <div class="jp-time-holder">
                    <div class="jp-current-time"></div>
                    <div class="jp-duration"></div>
                </div>
            </div>
            <div class="jp-volume-block">
                <div class="jp-mute">
                    <span class="ui-icon" tabindex="1" title="mute">mute</span>
                </div>
                <div class="jp-unmute">
                    <span class="ui-icon" tabindex="1" title="unmute">unmute</span>
                </div> 
                <div class="jp-volume-bar">
                    <div class="jp-volume-bar-value"></div>
                </div>
                <div class="jp-volume-max">
                    <span class="ui-icon" tabindex="1" title="max volume">max volume</span>
                </div>
            </div>
        </div>
        <div class="jp-playlist">
            <ul>
                <li></li>
            </ul>
        </div>
        <div class="jp-no-solution">
            <span>Update Required</span>
            To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
        </div>
    </div>
</div>
