<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo _("An error has occurred.") ?></title>
    <?php echo $this->headLink(); ?>
</head>

<body>
    <div class="error-content" id="error-500">
        <h2><?php echo _("Oops!") ?></h2>
        <p><?php echo _("Something went wrong!") ?></p>
        <div class="button-bar">
            <a class="toggle-button" href="<?php echo TROUBLESHOOTING_URL; ?>" target="_blank">
                <?php echo _("Troubleshooting help") ?>
            </a>
            <a class="toggle-button" href="<?php echo $this->helpUrl; ?>" target="_blank">
                <?php echo _("More help") ?>
            </a>
        </div>
    </div>
</body>

</html>
