<div id="player-widget" class="ui-widget prefpanel simple-formblock embed-player-form clearfix padded-strong ">

    <?php $baseUrl = Application_Common_OsPath::getBaseDir(); ?>

    <form method="post" id="player_form" enctype="multipart/form-data">
        <h2 style="text-align:center"><?php echo _("Player") ?></h2>
        <div style="clear:both"></div>
        <?php echo $this->player_error_msg; ?>
        <?php echo $this->player_form; ?>

    </form>
</div>
