<div class="login_box">
    <div class="logobox">&nbsp;</div>
        <h2>Login</h2>
    
    <div id="login" class="login-content clearfix">
        <p class="light"><?php echo $this->message; ?></p>
        <?php echo $this->form; ?>
    </div>
</div>
<div class="footer"> Airtime&nbsp;<?php echo $this->airtimeVersion ?>&nbsp;Copyright &copy; Sourcefabric o.p.s <?php echo $this->airtimeCopyright ?>. All rights reserved.<br/>
  Maintained and distributed under GNU GPL v.3 by <a href="http://www.sourcefabric.org"> Sourcefabric o.p.s </a> </div>
