<div class="login_box">
  <div class="logobox">&nbsp;</div>
  <h2><?php echo _("Reset password") ?></h2>

  <div id="login" class="login-content clearfix">
    <p class="light">
        <?php echo _("Enter your account e-mail address or your username (or both, if you have multiple accounts
                      using the same email address), and we'll send you a link to reset your password.")?>
    </p>
    <?php echo $this->form; ?>
  </div>
</div>
