<div class="ui-widget ui-widget-content block-shadow clearfix padded-strong user-management">
    <h2>Manage Users</h2>
    <div class="user-list-wrapper">
        <div id="users_wrapper" class="dataTables_wrapper">

            <div class="button-holder">
                <button type="button" id="add_user_button" name="search_add_group" class="ui-button ui-widget ui-state-default ui-button-text-icon-primary">
                    <span class="ui-icon ui-icon-plusthick"></span>
                    <span class="ui-button-text">New User</span>
                </button>
            </div>

            <table cellspacing="0" cellpadding="0" style="" id="users_datatable" class="datatable">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>Username</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Role</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
    <div class="user-data simple-formblock" id="user_details">
        <?php echo $this->successMessage ?>
        <fieldset class="padded">
            <?php echo $this->form ?>
        </fieldset>
    </div>
</div>
