# This file contains a list of package dependencies.
[python]
python3 = focal, bullseye, jammy, bookworm, noble, trixie, resolute
python3-pip = focal, bullseye, jammy, bookworm, noble, trixie, resolute

[liquidsoap]
# https://github.com/savonet/liquidsoap/blob/main/CHANGES.md
liquidsoap = focal, bullseye, jammy, bookworm, noble, trixie, resolute

[ffmpeg]
# Detect duration, silences and replaygain
ffmpeg = focal, bullseye, jammy, bookworm, noble, trixie, resolute

[=development]
# Generate fixtures
ffmpeg = focal, bullseye, jammy, bookworm, noble, trixie, resolute
