# This file contains a list of package dependencies.
[python]
python3 = bookworm, noble, trixie, resolute
python3-pip = bookworm, noble, trixie, resolute

[liquidsoap]
# https://github.com/savonet/liquidsoap/blob/main/CHANGES.md
liquidsoap = bookworm, noble, trixie, resolute

[ffmpeg]
# Detect duration, silences and replaygain
ffmpeg = bookworm, noble, trixie, resolute

[=development]
# Generate fixtures
ffmpeg = bookworm, noble, trixie, resolute
