#!/bin/bash
# Auto install script for airtime + nginx

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=`readlink -f $0`
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`

$SCRIPTPATH/airtime-full-install nginx

