<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="expires" content="-1">

	<title><?php echo _("Live stream") ?></title>

	<?php echo $this->headLink() ?>
	<?php echo $this->headScript() ?>
</head>

<body>
	<div id="content"><?php echo $this->layout()->content ?></div>
</body>

</html>
