<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <link rel="stylesheet" href="<?php echo $this->css?>" type="text/css">
    <script src="<?php echo $this->jquery ?>" type="text/javascript"></script>
    <script src="<?php echo $this->jquery_custom ?>" type="text/javascript"></script>
    <script src="<?php echo $this->widget_js ?>" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#onAirToday").airtimeShowSchedule({
                sourceDomain: "http://localhost",
                text: {onAirToday:"On air today"},
                updatePeriod: 5, //seconds
                showLimit: 10
            });
        });
    </script>
</head>

<body>
    <div id="onAirToday"></div>
</body>

</html>

