<div id="schedule-add-show" class="tabs ui-widget ui-widget-content block-shadow alpha-block padded">
    <div class="button-bar">
        <a href="#" id="add-show-close" class="icon-link"><span class="ui-icon ui-icon-circle-close"></span>Close</a>
        <button id="add-show-submit" class="right-floated">Add this show</button>
    </div>
    <div class="clear"></div>
    <h3 class="collapsible-header"><span class="arrow-icon"></span>What</h3>
    <div id="schedule-show-what" class="collapsible-content">
        <?php echo $this->what ?>
    </div>
    <h3 class="collapsible-header"><span class="arrow-icon"></span>When</h3>
    <div id="schedule-show-when" class="collapsible-content">
        <?php echo $this->when ?>
        <?php echo $this->repeats ?>
    </div>
    <h3 class="collapsible-header"><span class="arrow-icon"></span>Record & Rebroadcast</h3>  
    <div id="schedule-record-rebroadcast" class="collapsible-content">
        <?php echo $this->rr ?>
        <?php echo $this->rebroadcast ?>
    </div>
    <h3 class="collapsible-header"><span class="arrow-icon"></span>Who</h3>
    <div id="schedule-show-who" class="collapsible-content">
        <?php echo $this->who ?>
    </div>
    <h3 class="collapsible-header"><span class="arrow-icon"></span>Style</h3>
    <div id="schedule-show-style" class="collapsible-content">
        <?php echo $this->style ?>
    </div>
</div>

