<?php if(count($this->showContent) > 0) : ?>
	<?php foreach($this->showContent as $pl) : ?>
	<li id="g_<?php echo $pl["pl_group"] ?>" class="ui-widget-content">
		<h3>
			<div>
				<span><?php echo $pl["pl_name"] ?></span>
				<span><?php echo $pl["pl_length"] ?></span>
			</div>
			<div><?php echo $pl["pl_creator"] ?></div>
			<div><?php echo $pl["pl_description"] ?></div>
		</h3>
		<div>
			<?php foreach($pl["pl_content"] as $file) : ?>
			<div>
				<span><?php echo $file["f_name"] ?></span>
				<span><?php echo $file["f_length"] ?></span>
			</div>
			<div><?php echo $file["f_artist"] ?></div>
			<?php endforeach; ?>
		</div>
	</li>
	<?php endforeach; ?>
<?php else : ?>
<li>No Playlists</li>
<?php endif; ?>

