<div id="schedule_playlist_dialog">
	<div>	
		<input id="schedule_playlist_search" type="text"></input>
		<ul id="schedule_playlist_choice"></ul>
	</div>
	<div>
		<div>Items In This Show:</div>
		<ul id="schedule_playlist_chosen"></ul>
		<div id="show_time_info">
			<span id="show_time_filled" class="time"><?php echo $this->timeFilled; ?></span>
			<div id="show_progressbar"></div>
			<span id="show_length" class="time"><?php echo $this->showLength; ?></span>
		</div>
	</div>
</div>
