<?php if(count($this->showContent) > 0) : ?>
	<?php foreach($this->showContent as $pl) : ?>
	<li id="g_<?php echo $pl["pl_group"] ?>">
		<div><span class="ui-icon ui-icon-triangle-1-e"></span></div>
		<div><?php echo $pl["pl_name"] ?></div>
		<div><?php echo $pl["pl_creator"] ?></div>
		<div><?php echo $pl["pl_length"] ?></div>
		<div><span class="ui-icon ui-icon-close"></span></div>
		<div class="group_list" style="display:none">
			<div class="sched_description"><?php echo $pl["pl_description"] ?></div>
			<?php foreach($pl["pl_content"] as $file) : ?>
			<div>
				<span><?php echo $file["f_name"] ?></span>
				<span><?php echo $file["f_length"] ?></span>
			</div>
			<div><?php echo $file["f_artist"] ?></div>
			<?php endforeach; ?>
		</div>
	</li>
	<?php endforeach; ?>
<?php else : ?>
<li>No Playlists</li>
<?php endif; ?>

