<div id="schedule_playlist_dialog">
	<input id="schedule_playlist_search" type="text"></input>
	<div>
		<ul id="schedule_playlist_choice"></ul>
		<ul id="schedule_playlist_chosen"></ul>
	</div>
	<div id="show_time_info">
		<span id="show_time_filled"><?php echo $this->timeFilled; ?></span>
		<div id="show_progressbar"></div>
		<span id="show_length"><?php echo $this->showLength; ?></span>
	</div>
</div>
