<div id="show_content_dialog">
<div><?php echo $this->additionalShowInfo; ?></div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="datatable">
    <tr>
        <th>Start</th>
        <th>Title</th>
        <th>Creator</th>
        <th>Album</th>
        <th>Length</th>
        <th>Genre</th>
    </tr>
<?php $i=0; ?>
<?php foreach($this->showContent as $row): ?>
    <tr class="<?php if($i&1){echo "even";}else{echo "odd";}?>">
        <td><?php echo $row["starts"] ?></td>
        <td><?php echo $row["track_title"] ?></td>
        <td><?php echo $row["artist_name"] ?></td>
        <td><?php echo $row["album_title"] ?></td>
        <td><?php echo $row["length"] ?></td>
        <td><?php echo $row["genre"] ?></td>
    </tr>
<?php $i=$i+1; ?>
<?php endforeach; ?>
</table>
</div>
