#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import subprocess

if os.geteuid() != 0:
    print "Please run this as root."
    sys.exit(1)
    
try:
    print "Stopping daemontool script recorder"

    p1 = subprocess.Popen(["ps", "aux"], stdout=subprocess.PIPE)
    p2 = subprocess.Popen(["awk", "/recorder.py/ && !/awk/ {print $2}"], stdin=p1.stdout, stdout=subprocess.PIPE)
    recorder_pid = p2.communicate()[0].strip(" \n\r\t")
    if (len(recorder_pid) > 0):
        os.system("svc -d /etc/service/recorder 1>/dev/null 2>&1")
        os.system("svc -d /etc/service/recorder/log 1>/dev/null 2>&1")
        os.system("kill -2 %s" % recorder_pid)
        print "Success."
    else:
        print "Not Running."
    
except Exception, e:
    print "exception:" + str(e)
