#!/bin/bash
#
#

CAMPCASTER_DIR=/opt/campcaster
CAMPCASTER_BIN=$CAMPCASTER_DIR/bin
CAMPCASTER_ETC=$CAMPCASTER_DIR/etc
CAMPCASTER_LIB=$CAMPCASTER_DIR/lib

PATH=/sbin:/bin:/usr/sbin:/usr/bin:$CAMPCASTER_BIN
LD_LIBRARY_PATH=$CAMPCASTER_LIB:$LD_LIBRARY_PATH
DAEMON=$CAMPCASTER_BIN/campcaster-scheduler
NAME=campcaster-scheduler
DESC="campcaster scheduler"

test -x $DAEMON || exit 0

export PATH
export LD_LIBRARY_PATH

DAEMON_OPTS="-c $CAMPCASTER_ETC/campcaster-scheduler.xml"

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
    $DAEMON $DAEMON_OPTS start > /dev/null
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
    $DAEMON $DAEMON_OPTS stop > /dev/null
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
    $DAEMON $DAEMON_OPTS stop > /dev/null
	sleep 1
    $DAEMON $DAEMON_OPTS start > /dev/null
	echo "$NAME."
	;;
  kill)
	echo -n "Killing $DESC: "
    $DAEMON $DAEMON_OPTS kill > /dev/null
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload|kill}" >&2
	exit 1
	;;
esac

exit 0

