<?php

// This file generated by Propel 1.7.3-dev convert-conf target
// from XML runtime conf file /var/www/html/build/runtime-conf.xml
$conf = [
    'datasources' => [
        'airtime' => [
            'adapter' => 'pgsql',
            'connection' => [
                'dsn' => 'pgsql:host=localhost;port=5432;dbname=airtime;user=airtime;password=airtime',
            ],
        ],
        'airtime_test' => [
            'adapter' => 'pgsql',
            'connection' => [
                'dsn' => 'pgsql:host=localhost;port=5432;dbname=airtime_test;user=airtime;password=airtime',
            ],
        ],
        'default' => 'airtime',
    ],
    'generator_version' => '1.7.3-dev',
];
$conf['classmap'] = include dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-airtime-conf.php';

return $conf;
