<?php

declare(strict_types=1);

// This file generated by Propel 1.5.2 convert-conf target
// from XML runtime conf file /home/james/src/airtime/legacy/build/runtime-conf.xml

/* The original name of this file is airtime-conf.php but since we need to make custom changes
 * to it I've renamed it so that our changes aren't removed everytime we regenerate a database schema.
 * our custom changes requires the database parameters to be loaded from the config file so
 * that the user can customize these.
 */

$CC_CONFIG = Config::getConfig();

$dbhost = $CC_CONFIG['dsn']['host'];
$dbport = $CC_CONFIG['dsn']['port'];
$dbname = $CC_CONFIG['dsn']['database'];
$dbuser = $CC_CONFIG['dsn']['username'];
$dbpass = $CC_CONFIG['dsn']['password'];

$conf = [
    'datasources' => [
        'airtime' => [
            'adapter' => 'pgsql',
            'connection' => [
                'dsn' => "pgsql:host={$dbhost};port={$dbport};dbname={$dbname};user={$dbuser};password={$dbpass}",
            ],
        ],
        'default' => 'airtime',
    ],
    'generator_version' => '1.7.3-dev',
];
$conf['classmap'] = include dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-airtime-conf.php';

return $conf;
