fastcgi_cache_path /var/lib/nginx/cache levels=1:2 keys_zone=legacy:100m;
fastcgi_cache_key "$request_method$scheme$host$request_uri";

map $request_uri $legacy_no_cache {
  default "1";
  "/api/live-info" "0";
  "/api/week-info" "0";
  "~/api/track\\?id=\\d+&return=artwork" "0";
}

server {
  listen 8080;
  listen [::]:8080;

  root /var/www/html/public;

  index index.php index.html index.htm;

  client_max_body_size 512M;
  client_body_timeout 300s;

  location ~ \.php$ {
    fastcgi_buffers 64 4K;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;

    #try_files $uri =404;
    try_files $fastcgi_script_name =404;

    include fastcgi_params;

    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    set $path_info $fastcgi_path_info;
    fastcgi_param PATH_INFO $path_info;

    fastcgi_cache legacy;
    fastcgi_cache_valid 200 5s;

    fastcgi_no_cache      $legacy_no_cache;
    fastcgi_cache_bypass  $legacy_no_cache;

    fastcgi_index index.php;
    fastcgi_pass legacy:9000;
  }

  location / {
    try_files $uri $uri/ /index.php$is_args$args;
  }

  location ~ ^/api/(v2|browser) {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_redirect off;
    proxy_pass http://api:9001;
  }

  # Internal path for serving media files from the API.
  location /api/_media {
    internal;
    # This alias path must match the 'storage.path' configuration field.
    alias /srv/libretime;
  }
}
