<div id="weekly-schedule-widget" class="prefpanel ui-widget simple-formblock clearfix padded-strong ">

    <?php $baseUrl = Application_Common_OsPath::getBaseDir(); ?>

    <h2 style="text-align:center"><?php echo _("Weekly Schedule") ?></h2>
    <div style="clear:both"></div>

    <div id="weekly-schedule-widget-error">
        <?php echo $this->weekly_schedule_error_msg; ?>
    </div>
    <h3 style="float:left"><?php echo _("Preview:") ?></h3>
    <fieldset class="padded">
        <div id="weekly-schedule-widget-preview" <?php if (isset($this->weekly_schedule_error_msg)) echo "style=display:none"; ?>>
            <!-- <label><?php echo _("Preview:") ?></label> -->
            <div class="schedule_iframe_wrapper">
                <iframe id="schedule_iframe" height="400px" width="550px" scrolling="no" frameborder="0" src="<?php echo Application_Common_HTTPHelper::getStationUrl()."embed/weekly-program"?>"></iframe>
            </div>

            <div style="clear:both"></div>
            <label><?php echo _("Embeddable code:") ?><br><br></label>
            <textarea style="width:98%" rows="3" readonly="readonly"><iframe height="400px" width="550px" scrolling="no" frameborder="0" src="<?php echo Application_Common_HTTPHelper::getStationUrl()."embed/weekly-program"?>"></iframe>
            </textarea>
            <div><p>
                 <?php echo _("Copy this code and paste it into your website's HTML to embed the weekly schedule in your site. Adjust the height and width attributes to your desired size.") ?>
                </p>
            </div>
        </div>
    </fieldset>
</div>
