<form name="PL">
    <div class="pl_head">
        <span class="pl_input"><input type="checkbox" name="all"></span>
        <span class="pl_title">Title</span>
        <span class="pl_artist">Creator</span>
        <span class="pl_length">Length</span>
        <span class="pl_cue_in">Cue In</span>
        <span class="pl_cue_out">Cue Out</span>
        <span class="pl_playlength">Playlength</span>      
    </div>
	<div class="pl_main">
    	<ul id="pl_sortable">
		<?php 
			if (count($this->playlistcontents)) {
				echo $this->partialLoop('playlist/playlistEditorTable.phtml', $this->playlistcontents);
			}
			else {
				echo '<li class="pl_empty">Empty playlist</li>'; 
			}
		?>
		</ul>
	</div>
</form>
<div class="pl_footer">
    <span id="pl_remove_selected">Remove Selected</span>
	<span id="pl_delete">
		<a href="<?php echo $this->url(
		array(
		    'controller' => 'Playlist',
		    'action'     => 'delete-active'
		),
		'default',
		true) ?>">Delete Playlist</a>
	</span>
</div>
