<button id="spl_new">New</button>
<?php if (isset($this->pl)) : ?>
<button id="spl_delete">Delete</button>
<button id="spl_close">Close</button>
<?php endif; ?>

<?php if (isset($this->pl)) : ?>
<div id="spl_name"><?php echo $this->pl->getName(); ?></div>
<div id="spl_length"><?php echo $this->pl->getLength(); ?></div>

<ul id="spl_sortable">
	<?php if (count($this->pl->getContents())) : ?>
	<?php echo $this->partialLoop('playlist/sidebarcontent.phtml', $this->pl->getContents()); ?>
	<?php else : ?>
	<li class="spl_empty">Empty playlist</li> 
	<?php endif; ?>
</ul>
<div id="spl_editor"></div>
<?php else : ?>
<div>No open playlist</div>
<?php endif; ?>
