<span id="spl_new">New</span>
<?php if (isset($this->pl)) : ?>
<span id="spl_delete">Delete</span>
<span id="spl_close">Close</span>
<?php endif; ?>

<?php if (isset($this->pl)) : ?>
<div id="spl_name"><?php echo $this->pl->getName(); ?></div>
<div id="spl_length"><?php echo $this->pl->getLength(); ?></div>

<ul id="spl_sortable">
	<?php if (count($this->pl->getContents())) : ?>
	<?php echo $this->partialLoop('playlist/sidebarcontent.phtml', $this->pl->getContents()); ?>
	<?php else : ?>
	<li class="spl_empty">Empty playlist</li> 
	<?php endif; ?>
</ul>
<div id="spl_cue_edit"></div>
<?php else : ?>
<div>No open playlist</div>
<?php endif; ?>
