<?php // playlistEditorTable.phtml ?>

<li class="pl_row" id="pl_<?php echo $this->partialCounter-1 ?>">
	<div class="pl_fade_in">
		<span>Fade in: </span><span class="pl_time"><?php echo $this->fadein ?></span>
	</div>
    <span class="pl_input">
    	<input type="checkbox" class="checkbox" name="<?php echo $this->partialCounter-1 ?>"/>
    </span>
    <span class="pl_title">
    	<?php echo $this->CcFiles['track_title'] ?>
    </span>
    <span class="pl_artist">
    	<?php echo $this->CcFiles['artist_name'] ?>
    </span>
    <span class="pl_length" >
        <?php echo $this->CcFiles['length'] ?>
    </span>
    <span class="pl_cue_in pl_time">
        <?php echo $this->cuein ?>
    </span>
    <span class="pl_cue_out pl_time">
        <?php echo $this->cueout ?>
    </span>
    <span class="pl_playlength">
        <?php echo $this->cliplength ?>
    </span>
    <div class="pl_fade_out">
		<span>Fade out: </span><span class="pl_time"><?php echo $this->fadeout ?></span>
	</div>
</li>
