<dl id="spl_cue_editor" class="inline-list">
    <dt>Cue In:</dt>
    <dd id="spl_cue_in_<?php echo $this->pos; ?>" class="spl_cue_in">
        <span contenteditable="true" class="spl_text_input"><?php echo $this->cueIn; ?></span>
    </dd>
    <dd><span class="edit-error"></span></dd>
    <dt>Cue Out:</dt>
    <dd id="spl_cue_out_<?php echo $this->pos; ?>" class="spl_cue_out">
        <span contenteditable="true" class="spl_text_input"><?php echo $this->cueOut; ?></span>
    </dd>
    <dd><span class="edit-error"></span></dd>
    <dt>Original Length:</dt>
    <dd id="spl_original"><span><?php echo $this->origLength; ?></span></dd>
</dl>
