<li class="ui-state-default" id="spl_<?php echo $this->partialCounter-1 ?>">
	<div>
		<span class="ui-icon ui-icon-play"></span>
	</div>
	<div>
		<span class="spl_title"><?php echo $this->CcFiles['track_title'] ?></span>
		<span class="spl_playlength"><?php echo $this->cliplength ?></span>
		<span class="ui-icon ui-icon-close"></span>
		<span class="spl_artist"><?php echo $this->CcFiles['artist_name'] ?></span>
		<?php if($this->partialCounter-1 > 0): ?>
		<div id="fade_<?php echo $this->partialCounter-1 ?>" class="spl_fade_control ui-state-default ui-corner-all">Fade</div>
		<?php endif; ?>
	<div>
</li>
