<?php
/**
 * Created by PhpStorm.
 * User: asantoni
 * Date: 17/11/15
 * Time: 4:31 PM
 */
?>

<?php require(__DIR__."/featureupgrade.phtml"); ?>

<div class="angular_wrapper" ng-controller="Publish">

    <div class="btn-toolbar clearfix" style="position: absolute; bottom: 4px; right: 4px">
        <div class="btn-group pull-right">
            <button ng-click="discard()" class="btn" type="button" name="close">
                <?php echo _("Close") ?>
            </button>
        </div>
    </div>
</div>
