.\"                                      Hey, EMACS: -*- nroff -*-
.\" URL Macro
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CAMPCASTER\-SCHEDULER 1 "October 5, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.nh
.SH NAME
campcaster-scheduler \- Script controlling the Campcaster scheduling daemon
.SH SYNOPSIS
.B campcaster-scheduler
.RI start|stop|restart|status|install|uninstall|kill
.SH DESCRIPTION
This script controls the Campcaster scheduler daemon, which is usually 
launched during boot with administrator privileges. However, this tool is also used to
query the current status of the server or perform administrative tasks.
.PP
The scheduler daemon starts playlists at their designated time and provides an
XML-RPC interface, which can be accessed via the Campcaster web interface or via the 
campcaster-studio GUI.
.PP
Campcaster is free and open radio management software, providing
live studio broadcast capabilities as well as the remote automation in one
integrated system. The scalability of Campcaster allows implementation in a
number of use scenarios, ranging from an unmanned broadcast unit accessed via
the Internet to a local network of Campcaster machines inside a
radio station handling live broadcasts and delivering program automation by
accessing a central audio storage system. Campcaster is capable of combining
local audio files and remote web streams, supporting the widely used MP3 format
and the open equivalent OGG Vorbis.
.SH SEE ALSO
.URL "http://en.flossmanuals.net/campcaster/" "Online manual",
.br
.BR campcaster-studio (1),
.BR campcaster-import (1).
.SH AUTHOR
Campcaster was written by Sourcefabric, with the support of the Media Develoment 
Loan Fund. For full credits see the
.URL "http://campcaster.sourcefabric.org/" "Campcaster homepage".
.PP
This manual page was written by Robin Gareus <robin@gareus.org>,
for the Debian project (and may be used by others).
