#!/bin/bash
#preinst script for airtime

set -e

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

case "$1" in
  install|upgrade)

    # Remove liquidsoap binary from old installs
    if [ -f /var/lib/airtime/python_apps/pypo/liquidsoap/liquidsoap ]; then
     echo "Removing old Liquidsoap binary..." >&2
     rm -f /var/lib/airtime/python_apps/pypo/liquidsoap/liquidsoap
    fi

  ;;

  abort-upgrade)
    echo "Upgrade aborting..." >&2
  ;;

  *)
       echo "preinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
