#!/bin/bash
#prerm script for airtime

set -e

package_name="airtime"
datadir="/var/lib/${package_name}/tmp"

case "$1" in
  remove)
      cd $datadir/install_minimal/ && ./airtime-uninstall || true
  ;;

  purge)
      cd $datadir/install_minimal/ && ./airtime-uninstall --purge || true
  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
      echo "prerm called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

#DEBHELPER#

exit 0
