# This file contains a list of package dependencies.
[python]
python3 = bookworm, noble, trixie, resolute
python3-pip = bookworm, noble, trixie, resolute
python3-lxml = bookworm, noble, trixie, resolute

[liquidsoap]
# https://github.com/savonet/liquidsoap/blob/main/CHANGES.md
liquidsoap = bookworm, noble, trixie, resolute

[misc]
# Used by pypofetch to check if a file is open.
# TODO: consider using a python library
lsof = bookworm, noble, trixie, resolute
