<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <script src="<?php echo $this->mrp_js?>" type="text/javascript"></script>
    <script type="text/javascript">

        function musesCallback(event,value){
            if (event == "source") {
                //MRP.setUrl("http://sourcefabric.out.airtime.pro:8000/sourcefabric_b");
            }
        }
        </script>
</head>
<body>

<script type="text/javascript">
    MRP.insert({
        'url':"<?php echo $this->streamURL ?>",
        'codec':"<?php echo $this->codec ?>",
        'volume':100,
        'jsevents':true,
        'autoplay':false,
        'buffering':5,
        'title':'test',
        'bgcolor':'#FFFFFF',
        'skin':"<?php echo $this->skin ?>",
        'width':180,
        'height':60
    });

</script>

</body>
</html>