<div class="ui-widget ui-widget-content block-shadow simple-formblock clearfix padded-strong preferences">
    <h2 style="float:left"><?php echo _("Embeddable Player") ?></h2>
    <?php $baseUrl = Application_Common_OsPath::getBaseDir(); ?>
    <form method="post" id="player_form" enctype="multipart/form-data">


        <div style="clear:both"></div>
        <?php

        echo $this->statusMsg;
        echo $this->form;
        ?>
        <?php echo $this->form->getElement('submit')->render() ?>
        <br />
    </form>
</div>
