<fieldset id="add_show_rebroadcast_absolute">
    <dl>
    <dt id="add_show_hosts_rebroadcast_day-label" class="block-display">
        <label for="add_show_rebroadcast_day" class="optional"><?php echo _("Choose Days:"); ?></label>
    </dt>
    <dd id="add_show_rebroadcast_day-element" class="block-display clearfix">
    <ul class="formrow-repeat">
        <?php for($i=1; $i<=10; $i++): ?>
            <li <?php if(($i > 1)
                        && ($this->element->getElement('add_show_rebroadcast_date_absolute_'.$i)->getValue() == ""
                        && $this->element->getElement('add_show_rebroadcast_time_absolute_'.$i)->getValue() == "")){echo 'style=display:none';} ?>>
                <?php echo $this->element->getElement('add_show_rebroadcast_date_absolute_'.$i) ?>
                <span class="inline-text">@</span>
                <?php echo $this->element->getElement('add_show_rebroadcast_time_absolute_'.$i) ?>
                <?php if($i > 1): ?>
                    <a class="ui-button ui-button-icon-only  ui-widget ui-state-default" id="remove_rebroadcast_absolute_<?php echo $i ?>">
                        <span class="ui-icon ui-icon-closethick"></span>
                        <span class="ui-button-text"><?php echo _("Remove") ?></span>
                    </a>
                <?php endif; ?>
                <?php if(($this->element->getElement('add_show_rebroadcast_date_absolute_'.$i)->hasErrors())
                  || ($this->element->getElement('add_show_rebroadcast_time_absolute_'.$i)->hasErrors())) : ?>
                    <ul class='errors'>
                        <?php $errors = array_merge(
                                $this->element->getElement('add_show_rebroadcast_date_absolute_'.$i)->getMessages(),
                                $this->element->getElement('add_show_rebroadcast_time_absolute_'.$i)->getMessages()
                                );
                        ?>

                        <?php foreach($errors as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endfor; ?>
    </ul>
    <a class="ui-button ui-button-icon-only  ui-widget ui-state-default add_absolute_rebroadcast_day">
        <span class="ui-icon ui-icon-plusthick"></span>
        <span class="ui-button-text"><?php echo _("Add") ?></span>
    </a>
    </dd>
    </dl>
</fieldset>
