<fieldset>
    <dl>
        <?php echo $this->element->getElement('cb_airtime_auth')->render(); ?>
        <?php echo $this->element->getElement('cb_custom_auth')->render(); ?>
        <div id="custom_auth_div">
            <?php echo $this->element->getElement('custom_username')->render(); ?>
            <?php echo $this->element->getElement('custom_password')->render(); ?>
        </div>
        <fieldset id="add-show-show-source">
            <legend><?php echo _("Show Source") ?></legend>
            <p class="input-settings-inline-p">
                <?php echo _("DJs can use these settings to connect with compatible software and broadcast live during this show. Assign a DJ below.") ?>
            </p>
            <?php echo $this->element->getElement("show_source_host")->render() ?>
            <?php echo $this->element->getElement("show_source_port")->render() ?>
            <?php echo $this->element->getElement("show_source_mount")->render() ?>
        </fieldset>
     </dl>
</fieldset>
