<dt id="<?php echo $this->element->getName() ?>-label" class="<?php echo $this->class ?>">
    <?php echo $this->formLabel($this->element->getName(),
                         $this->element->getLabel()) ?>
</dt>
<dd id="<?php echo $this->element->getName() ?>-element" class="<?php echo $this->class ?>">
    <?php echo $this->{$this->element->helper}(
        $this->element->getName(),
        $this->element->getValue(),
        $this->element->getAttribs()
    ) ?>
    <?php if($this->element->hasErrors()) {
            echo $this->formErrors($this->element->getMessages());
        }
    ?>
</dd>
