<fieldset>
    <form enctype="application/x-www-form-urlencoded" method="post" action="">
        <dl class="zend_form">

            <p><?php echo(_("Please enter both your username and email address.")); ?></p>
            <dt id="username-label">
                <label for="username" class="required">
                    <?php echo $this->element->getElement('username')->getLabel() ?>
                </label>
                </dt>
                <dd id="username-element">
                    <?php echo $this->element->getElement('username') ?>
                </dd>
            </dt>

            <dt id="email-label">
                <label for="email" class="required">
                    <?php echo $this->element->getElement('email')->getLabel() ?>
                </label>
            </dt>
            <dd id="email-element">
                <?php echo $this->element->getElement('email') ?>
            </dd>
            <?php if ($this->element->getElement('email')->hasErrors()): ?>
                <ul class='errors'>
                    <?php foreach ($this->element->getElement('email')->getMessages() as $error): ?>
                        <li><?php echo $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <dt id="submit-label">&nbsp;</dt>
            <dd id="submit-element">
                <?php echo $this->element->getElement('submit') ?>
            </dd>

            <dd id="cancel-element">

                <a href="<?php echo($this->baseUrl('login')); ?>">
                    <button name="cancel" type="button" class="ui-button ui-widget ui-state-default ui-button-text-only center"><?php echo(_("Back")); ?></button>
                </a>
            </dd>
        </dl>
    </form>
</fieldset>
