<form enctype="application/x-www-form-urlencoded" method="post" action="">
  <dl class="zend_form">
    <dt id="new-password-label">
      <label for="new-password" class="required">
          <?php echo $this->element->getElement('password')->getLabel() ?>
      </label>
    </dt>
    <dd id="new-password-element">
      <?php echo $this->element->getElement('password') ?>
    </dd>
    <?php if($this->element->getElement('password')->hasErrors()): ?>
        <ul class='errors'>
            <?php foreach($this->element->getElement('password')->getMessages() as $error): ?>
                <li><?php echo $error; ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

    <dt id="confirm-password-label">
      <label for="confirm-password" class="required">
          <?php echo $this->element->getElement('password_confirm')->getLabel() ?>
      </label>
    </dt>
    <dd id="confirm-password-element">
      <?php echo $this->element->getElement('password_confirm') ?>
    </dd>
    <?php if($this->element->getElement('password_confirm')->hasErrors()): ?>
        <ul class='errors'>
            <?php foreach($this->element->getElement('password_confirm')->getMessages() as $error): ?>
                <li><?php echo $error; ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

    <dt id="submit-label">&nbsp;</dt>
    <dd id="submit-element">
      <?php echo $this->element->getElement('submit') ?>
    </dd>
  </dl>
</form>
