<style type="text/css">

.player-title {
	width: 70px;
	border-style: none
	float: left;
	}

.preview-label {
	line-height: 60px;
	border-style: none
	float: left;
	font-size: 20px;
	color: #fff
	}

</style>
<fieldset class="padded">
    <dl class="zend_form">

        <?php echo $this->element->getElement('player_preview_label')->renderLabel(); ?>

        <div style="clear:both"></div>
        <div class="player-preview">
            <?php echo $this->element->getElement('player_embed_src')->getValue(); ?>
        </div>

        <div id="player_instructions">
            <?php echo _("Customize the player by configuring the options below. When you are done,
            copy the embeddable code below and paste it into your website's HTML.") ?>
        </div>

        <?php echo $this->element->getElement('player_title')->render(); ?>

        <?php echo $this->element->getElement('player_stream_mode')->render(); ?>

        <?php echo $this->element->getElement('player_stream_url'); ?>

        <?php echo $this->element->getElement('player_embed_src')->render(); ?>

        <?php //echo $this->element->getElement('player_display_track_metadata'); ?>

        <table id="player_compatibility_chart" style="text-align:center; position:relative; top:40px;">
            <th colspan="5" style="text-align:center"><?php echo _("Stream Compatibility") ?></th>
            <tr>
                <td colspan="3"><?php echo _("Desktop") ?></td>
                <td colspan="2"><?php echo _("Mobile") ?></td>
            </tr>
            <tr>
                <td>Firefox</td>
                <td>Chrome</td>
                <td>Internet Explorer</td>
                <td>Android 5 - Chrome</td>
                <td>iOS 7 - Safari</td>
            </tr>
            <tr>
                <td><?php echo _("Yes (Flash)") ?></td>
                <td><?php echo _("Yes (Flash)") ?></td>
                <td><?php echo _("Yes (Flash)") ?></td>
                <td><?php echo _("MP3/OGG* only") ?></td>
                <td><?php echo _("MP3/AAC only") ?></td>
            </tr>
            <tr>
                <td colspan="5" style="text-align:left"><?php echo _("* Chrome on Android is known to take about 4 seconds to buffer a 128 kbps MP3 stream. Lower bitrates take longer to buffer.") ?></td>
            </tr>
        </table>


    </dl>
</fieldset>
