<fieldset class="padded">
    <dl class="zend_form">

        <?php echo $this->element->getElement('stationName')->render() ?>

        <?php echo $this->element->getElement('stationDescription')->render() ?>

        <?php echo $this->element->getElement('stationLogo')->render() ?>

        <?php echo $this->element->getElement('stationLogoRemove')->render() ?>

        <!--        <button id="logo-remove-btn" value="Remove" class="btn">Remove</button>-->

        <div id="Logo-img-container">
            <?php
            $logoImg = $this->element->getView()->logoImg;
            $src = "data:image/png;base64," . $logoImg;
            ?>
            <img onError="this.onerror = '';this.style.visibility='hidden';$('#logo-remove-btn').hide();$('[id^=stationLogoRemove]').each(function(i,v){v.style.width=v.style.height=v.style.margin=v.style.padding='0px';});" id="logo-img" onload='/*resizeImg(this, 450, 450);*/' src="<?php echo $src ?>" />
        </div>

        <?php echo $this->element->getElement('locale')->render() ?>

        <?php echo $this->element->getElement('timezone')->render() ?>

        <?php echo $this->element->getElement('weekStartDay')->render() ?>

        <?php echo $this->element->getElement('tracktypeDefault')->render() ?>

        <?php echo $this->element->getElement('stationDefaultFadeIn')->render() ?>

        <?php echo $this->element->getElement('stationDefaultFadeOut')->render() ?>

        <?php echo $this->element->getElement('stationDefaultCrossfadeDuration')->render() ?>

        <?php echo $this->element->getElement('introPlaylistSelect')->render() ?>

        <?php echo $this->element->getElement('outroPlaylistSelect')->render() ?>

        <?php echo $this->element->getElement('podcastAlbumOverride')->render() ?>

        <?php echo $this->element->getElement('podcastAutoSmartblock')->render() ?>

        <?php echo $this->element->getElement('featurePreviewMode')->render() ?>

        <?php echo $this->element->getElement('thirdPartyApi')->render() ?>

        <?php echo $this->element->getElement('scheduleTrimOverbooked')->renderViewHelper() ?>
        <?php echo $this->element->getElement('scheduleTrimOverbooked')->renderLabel() . '<p/>' ?>

        <?php echo $this->element->getElement('radioPageLoginButton')->renderViewHelper() ?>
        <?php echo $this->element->getElement('radioPageLoginButton')->renderLabel() ?>
    </dl>
</fieldset>
