<h3><?php echo _("Live Broadcasting") ?></h3>
<fieldset class="padded stream-setting-global">
    <dl class="zend_form">
        <?php echo $this->element->getElement('auto_transition')->render() ?>
        <span class="icecast_metadata_help_icon" id="auto_transition_help"></span>
        <?php echo $this->element->getElement('auto_switch')->render() ?>
        <span class="icecast_metadata_help_icon" id="auto_switch_help"></span>
        <?php echo $this->element->getElement('transition_fade')->render() ?>

        <fieldset class="padded stream-setting-global" style="margin-top: 15px">
            <legend><?php echo _("Master Source") ?></legend>
            <p class="input-settings-inline-p">
                <?php echo _("Use these settings in your broadcasting software to stream live at any time.") ?>
            </p>
            <?php echo $this->element->getElement('master_username')->render() ?>
            <span class="master_username_help_icon"></span>
            <?php echo $this->element->getElement('master_password')->render() ?>
            <?php echo $this->element->getElement("master_source_host")->render() ?>
            <?php echo $this->element->getElement("master_source_port")->render() ?>
            <?php echo $this->element->getElement("master_source_mount")->render() ?>
        </fieldset>

        <fieldset class="padded stream-setting-global" style="margin-top: 15px">
            <legend><?php echo _("Show Source") ?></legend>
            <p class="input-settings-inline-p">
                <?php echo _("DJs can use these settings in their broadcasting software to broadcast live only during shows assigned to them.") ?>
            </p>
            <?php echo $this->element->getElement("show_source_host")->render() ?>
            <?php echo $this->element->getElement("show_source_port")->render() ?>
            <?php echo $this->element->getElement("show_source_mount")->render() ?>
        </fieldset>
    </dl>
</fieldset>
