<div class="sb-options-form">
    <?php echo $this->element->getElement('sb_date_start'); ?>
    <?php echo $this->element->getElement('sb_time_start'); ?>
    <?php echo $this->element->getElement('sb_date_end'); ?>
    <?php echo $this->element->getElement('sb_time_end'); ?>
    <a id="sb_submit" class="btn btn-small" href="#" title="Display shows in the specified date and time range">
        <i class="icon-white icon-search"></i><span><?php echo _("Find Shows") ?></span>
    </a>

    <?php echo $this->element->getElement('sb_show_filter') ?>

<!--    --><?php //if ($this->element->getElement('sb_my_shows')):?>
<!--        <label>--><?php //echo $this->element->getElement('sb_my_shows')->getLabel(); ?><!--</label>-->
<!--        --><?php //echo $this->element->getElement('sb_my_shows'); ?>
<!--    --><?php //endif;?>
</div>
