<!--<form action="/rest/media" method="post" id="upload_form" class="dropzone dz-clickable" --><?php //if ($this->quotaLimitReached) { ?><!-- class="hidden" --><?php //} ?>
<!--    --><?php //echo $this->csrf ?>
<!--    <div class="dz-message">-->
<!--        --><?php //echo _("Drop files here or click to upload") ?>
<!--    </div>-->
<!--</form>-->

<div id="media_type_nav">
    <div class="btn-group">
        <button id="new_media_selector" class="btn btn-small dropdown-toggle" data-toggle="dropdown">
            New <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li id="new-playlist">
                <a href="#"><?php echo _("Playlist") ?></a>
            </li>
            <li id="new-smart-block">
                <a href="#"><?php echo _("Smart Block") ?></a>
            </li>
            <li id="new-webstream">
                <a href="#"><?php echo _("Webstream") ?></a>
            </li>
        </ul>
    </div>
    <div class="media_type_selector selected" selection_id="1"><?php echo _("Files") ?></div>
    <div class="media_type_selector" selection_id="2"><?php echo _("Playlists") ?></div>
    <div class="media_type_selector" selection_id="3"><?php echo _("Smart Blocks") ?></div>
    <div class="media_type_selector" selection_id="4"><?php echo _("Webstreams") ?></div>
</div>

<div id="library_content" class="lib-content tabs">
    <fieldset class="toggle closed" id="filter_options">
        <legend style="cursor: pointer;">
            <span class="ui-icon ui-icon-triangle-2-n-s"></span>
            <?php echo _("Advanced Search Options") ?>
        </legend>
        <div id="advanced_search" class="advanced_search form-horizontal"></div>
    </fieldset>
    <table id="library_display" cellpadding="0" cellspacing="0" class="datatable">
    </table>
</div>

<div id="show_builder" class="sb-content">
    <div class="sb-timerange">
        <?php echo $this->sb_form; ?>
    </div>
    <table id="show_builder_table" cellpadding="0" cellspacing="0" class="datatable"></table>
</div>

<div id="side_playlist" class="pl-content">
</div>

<?php echo $this->dialog ?>
