
<table id="schedule_block_table">
    <tr>
        <td>
            <form id="add-show-form" method="post" action="" style="display:none;">
            <?php if($this->preloadShowForm){
                echo $this->render('schedule/add-show-form.phtml');
            }?>
            </form>
        </td>
        <td id="schedule_calendar_cell">
            <div id='schedule_calendar' class="ui-widget-content block-shadow padded omega-block"></div>
        </td>
     </tr>
</table>
