<style type="text/css">
#plupload_files input[type="file"] {
    font-size: 200px !important;
}
</style>
<?php $upgradeLink = Application_Common_OsPath::getBaseDir() . "billing/upgrade"; ?>
<?php if ($this->quotaLimitReached) { ?>
    <div class="errors quota-reached">
    <?php printf(_pro("Disk quota exceeded. You cannot upload files until you %s upgrade your storage"),
        "<a target=\"_parent\" href=$upgradeLink>");?></a>.
    </div>
<?php 
}
?>
<!--
<form id="plupload_form" <?php if ($this->quotaLimitReached) { ?> class="hidden" <?php } ?>>
    <?php echo $this->form->getElement('csrf') ?>
    <div id="plupload_files"></div>	
</form>
-->
<div id="upload_form" class="lib-content ui-widget ui-widget-content block-shadow padded <?php if ($this->quotaLimitReached) { ?> hidden <?php } ?>">
    <H2>Upload Audio Files</H2>
    <div>
        <form action="/rest/media" method="post" id="add-media-dropzone" class="dropzone dz-clickable">
            <?php echo $this->form->getElement('csrf') ?>
            <div class="dz-message">
                <?php echo _("Drop files here or click to browse your computer.") ?>
            </div>
        </form>
        <!--
        <div id="filelist">Your browser doesn't have Flash, Silverlight or HTML5 support.</div>
        <br />
         
        <div id="container">
                <a id="pickfiles" href="javascript:;">[Select files]</a>
                <a id="uploadfiles" href="javascript:;">[Upload files]</a>
        </div>
        -->
    </div>
</div>
<div id="plupload_error">
	<table></table>
</div>


<div id="recent_uploads_wrapper" class="lib-content ui-widget ui-widget-content block-shadow">
    <div id="recent_uploads" class="padded">
    
            <div id="recent_uploads_filter">
            <form>
                <input type="radio" name="upload_status" id="upload_status_all" checked></input><label for="upload_status_all"><?php echo _("All")?></label>
                <input type="radio" name="upload_status" id="upload_status_failed"></input><label for="upload_status_failed"><?php echo _("Failed")?></label>
                <input type="radio" name="upload_status" id="upload_status_pending"></input><label for="upload_status_pending"><?php echo _("Pending")?></label>
            </form>        
        </div>
        <H2><?php echo _("Recent Uploads")?></H2>
        <table id="recent_uploads_table" class="datatable lib-content ui-widget ui-widget-content block-shadow alpha-block "
               cellpadding="0" cellspacing="0"></table>
    </div>
    <div style="clear: both;"></div>
</div>
