<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle() ?>
	<?php echo $this->headScript() ?>
	<?php echo $this->headLink() ?>
</head>
<body>

<div id="Panel">
    <div class="logo"></div>
    <?php echo $this->partial('partialviews/header.phtml', array("user" => $this->loggedInAs())) ?>

<?php 	$partial = array('menu.phtml', 'default');
		$this->navigation()->menu()->setPartial($partial); ?>

<?php echo $this->navigation()->menu() ?>
</div>
 
<div class="wrapper" id="content"><?php echo $this->layout()->content ?></div>
</body>
</html>
