<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Airtime</title>
	<?php echo $this->headScript() ?>
	<?php echo $this->headLink() ?>
</head>
<body>

<div id="nav"><?php echo $this->navigation()->menu()->setRenderInvisible(true) ?></div>

<div id="library_content"><?php echo $this->layout()->library ?></div>

<div id="side_playlist"><?php echo $this->layout()->spl ?></div>
 
</body>
</html>
