#!/bin/bash -e

# Location of pypo_cli.py Python script

virtualenv_bin="/usr/lib/airtime/airtime_virtualenv/bin/"
. ${virtualenv_bin}activate

media_monitor_path="/usr/lib/airtime/media-monitor/"
media_monitor_script="media_monitor.py"

api_client_path="/usr/lib/airtime/"

cd ${media_monitor_path}

exec 2>&1

set +e
cat /etc/default/locale | grep -i "LANG=.*UTF-\?8"
set -e
if [ "$?" != "0" ]; then
    echo "non UTF-8 default locale found in /etc/default/locale." > /var/log/airtime/pypo/error.log
    exit 1
fi

export PYTHONPATH=${api_client_path}
export LC_ALL=`cat /etc/default/locale | grep "LANG=" | cut -d= -f2 | tr -d "\n\""`

# Note the -u when calling python! we need it to get unbuffered binary stdout and stderr
exec python -u ${media_monitor_path}${media_monitor_script} > /var/log/airtime/media-monitor/py-interpreter.log 2>&1

# EOF
