<div class="ui-widget ui-widget-content block-shadow simple-formblock clearfix padded-strong preferences">
<h2 style="float:left"><?php echo _("Preferences") ?></h2>
<?php $baseUrl = Application_Common_OsPath::getBaseDir(); ?>
<form method="post" id="pref_form" enctype="multipart/form-data">

    <?php echo $this->form->getElement('submit')->render() ?>
    <div style="clear:both"></div>

    <?php
        echo $this->statusMsg;
        echo $this->form;
    ?>
    <br />
</form>
</div>
