<div class="ui-widget ui-widget-content block-shadow simple-formblock clearfix padded-strong stream-config">
    <h2 style="float:left">Stream Settings</h2>
    <?php if($this->enable_stream_conf == "true"){?>
    <form method="post" action="/Preference/stream-setting" enctype="application/x-www-form-urlencoded">
    <div class="button-bar bottom" id="submit-element" style="float:right">
        <input type="submit" class="ui-button ui-state-default right-floated" value="Save" id="Save" name="Save" />
    </div>
    <div style="clear:both"></div>
    <?php }?>
<?php echo $this->statusMsg;?>
    <fieldset class="padded">
        <legend>Hardware Audio Out</legend>
        <dl class="zend_form">
            <dt id="hardwareOut-label">
                <label class="required" for="EnableHardwareOut">
                <?php echo $this->form->getElement('output_sound_device')->getLabel() ?> :
                </label>
            </dt>
            <dd id="hardwareOut-element">
                <?php echo $this->form->getElement('output_sound_device') ?>
            </dd>
        </dl>
    </fieldset>
    <?php
        for($i=1;$i<=$this->num_stream;$i++){
            echo $this->form->getSubform("s".$i."_subform");
        }
    ?>
    <?php if($this->enable_stream_conf == "true"){?>
    <div class="button-bar bottom" id="submit-element">
        <input type="submit" class="ui-button ui-state-default right-floated" value="Save" id="Save" name="Save" />
    </div>
    <?php }?>
</form>
</div>