<div class="ui-widget ui-widget-content block-shadow simple-formblock clearfix padded-strong stream-config">
    <h2 <?php if($this->enable_stream_conf == "true"){?>style="float:left"<?php }?>>Stream Settings</h2>
    <?php if($this->enable_stream_conf == "true"){?>
    <form method="post" action="/Preference/stream-setting" enctype="application/x-www-form-urlencoded">
    <div class="button-bar bottom" id="submit-element" style="float:right">
        <input type="submit" class="ui-button ui-state-default right-floated" value="Save" id="Save" name="Save" />
    </div>
    <div style="clear:both"></div>
    <?php }?>
<?php echo $this->statusMsg;?>
    <fieldset class="padded stream-setting-global">
        <legend>Global Settings</legend>
        <dl class="zend_form">
        <?php if($this->form->getElement('output_sound_device') != null){?>
            <dt id="hardwareOut-label">
                <label class="required">
                <?php echo $this->form->getElement('output_sound_device')->getLabel() ?> :
                </label>
            </dt>
            <dd id="hardwareOut-element">
                <?php echo $this->form->getElement('output_sound_device') ?>
            </dd>
        <?php } ?>
            <dt id="vorbisMetadata-label">
                <label class="required">
                <?php echo $this->form->getElement('icecast_vorbis_metadata')->getLabel() ?> :
                </label>
            </dt>
            <dd id="vorbisMetadata-element">
                <?php echo $this->form->getElement('icecast_vorbis_metadata') ?>
            </dd>
        </dl>
    </fieldset>
    <?php
        for($i=1;$i<=$this->num_stream;$i++){
            echo $this->form->getSubform("s".$i."_subform");
        }
    ?>
    <?php if($this->enable_stream_conf == "true"){?>
    <div class="button-bar bottom" id="submit-element">
        <input type="submit" class="ui-button ui-state-default right-floated" value="Save" id="Save" name="Save" />
    </div>
    <?php }?>
</form>
</div>