<div class="ui-widget ui-widget-content block-shadow simple-formblock clearfix padded-strong preferences" id="support-feedback-view">
<h2><?php echo $this->section_title?></h2>
<?php $baseUrl = Application_Common_OsPath::getBaseDir(); ?>
    <form method="post" action=<?php echo $baseUrl."Preference/support-setting"?> enctype="multipart/form-data" id="support-feedback-form">
        <div id="support-settings">
            <?php echo $this->statusMsg ?>
            <?php echo $this->form ?>
        </div>
        <div class="button-bar bottom" id="submit-element">
            <?php echo $this->form->getElement('submit')?>
        </div>
    </form>
</div>
