<?php
/**
 * Created by PhpStorm.
 * User: asantoni
 * Date: 17/11/15
 * Time: 2:32 PM
 */
?>

<div id="upgrade-feature-locked">
    <h2>Get a built-in podcast for your radio station.</h2>
    <h3>Upgrade to unlock this feature today. Podcast hosting is included on all Starter, Plus, and Premium plans.</h3>

<p>With our built-in podcast, you can:
        <ul>
            <li>Share your own uploads through your podcast feed for on-demand listening.</li>
            <li>Invite your fans to listen to your podcast on your Radio Page.</li>
            <li>Publish tracks to both SoundCloud and your station podcast with one click.</li>
            <li>Reach more listeners, both offline and mobile with your radio podcast.</li>
    </ul>
    </p>

    <a href="<?php echo(Application_Common_HTTPHelper::getStationUrl() . "billing/upgrade");?>" class="upgrade-cta-button">Upgrade today!</a>
</div>


