<div class="inner_editor_title">
    <h2>
        <?php echo _("Editing ") ?>"<span ng-bind="podcast.title" class="title_obj_name"></span>"
    </h2>
</div>
<div class="inner_editor_wrapper">
    <form class="podcast-metadata">
        <input ng-value="podcast.id" class="obj_id" type="hidden"/>
        <label>
            <?php echo _("Podcast Name") ?>
            <input disabled ng-model="podcast.title" type="text"/>
        </label>
        <label>
            <?php echo _("Podcast URL") ?>
            <input disabled ng-model="podcast.url" type="text"/>
        </label>
    </form>
</div>

<table id="podcast_episodes" class="datatable" cellpadding="0" cellspacing="0"></table>

<div class="btn-toolbar clearfix">
    <div class="btn-group pull-right">
        <button ng-click="discard()" class="btn" type="button" name="cancel">
            <?php echo _("Cancel") ?>
        </button>
    </div>
    <div class='btn-group pull-right'>
        <button ng-click="savePodcast()" class="btn" title='<?php echo _("Save podcast") ?>' type="button">
            <?php echo _("Save") ?>
        </button>
    </div>
    <div class='success' style='display:none'></span></div>
</div>