<div class="angular_wrapper" ng-controller="Podcast">
    <div class="inner_editor_title">
        <h2>
            <?php echo _("Editing ") ?>"<span ng-bind="podcast.title" class="title_obj_name"></span>"
        </h2>
    </div>
    <div class="inner_editor_wrapper">
        <form class="podcast-metadata">
            <input ng-value="podcast.id" class="obj_id" type="hidden"/>
            <div>
                <label for="podcast_name"><?php echo _("Podcast Name: ") ?></label>
                <span class="podcast-metadata-field">{{podcast.title}}</span>
            </div>
            <div>
                <label for="podcast_url"><?php echo _("Podcast URL: ") ?></label>
                <a href="{{podcast.url}}" target="_blank">
                    <span class="podcast-metadata-field">{{podcast.url}}</span>
                </a>
            </div>
            <div style="padding-top: 0.1em;">
                <label for="podcast_auto_ingest"><input name="podcast_auto_ingest" ng-model="podcast.auto_ingest" type="checkbox" class="float-right"/></label>
                <span class="podcast-metadata-field"><?php echo _("Automatically download latest episodes?") ?></span>
            </div>
            <div style="padding-top: 0.1em;">
                <label for="podcast_album_override"><input name="podcast_album_override" ng-model="podcast.album_override" type="checkbox" class="no-float"/></label>
                <span class="podcast-metadata-field"><?php echo _("Override album name with podcast name during ingest."); ?></span>
            </div>
        </form>
    </div>

<!--    <table class="datatable podcast_episodes" cellpadding="0" cellspacing="0"></table>-->

    <div class="btn-toolbar clearfix">
        <div class="btn-group pull-right">
            <button ng-click="discard()" class="btn" type="button" name="cancel">
                <?php echo _("Cancel") ?>
            </button>
        </div>
        <div class='btn-group pull-right'>
            <button ng-click="savePodcast()" class="btn" title='<?php echo _("Save podcast") ?>' type="button">
                <?php echo _("Save") ?>
            </button>
        </div>
        <div class='success' style='display:none'></span></div>
    </div>
</div>
