<div id="podcast_url_dialog">
    <form name="podcast_url_form">
        <?php echo $this->csrf ?>
        <label>
            <?php echo _("Podcast URL"); ?>
            <input type="text" name="url" />
        </label>
        <button class="btn btn-new right-floated" type="button" onclick="AIRTIME.podcast.addPodcast()">
            <?php echo _("Subscribe"); ?>
        </button>
    </form>
</div>