<div class="inner_editor_title">
    <h2>
        <?php echo _("Editing ") ?>"<span ng-bind="podcast.title" class="title_obj_name"></span>"
    </h2>
</div>
<div class="inner_editor_wrapper">
    <form class="podcast-metadata">
        <input ng-value="podcast.id" class="obj_id" type="hidden"/>
        <p>
            <label for="podcast_name">
                <?php echo _("Podcast Name") ?>
            </label>
            <input name="podcast_name" ng-model="podcast.title" type="text"/>
        </p>
        <p>
            <label for="podcast_creator">
                <?php echo _("Podcast Creator") ?>
            </label>
            <input name="podcast_creator" ng-model="podcast.creator" type="text"/>
        </p>
        <p>
            <label for="podcast_url">
                <?php echo _("Podcast URL") ?>
            </label>
            <input disabled name="podcast_url" ng-model="podcast.url" type="text"/>
        </p>
    </form>
</div>

<table class="datatable podcast_episodes" cellpadding="0" cellspacing="0"></table>

<div class="btn-toolbar clearfix">
    <div class="btn-group pull-right">
        <button ng-click="discard()" class="btn" type="button" name="cancel">
            <?php echo _("Cancel") ?>
        </button>
    </div>
    <div class='btn-group pull-right'>
        <button ng-click="saveStationPodcast()" class="btn" title='<?php echo _("Save station podcast") ?>' type="button">
            <?php echo _("Save") ?>
        </button>
    </div>
    <div class='success' style='display:none'></span></div>
</div>