#!/bin/bash
#-------------------------------------------------------------------------------
#  Determine directories, files
#-------------------------------------------------------------------------------

virtualenv_bin="/usr/lib/airtime/airtime_virtualenv/bin/"
. ${virtualenv_bin}activate

# Absolute path to this script
SCRIPT=`readlink -f $0`
# Absolute directory this script is in
SCRIPTPATH=`dirname $SCRIPT`

#-------------------------------------------------------------------------------
#   Do import
#-------------------------------------------------------------------------------
invokePwd=$PWD
cd $SCRIPTPATH && python airtime-update-db-settings.py
