#!/bin/bash
#-------------------------------------------------------------------------------
#   Copyright (c) 2011 Sourcefabric O.P.S.
#
#   This file is part of the Airtime project.
#   http://airtime.sourcefabric.org/
#
#   Airtime is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   Airtime is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Airtime; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
#  This script handles update cue-in/cue-out points for files that already exist
#  in Airtime's library.
#
exec 2>&1
airtime_silan_script="airtime-silan.py"
api_client_path="/usr/lib/airtime/"

virtualenv_bin="/usr/lib/airtime/airtime_virtualenv/bin/"
. ${virtualenv_bin}activate

export PYTHONPATH=${api_client_path}

# Absolute path to this script
SCRIPT=`readlink -f $0`
# Absolute directory this script is in
SCRIPTPATH=`dirname $SCRIPT`

cd $SCRIPTPATH
python ${airtime_silan_script}
