#!/usr/bin/python


# usage: sudo ./airtime-re-silan


import os
import sys
import psycopg2
import subprocess
import json
import datetime

# loading config file
srv_root = "/srv/airtime/stor/"


conn = psycopg2.connect("dbname=airtime user=airtime host=localhost password=airtime")

cur = conn.cursor()
cur.execute("SELECT count(id) FROM cc_files;")
nb = cur.fetchone()[0]


cur.execute("SELECT id, cuein, cueout, length, filepath FROM cc_files;")

cur2 = conn.cursor()

i = 1
for record in cur:
	rid = record[0]
	full_path = srv_root + record[4]
	if os.path.isfile(full_path):
		command = ['silan', '-b', '-f', 'JSON', full_path]
		proc = subprocess.Popen(command, stdout=subprocess.PIPE)
		out = proc.communicate()[0].strip('\r\n')
		info = json.loads(out)
		data = {}
		data['cuein'] = float('{0:f}'.format(info['sound'][0][0]))
		data['cueout'] = float('{0:f}'.format(info['sound'][-1][1]))
		data['length'] = float('{0:f}'.format(info['file duration']))
		print "== " + str(i) + " / " + str(nb) + " =="
		print "  File " + record[4] + " " + str(data)
		cur2.execute("UPDATE cc_files SET cuein=%s, cueout=%s, length=%s WHERE id=%s", (datetime.timedelta(seconds=data['cuein']), datetime.timedelta(seconds=data['cueout']), datetime.timedelta(seconds=data['length']), rid))
		print "  -> " + str(cur2.rowcount) + " update"
		i +=  1

conn.commit()
cur.close()
cur2.close()
conn.close()


