<div id="listenerstat_content" class="alpha-block padded">
    <H2><?php echo _("Listeners")?></H2>
    <div id="flot_placeholder" style="height:300px;margin:0px 50px 0px 50px"></div>
    <div id="legend" style="width:600px;height:70px;margin:0px 50px 0px 50px"></div>
    <div id="date_form" style="float:left; margin:0px 0px">
        <h3 style="padding-left: 0px">Date Range</h3>
        <?php echo $this->date_form; ?>
    </div>
    <div id="errorStatus" style="float:right; width: 400px">
        <h3><?php echo _("Stream Data Collection Status")?></h3>
        <fieldset class="padded stream-setting-global">
        <?php foreach ($this->errorStatus as $k=>$v) {?>
        <div class='stream-status <?php echo ($v == 'OK')? 'status-good' : 'status-error' ?>'><p><?php echo $k?>: <?php echo $v?></p></div>
        <?php }?>
        </fieldset>
    </div>
    <div style="clear: both;"></div>
    <?php $bandwidthLimit = Application_Model_Preference::getBandwidthLimit(); ?>
    <?php if ($bandwidthLimit): ?>
    <?php $bandwidthUsage = Application_Model_Preference::getBandwidthLimitCounter(); ?>
    <?php $percentInUse = sprintf("%01.1f%% ", $bandwidthUsage/$bandwidthLimit*100); ?>
    <div id="bandwidth_usage">
        <div style="padding-bottom: 2px;"><?php echo _("Monthly Listener Bandwidth Usage") ?></div>
        <div class="bandwidth_usage_progress_bar"></div>
        <div class="bandwidth_usage_percent_in_use"><?php echo $percentInUse .  _("in use") ?></div>
        <div class="bandwidth_usage_used" style="width:<?php echo sprintf("%01.1f%%", min(100, $bandwidthUsage/$bandwidthLimit*100)) ?>;"></div>

        <div style="margin-top: 17px; font-size: 12px;"><?php echo sprintf("%01.1fGB of %01.1fGB", $bandwidthUsage/pow(2, 30), $bandwidthLimit/pow(2, 30)); ?></div>
    </div>
    <?php endif; ?>
</div>
