<?php if(count($this->showContent) > 0) : ?>
	<?php foreach($this->showContent as $pl) : ?>
	<li id="g_<?php echo $pl["pl_group"] ?>" >
		<h3 class="ui-accordion-header ui-state-default ui-corner-all">
			<span class="ui-icon ui-icon-triangle-1-e"></span>
            <span class="ui-icon ui-icon-close"></span>
			<div class="sh_pl_name"><?php echo $pl["pl_name"] ?></div>
			<div class="sh_pl_creator"><?php echo $pl["pl_creator"] ?></div>
			<div class="sh_pl_time"><?php echo $pl["pl_length"] ?></div>
		</h3>
		<div class="group_list ui-widget-content ui-corner-bottom" style="display:none">
			<div class="sched_description"><?php echo $pl["pl_description"] ?></div>
			<?php foreach($pl["pl_content"] as $file) : ?>
			<div>
				<span class="sh_file_name"><?php echo $file["f_name"] ?></span>
				<span><?php echo $file["f_length"] ?></span>
			</div>
			<div class="sh_file_artist"><?php echo $file["f_artist"] ?></div>
			<?php endforeach; ?>
		</div>
	</li>
	<?php endforeach; ?>
<?php else : ?>
<li>Nothing Scheduled</li>
<?php endif; ?>

