<div id="show_content_dialog">
<div><?php echo $this->additionalShowInfo; ?></div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="datatable">
    <tr>
        <th>Start</th>
        <th>Title</th>
        <th>Creator</th>
        <th>Album</th>
        <th>Length</th>
        <th>Genre</th>
    </tr>
<?php $i=0; ?>
<?php foreach($this->showContent as $row): ?>
    <tr id="au_<?php echo $row["file_id"] ?>" class="<?php if($i&1){echo "even";}else{echo "odd";}?>">
        <td><?php echo $row["starts"] ?></td>
        <td><?php echo $row["track_title"] ?></td>
        <td><?php echo $row["artist_name"] ?></td>
        <td><?php echo $row["album_title"] ?></td>
        <td class="library_length"><?php echo $row["clip_length"] ?></td>
        <td><?php echo $row["genre"] ?></td>
    </tr>
<?php $i=$i+1; ?>
<?php endforeach; ?>
</table>
<br/>
<div id="show_time_info">
    <span id="show_time_filled" class="time"><?php echo $this->timeFilled; ?></span>
    <div id="show_progressbar"></div>
    <span id="show_length" class="time"><?php echo $this->showLength; ?></span>
</div>
</div>
