<div><!-- jQuery UI changes the styling on the outermost div; use a blank div so as not to break the .wrapper styling-->
    <div class="wrapper">
        <div id="media_selector_wrapper">
            <div class="media_type_selector dashboard_sub_nav" data-selection-id="1">
                <a href="#tracks">
                    <i class='icon-music icon-white'></i>
                    <span class="selector-name"><?php echo _("Tracks") ?></span>
                </a>
            </div>
            <div class="media_type_selector dashboard_sub_nav" data-selection-id="2">
                <a href="#playlists">
                    <i class='icon-list icon-white'></i>
                    <span class="selector-name"><?php echo _("Playlists") ?></span>
                </a>
            </div>
            <div class="media_type_selector dashboard_sub_nav" data-selection-id="3">
                <a href="#smart-blocks">
                    <i class='icon-time icon-white'></i>
                    <span class="selector-name"><?php echo _("Smart Blocks") ?></span>
                </a>
            </div>
            <div class="media_type_selector dashboard_sub_nav" data-selection-id="4">
                <a href="#webstreams">
                    <i class='icon-random icon-white'></i>
                    <span class="selector-name"><?php echo _("Webstreams") ?></span>
                </a>
            </div>
        </div>
        <?php echo $this->csrf ?>

        <div id="library_content" class="lib-content tabs content-pane wide-panel">
            <div>
                <h2 id="library_title"><?php echo _("Dashboard")." - " ?><span id="library_filter"></span></h2>
            </div>
            <div class="panel-header">
                <div id="advanced-options" class="btn-group">
                    <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                    </button>
                    <div id="advanced_search" class="advanced_search form-horizontal dropdown-menu"></div>
                </div>
            </div>
            <div class="outer-datatable-wrapper">
                <table id="library_display" cellpadding="0" cellspacing="0" class="datatable"></table>
            </div>
        </div>

        <div id="show_builder" class="sb-content content-pane wide-panel">
            <div class="panel-header">
                <ul class="nav nav-tabs">
                    <li id="schedule-tab" role="presentation" class="active"><a href="#">Scheduled Shows</a></li>
                </ul>
            </div>
            <div class="outer-datatable-wrapper active-tab">
                <table id="show_builder_table" cellpadding="0" cellspacing="0" class="datatable"></table>
                <div class="sb-timerange">
                    <?php echo $this->sb_form; ?>
                </div>
            </div>
        </div>
    </div>
</div>