<input type="text" id="show_builder_datepicker_start" class="input_text"></input>
<input type="text" id="show_builder_timepicker_start" class="input_text"></input>
<input type="text" id="show_builder_datepicker_end" class="input_text"></input>
<input type="text" id="show_builder_timepicker_end" class="input_text"></input>
<input type="button" id="show_builder_timerange_button" class="ui-button ui-state-default" value="GO"></input>
<table id="show_builder_table" cellpadding="0" cellspacing="0" class="datatable"></table>
