<div class="wrapper">
    <div id="library_content" class="lib-content tabs ui-widget ui-widget-content block-shadow alpha-block padded">
        <?php echo $this->render('library/librarytabs.phtml') ?>
    </div>
    <div id="show_builder" class="sb-content ui-widget ui-widget-content block-shadow omega-block padded">
        <table id="show_builder_table" cellpadding="0" cellspacing="0" class="datatable"></table>
    </div>
</div>
