# This file contains a list of package dependencies.
[common]
# The php-pear package depends on php-(cli|common|xml), be sure to
# install the dependencies with the right php version.
php-pear = focal, bullseye, bookworm, noble, trixie, resolute
php-amqplib = focal, bullseye, bookworm, noble, trixie, resolute

[locale]
gettext = focal, bullseye, bookworm, noble, trixie, resolute

# [apache]
# apache2 = focal, bullseye
# libapache2-mod-php7.4 = focal, bullseye

[php-fpm]
php7.4-fpm = focal, bullseye
php8.2-fpm = bookworm
php8.3-fpm = noble
php8.4-fpm = trixie
php8.5-fpm = resolute

# Focal, Bullseye
[php7.4]
php7.4 = focal, bullseye
php7.4-apcu = focal, bullseye
php7.4-apcu-bc = focal, bullseye
php7.4-bcmath = focal, bullseye
php7.4-cli = focal, bullseye
php7.4-common = focal, bullseye
php7.4-curl = focal, bullseye
php7.4-dev = focal, bullseye
php7.4-gd = focal, bullseye
php7.4-mbstring = focal, bullseye
php7.4-pgsql = focal, bullseye
php7.4-xml = focal, bullseye
php7.4-yaml = focal, bullseye

# Bookworm
[php8.2]
php8.2 = bookworm
php8.2-apcu = bookworm
php8.2-apcu-bc = bookworm
php8.2-bcmath = bookworm
php8.2-cli = bookworm
php8.2-common = bookworm
php8.2-curl = bookworm
php8.2-dev = bookworm
php8.2-gd = bookworm
php8.2-mbstring = bookworm
php8.2-pgsql = bookworm
php8.2-xml = bookworm
php8.2-yaml = bookworm

# Noble
[php8.3]
php8.3 = noble
php8.3-apcu = noble
php8.3-apcu-bc = noble
php8.3-bcmath = noble
php8.3-cli = noble
php8.3-common = noble
php8.3-curl = noble
php8.3-dev = noble
php8.3-gd = noble
php8.3-mbstring = noble
php8.3-pgsql = noble
php8.3-xml = noble
php8.3-yaml = noble

# Trixie
[php8.4]
php8.4 = trixie
php8.4-apcu = trixie
php8.4-apcu-bc = trixie
php8.4-bcmath = trixie
php8.4-cli = trixie
php8.4-common = trixie
php8.4-curl = trixie
php8.4-dev = trixie
php8.4-gd = trixie
php8.4-mbstring = trixie
php8.4-pgsql = trixie
php8.4-xml = trixie
php8.4-yaml = trixie

# Resolute
[php8.5]
php8.5 = resolute
php8.5-apcu = resolute
php8.5-apcu-bc = resolute
php8.5-bcmath = resolute
php8.5-cli = resolute
php8.5-common = resolute
php8.5-curl = resolute
php8.5-dev = resolute
php8.5-gd = resolute
php8.5-mbstring = resolute
php8.5-pgsql = resolute
php8.5-xml = resolute
php8.5-yaml = resolute
