# This file contains a list of package dependencies.
[common]
# The php-pear package depends on php-(cli|common|xml), be sure to
# install the dependencies with the right php version.
php-pear = focal, bullseye, bookworm
php-amqplib = focal, bullseye, bookworm

[locale]
gettext = focal, bullseye, bookworm

# [apache]
# apache2 = focal, bullseye, bookworm
# libapache2-mod-php7.4 = focal, bullseye
# libapache2-mod-php8.2 = bookworm

[php-fpm]
php7.4-fpm = focal, bullseye
php8.2-fpm = bookworm

# Focal, Bullseye
[php7.4]
php7.4 = focal, bullseye
php7.4-apcu = focal, bullseye
php7.4-apcu-bc = focal, bullseye
php7.4-bcmath = focal, bullseye
php7.4-cli = focal, bullseye
php7.4-common = focal, bullseye
php7.4-curl = focal, bullseye
php7.4-dev = focal, bullseye
php7.4-gd = focal, bullseye
php7.4-mbstring = focal, bullseye
php7.4-pgsql = focal, bullseye
php7.4-xml = focal, bullseye
php7.4-yaml = focal, bullseye

# Bookworm
[php8.2]
php8.2 = bookworm
php8.2-apcu = bookworm
php8.2-bcmath = bookworm
php8.2-cli = bookworm
php8.2-common = bookworm
php8.2-curl = bookworm
php8.2-dev = bookworm
php8.2-gd = bookworm
php8.2-mbstring = bookworm
php8.2-pgsql = bookworm
php8.2-xml = bookworm
php8.2-yaml = bookworm
