<div class="ui-widget prefpanel clearfix padded-strong user-management">

    <h2><?php echo _("Manage Users") ?></h2>
    <div class="user-list-wrapper">
        <div id="users_wrapper" class="dataTables_wrapper">

            <div class="button-holder">
                <button type="button" id="add_user_button" name="search_add_group" class="ui-button ui-widget  ui-button-text-icon-primary btn">
                    <span class="ui-icon ui-icon-plusthick"></span>
                    <span class="ui-button-text"><?php echo _("New User")?></span>
                </button>
            </div>

            <table cellspacing="0" cellpadding="0" style="" id="users_datatable" class="datatable">
                <thead>
                    <tr>
                        <th><?php echo _("id") ?></th>
                        <th><?php echo _("Username") ?></th>
                        <th><?php echo _("First Name")?></th>
                        <th><?php echo _("Last Name")?></th>
                        <th><?php echo _("User Type")?></th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
    <div class="user-data simple-formblock" id="user_details">
        <?php echo $this->successMessage ?>
        <fieldset class="padded">
            <?php echo $this->form ?>
        </fieldset>
    </div>
</div>
