# Generated by Django 4.1.7 on 2023-03-06 14:41

from django.db import migrations

from ._migrations import legacy_migration_factory

UP = """
alter table "cc_subjs" add column "is_active" boolean default 't' not null;
"""

DOWN = """
alter table "cc_track_types" drop column if exists "is_active";
"""


class Migration(migrations.Migration):
    dependencies = [
        ("legacy", "0044_add_track_types_analyzer_options"),
    ]

    operations = [
        migrations.RunPython(
            code=legacy_migration_factory(
                target="45",
                sql=UP,
            )
        )
    ]
