<div id="master-panel">
  <div class="now-playing-block">
    <div class="text-row"><strong>Previous:</strong> <span id='previous'></span> <span id='prev-length'></span></div>
    <div class="now-playing-info song">
      <div class="time-flow"><span class="time-elapsed" id="time-elapsed"></span><span class="time-remaining" id="time-remaining"></span></div>
      <span id='current'></span> <span class="length" id="song-length"></span> </div>
    <div class="progressbar">
      <div class="progress-song" id="progress-bar" style="width:0%;"></div>
    </div>
    <div class="text-row next-song"><strong>Next:</strong> <span id='next'></span> <span id='next-length'></span></div>
  </div>
    <div class="show-block">
      <div class="text-row">&nbsp;</div>
      <div class="now-playing-info show">
        <div class="recording-show" style="display: none;"></div>
        <span id="playlist"></span>
        <span id="show-length" class="show-length"></span>
      </div>
      <div class="progressbar">
        <div class="progress-show" id='progress-show' style="width:0%;"></div>
      </div>
    </div>
  <div class="on-air-block">
    <div class="on-air-info off" id="on-air-info">ON AIR</div>
  </div>
  <div class="time-info-block">
    <ul>
      <li>Station time</li>
      <li class="time" id="time"></li>
      <li class="time-zone"><span id="time-zone"></span></li>
    </ul>
  </div>
    <div class="listen-control-block"> 
        <a class="" href="#"><span>Listen</span></a> 
    </div>
  <div class="personal-block">
    <ul>
      <li><span class="name"><?php echo $this->user ?></span> | <a href="/Login/logout">Logout</a></li>
    </ul>
  </div>
  <?php if($this->is_trial){?>
  <div class="trial-box">
      <p>Your Trial expires in</p>
      <div class="trial-box-calendar">
           <span class="trial-box-calendar-white"><?php echo $this->trial_remain?></span>
           <div class="trial-box-calendar-gray">days</div>
      </div>
      <div class="trial-box-button">
            <a title="Purchase your copy of Airtime" href="#">Keep going on</a>
      </div>
  </div>
  <?php }?> 
</div>
<div id="jquery_jplayer_1" class="jp-jplayer" style="width:0px; height:0px;"></div>
