<div id="jp_container_1" class="jp-audio">
	<div id="jquery_jplayer_1" class="jp-jplayer"></div>
    <div class="jp-type-playlist">
        <div class="jp-gui jp-interface">
            <ul class="jp-controls">
                <li class="ui-state-default ui-corner-all jp-previous" style="display:none">
                    <span class="ui-icon ui-icon-seek-prev" tabindex="1"><?php echo _("previous") ?></span>
                </li>
                <li class="ui-state-default ui-corner-all jp-play">
                    <span class="ui-icon ui-icon-play" tabindex="1"><?php echo _("play") ?></span>
                </li>
                <li class="ui-state-default ui-corner-all jp-pause">
                    <span class="ui-icon ui-icon-pause" tabindex="1"><?php echo _("pause") ?></span>
                </li>
                <li class="ui-state-default ui-corner-all jp-next" style="display:none">
                    <span class="ui-icon ui-icon-seek-next" tabindex="1"><?php echo _("next") ?></span>
                </li>
                <li class="ui-state-default ui-corner-all jp-stop">
                    <span class="ui-icon ui-icon-stop" tabindex="1"><?php echo _("stop") ?></span>
                </li>
            </ul>
            <div class="jp-time-block">
                <div class="jp-progress">
                    <div class="jp-seek-bar">
                        <div class="jp-play-bar"></div>
                    </div>
                </div>
                <div class="jp-time-holder">
                    <div class="jp-current-time"></div>
                    <div class="jp-duration" style="display:none"></div>
                </div>
            </div>
            <div class="jp-volume-block">
                <div class="jp-mute">
                    <span class="ui-icon" tabindex="1" title="mute"><?php echo _("mute") ?></span>
                </div>
                <div class="jp-unmute">
                    <span class="ui-icon" tabindex="1" title="unmute"><?php echo _("unmute") ?></span>
                </div>
                <div class="jp-volume-bar">
                    <div class="jp-volume-bar-value"></div>
                </div>
                <div class="jp-volume-max">
                    <span class="ui-icon" tabindex="1" title="max volume"><?php echo _("max volume") ?></span>
                </div>
            </div>
        </div>
        <div class="jp-playlist">
            <ul>
                <li></li>
            </ul>
        </div>
        <div class="jp-no-solution">
            <span><?php echo _("Update Required") ?></span>
            <?php sprintf(_("To play the media you will need to either update your browser to a recent version or update your %sFlash plugin%s."),
                "<a href='http://get.adobe.com/flashplayer/' target='_blank'>",
                "</a>") ?>
        </div>
    </div>
</div>