<?php if($this->is_trial && $this->trial_remain != '' && $this->trial_remain != "Trial expired."){?>
  <div class="trial-box">
      <p><?php echo _("Your trial expires in") ?></p>
      <div class="trial-box-calendar">
           <span class="trial-box-calendar-white"><?php echo $this->trial_remain?></span>
           <div class="trial-box-calendar-gray"><?php echo _("days") ?></div>
      </div>
      <div class="trial-box-button">
            <a title="<?php echo sprintf(_pro("Purchase an %s plan!"), SAAS_PRODUCT_BRANDING_NAME)?>" href="/billing/upgrade"><?php echo _pro("My Account") ?></a>
      </div>
  </div>
<?php }?> 
