<div class="ui-widget prefpanel clearfix padded-strong billing-panel">
<H2>Invoices</H2>
<?php 
$topTextClass = "";
if (array_key_exists("planupdated", $_GET))
{
    $topText = _pro("<b>Thank you!</b> Your plan has been updated and you will be invoiced during your next billing cycle.");
    $topTextClass = "status-good";
}
else {
    $topText = _pro("Tip: To pay an invoice, click \"View Invoice\" and look for the \"Checkout\" button.");
}
    
?>
<p class="<?=$topTextClass?>"><?=$topText?></p>
<table id="invoices_table">
    <tr class="header">
        <th>Date Issued</th>
        <th>Due Date</th>
        <th>Link</th>
        <th>Status</th>
    </tr>
<?php
foreach ($this->invoices as $invoice) {?>
    <tr>
        <td><?php echo $invoice["date"]?></td>
        <td><?php echo $invoice["duedate"]?></td>
        <td><a href="invoice?invoiceid=<?php echo $invoice["id"]?>">View Invoice</a></td>
        <td class="<?=$invoice["status"]==="Unpaid" ? "unpaid" : "";?>"><?php echo $invoice["status"]?></td>
    </tr>
    
<?php };?>
</table>
</div>
