<script language="JavaScript">
    function autoResize(id){
        var newheight;
        var newwidth;

        if(document.getElementById){
            newheight=document.getElementById(id).contentWindow.document.body.scrollHeight;
            // Hack to get height in Firefox
            if (newheight == 0) newheight = newheight = document.getElementById(id).contentWindow.document.documentElement.scrollHeight;
            newwidth=document.getElementById(id).contentWindow.document.body.scrollWidth;
        }
        document.getElementById(id).height= (newheight) + "px";
        document.getElementById(id).width= (newwidth) + "px";
    }
</script>

<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.css"> -->
<link rel="stylesheet" href="/css/bulma.css">

<section class="hero is-dark is-bold is-fullheight">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <header class="navbar">
      <div class="container">
        <div class="navbar-brand">
            <p class="navbar-item"><b><?php echo $this->escape($this->stationName) ?></b></p>
          <span class="navbar-burger" data-target="navbarMenuHeroC">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroC" class="navbar-menu">
          <div class="navbar-end">
            <a id="home-link" class="navbar-item has-text-white" data-tab="home-tab">
              Home
            </a>
            <a id="schedule-link" class="navbar-item has-text-white" data-tab="schedule-tab">
              Schedule
            </a>
            <?php if ($this->displayRssTab) {?>
            <a id="podcast-link" class="navbar-item has-text-white" data-tab="podcast-tab">
              Podcast
            </a>
            <?php } ?>
            <?php if ($this->displayLoginButton): ?>
            <span class="navbar-item">
              <a href="/login" class="button is-warning has-text-white">
                <span>Login</span>
              </a>
            </span>
            <?php endif; ?>
          </div>
        </div>
      </div>
    </header>
  </div>

  <!-- Hero content: will be in the middle -->
    <div class="hero-body" style="margin-bottom: 120px;">
        <div id="home-tab" class="container has-text-centered">
            <?php echo "<a href='#' style='margin-left: auto; margin-right:auto;' class='image is-128x128'><img src='data:image/png;base64," . $this->stationLogo . "'></a>" ?>
            <br>
            <h2 class="subtitle">
                <?php echo $this->escape($this->stationDescription) ?>
            </h2>
        </div>
        <div id="schedule-tab" class="container is-hidden">
            <iframe id="schedule_iframe" height="400px" scrolling="yes" frameborder="0" src="/embed/weekly-program?style=premium"></iframe>
        </div>
        <?php if ($this->displayRssTab) {?>
        <div id="podcast-tab" class="container is-hidden">
            <h2 class="title has-text-centered">Subscribe</h2>
            <div class="columns">
                <div class="column is-one-third">
                    <article class="message">
                        <div class="message-header">
                            <p><?php echo $this->podcastTitle ?></p>
                            <!-- <button id="copyBtn" aria-label="copy">Copy</button> -->
                        </div>
                        <div id="copyURL" class="message-body">
                            <?php echo $this->stationPodcastRssUrl ?>   
                        </div>
                    </article>
                </div>
                <div class="column content has-text-white">
                    <p>To subscribe to this station's podcast, copy and paste the URL into your podcast client.</p>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>

  <!-- Hero footer: will stick at the bottom -->
  <div class="hero-foot">
    <iframe id="player_iframe" frameborder="0" width="100%" style="bottom:0px; left:0px; position:fixed; right:0px;" src="http://192.168.64.53/embed/player?stream=auto&style=premium"></iframe>
  </div>
</section>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', () => {
        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {

        // Add a click event on each of them
        $navbarBurgers.forEach( el => {
            el.addEventListener('click', () => {

            // Get the target from the "data-target" attribute
            const target = el.dataset.target; // ??
            const $target = document.getElementById(target);

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            el.classList.toggle('is-active');
            $target.classList.toggle('is-active');
            });
        });
        }

        $("#navbarMenuHeroC").contents().find('.navbar-item').click(function(){
            var tab_id = $(this).attr('data-tab');

            $(".hero-body").contents().addClass('is-hidden');
            $('.tab_content').addClass('is-hidden');

            window.scrollTo(0,0);
            $(this).removeClass('is-hidden');
            $("#"+tab_id).removeClass('is-hidden');
        });

        // schedule widget tabs
        // $('.tabs li').click(function(){
        //     var tab_id = $(this).attr('data-tab');

        //     $('.tabs li').removeClass('active');
        //     $('.schedule_item').removeClass('active');

        //     $(this).addClass('active');
        //     $("#"+tab_id).addClass('active');
        // });
    });
</script>
