# This file contains a list of package dependencies.
[python]
python3 = focal, bullseye, bookworm
python3-pip = focal, bullseye, bookworm

[psycopg2]
# See https://www.psycopg.org/docs/install.html#install-from-source
build-essential = focal, bullseye, bookworm
python3-dev = focal, bullseye, bookworm
libpq-dev = focal, bullseye, bookworm
