# This file contains a list of package dependencies.
[python]
python3 = bookworm, noble, trixie, resolute
python3-pip = bookworm, noble, trixie, resolute

[psycopg2]
# See https://www.psycopg.org/docs/install.html#install-from-source
build-essential = bookworm, noble, trixie, resolute
python3-dev = bookworm, noble, trixie, resolute
libpq-dev = bookworm, noble, trixie, resolute
