name: Tests PHP

on:
  push:
    branches: [master]
    paths-ignore: ["docs/**"]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize, edited]
    paths-ignore: ["docs/**"]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        # TODO: Enable ubuntu-20.04
        # runs-on: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        runs-on: [ubuntu-16.04, ubuntu-18.04]
        php-version: ["7.0", "7.2"]

    runs-on: ${{ matrix.runs-on }}
    env:
      ENVIRONMENT: testing
      LIBRETIME_LOG_DIR: /tmp/log/libretime

    # TODO: Enable service instead of local postgres
    # services:
    #   postgres:
    #     image: postgres:13
    #     env:
    #       POSTGRES_USER: libretime
    #       POSTGRES_PASSWORD: libretime
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Setup Postgres
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          sudo -u postgres psql -c 'CREATE DATABASE libretime;'
          sudo -u postgres psql -c "CREATE USER libretime WITH PASSWORD 'libretime';"
          sudo -u postgres psql -c 'GRANT CONNECT ON DATABASE libretime TO libretime;'
          sudo -u postgres psql -c 'ALTER USER libretime CREATEDB;'

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          sudo mkdir -p "$LIBRETIME_LOG_DIR"
          sudo chown runner:runner "$LIBRETIME_LOG_DIR"

          composer install --no-progress --dev

      - name: Run tests
        run: |
          pushd airtime_mvc/tests/
          php ../../vendor/bin/phpunit
          popd
