<div class="text-content">
  <h2><?php echo sprintf(_("Welcome to %s!"), PRODUCT_NAME) ?></h2>
<p><?php echo sprintf(_("Here's how you can get started using %s to automate your broadcasts: "), PRODUCT_NAME)?></p>

<ol>
    <li><h4><?php echo _("Upload audio tracks");?></h4>
        <?php echo _("Click the 'Upload' button in the left corner to upload tracks to your library.")?></li>
    <li><h4><?php echo _("Schedule a show");?></h4>
        <?php echo _("Click on 'Calendar' in the navigation bar on the left. From there click the '+ New Show' button and fill out the required fields.")?></li>
    <li><h4><?php echo _("Add tracks to your show"); ?></h4>
        <?php echo _("Click on your show in the calendar and select 'Schedule Show'. In the popup window drag tracks into your show."); ?>
    </li>


</ol>
<p><strong><?php echo _("Now you're good to go!")?></strong><br />
<?php
$userManualAnchorOpen = "<a href='" . USER_MANUAL_URL . "' target='_blank'>";
echo sprintf(_("For more detailed help, read the %suser manual%s."),
    $userManualAnchorOpen, "</a>")

?>
</p>
</div>
